//! Rust code generation for resolved WebIDL metadata.
//!
//! The generated Rust module is checked into `src/` (currently `src/webidl/generated/mod.rs`) and
//! therefore must be:
//! - deterministic (stable diffs),
//! - rustfmt-stable under the repository's `.rustfmt.toml`, and
//! - free of panic/unwrap tokens that would trip `cargo xtask lint-no-panics`.

use super::resolve::{
  ResolvedCallback, ResolvedDictionary, ResolvedEnum, ResolvedInterface, ResolvedInterfaceMember,
  ResolvedInterfaceMixin, ResolvedTypedef, ResolvedWebIdlWorld,
};
use super::ExtendedAttribute;
use anyhow::{bail, Context, Result};
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;
use std::process::Command;

/// Tokens that must not appear in generated Rust sources.
///
/// Note: This is stricter than `cargo xtask lint-no-panics` (which ignores comments/strings), but
/// keeping the generator output free of these tokens anywhere makes it resilient to future linting
/// changes.
pub const FORBIDDEN_TOKENS: [&str; 10] = [
  "panic!",
  "todo!",
  "unimplemented!",
  "assert!",
  "assert_eq!",
  "assert_ne!",
  "unreachable!",
  ".unwrap(",
  ".unwrap()",
  ".expect(",
];

/// Generate a rustfmt-formatted Rust module for the given resolved world.
pub fn generate_rust_module(
  world: &ResolvedWebIdlWorld,
  rustfmt_config_path: &Path,
) -> Result<String> {
  let raw = generate_rust_module_unformatted(world);
  let formatted = rustfmt(&raw, rustfmt_config_path)?;
  ensure_no_forbidden_tokens(&formatted)?;
  Ok(formatted)
}

/// Parse+resolve an IDL input string, then generate a rustfmt-formatted Rust module.
pub fn generate_rust_module_from_idl(idl: &str, rustfmt_config_path: &Path) -> Result<String> {
  let parsed = super::parse_webidl(idl).context("parse WebIDL")?;
  let resolved = super::resolve::resolve_webidl_world(&parsed);
  generate_rust_module(&resolved, rustfmt_config_path)
}

fn generate_rust_module_unformatted(world: &ResolvedWebIdlWorld) -> String {
  let mut out = String::new();

  let _ = writeln!(
    out,
    "// @generated by `cargo xtask webidl`. DO NOT EDIT.\n\
     //\n\
     // Source inputs:\n\
     // - specs/whatwg-dom/dom.bs\n\
     // - specs/whatwg-html/source\n\
     \n\
     use super::*;\n"
  );

  let _ = writeln!(out, "pub const WORLD: WebIdlWorld = WebIdlWorld {{");

  let _ = writeln!(out, "  interfaces: &[");
  for iface in world.interfaces.values() {
    write_interface(&mut out, iface, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "  interface_mixins: &[");
  for mixin in world.interface_mixins.values() {
    write_interface_mixin(&mut out, mixin, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "  dictionaries: &[");
  for dict in world.dictionaries.values() {
    write_dictionary(&mut out, dict, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "  enums: &[");
  for en in world.enums.values() {
    write_enum(&mut out, en, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "  typedefs: &[");
  for td in world.typedefs.values() {
    write_typedef(&mut out, td, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "  callbacks: &[");
  for cb in world.callbacks.values() {
    write_callback(&mut out, cb, 2);
  }
  let _ = writeln!(out, "  ],");

  let _ = writeln!(out, "}};\n");

  out
}

fn write_interface(out: &mut String, iface: &ResolvedInterface, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlInterface {{");

  indent_kv_str(out, indent + 2, "name", &iface.name);
  indent_kv_opt_str(out, indent + 2, "inherits", iface.inherits.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &iface.ext_attrs);

  indent_line(out, indent + 2);
  let _ = writeln!(out, "members: &[");
  for member in &iface.members {
    write_interface_member(out, member, indent + 4);
  }
  indent_line(out, indent + 2);
  let _ = writeln!(out, "],");

  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_interface_mixin(out: &mut String, mixin: &ResolvedInterfaceMixin, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlInterfaceMixin {{");

  indent_kv_str(out, indent + 2, "name", &mixin.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &mixin.ext_attrs);

  indent_line(out, indent + 2);
  let _ = writeln!(out, "members: &[");
  for member in &mixin.members {
    write_interface_member(out, member, indent + 4);
  }
  indent_line(out, indent + 2);
  let _ = writeln!(out, "],");

  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_interface_member(out: &mut String, member: &ResolvedInterfaceMember, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlInterfaceMember {{");
  indent_kv_opt_str(out, indent + 2, "name", member.name.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &member.ext_attrs);
  indent_kv_str(out, indent + 2, "raw", &member.raw);
  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_dictionary(out: &mut String, dict: &ResolvedDictionary, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlDictionary {{");
  indent_kv_str(out, indent + 2, "name", &dict.name);
  indent_kv_opt_str(out, indent + 2, "inherits", dict.inherits.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &dict.ext_attrs);

  indent_line(out, indent + 2);
  let _ = writeln!(out, "members: &[");
  for member in &dict.members {
    indent_line(out, indent + 4);
    let _ = writeln!(out, "WebIdlDictionaryMember {{");
    indent_kv_opt_str(out, indent + 6, "name", member.name.as_deref());
    indent_kv_ext_attrs(out, indent + 6, "ext_attrs", &member.ext_attrs);
    indent_kv_str(out, indent + 6, "raw", &member.raw);
    indent_line(out, indent + 4);
    let _ = writeln!(out, "}},");
  }
  indent_line(out, indent + 2);
  let _ = writeln!(out, "],");

  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_enum(out: &mut String, en: &ResolvedEnum, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlEnum {{");
  indent_kv_str(out, indent + 2, "name", &en.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &en.ext_attrs);

  indent_line(out, indent + 2);
  let _ = writeln!(out, "values: &[");
  for value in &en.values {
    indent_line(out, indent + 4);
    let _ = writeln!(out, "{},", rust_string_literal(value));
  }
  indent_line(out, indent + 2);
  let _ = writeln!(out, "],");

  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_typedef(out: &mut String, td: &ResolvedTypedef, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlTypedef {{");
  indent_kv_str(out, indent + 2, "name", &td.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &td.ext_attrs);
  indent_kv_str(out, indent + 2, "type_", &td.type_);
  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn write_callback(out: &mut String, cb: &ResolvedCallback, indent: usize) {
  indent_line(out, indent);
  let _ = writeln!(out, "WebIdlCallback {{");
  indent_kv_str(out, indent + 2, "name", &cb.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &cb.ext_attrs);
  indent_kv_str(out, indent + 2, "type_", &cb.type_);
  indent_line(out, indent);
  let _ = writeln!(out, "}},");
}

fn indent_kv_str(out: &mut String, indent: usize, key: &str, value: &str) {
  indent_line(out, indent);
  let _ = writeln!(out, "{key}: {},", rust_string_literal(value));
}

fn indent_kv_opt_str(out: &mut String, indent: usize, key: &str, value: Option<&str>) {
  indent_line(out, indent);
  match value {
    Some(v) => {
      let _ = writeln!(out, "{key}: Some({}),", rust_string_literal(v));
    }
    None => {
      let _ = writeln!(out, "{key}: None,");
    }
  }
}

fn indent_kv_ext_attrs(out: &mut String, indent: usize, key: &str, attrs: &[ExtendedAttribute]) {
  indent_line(out, indent);
  let _ = writeln!(out, "{key}: &[");
  for attr in attrs {
    indent_line(out, indent + 2);
    let _ = write!(
      out,
      "WebIdlExtendedAttribute {{ name: {}, value: ",
      rust_string_literal(&attr.name)
    );
    match &attr.value {
      Some(v) => {
        let _ = write!(out, "Some({})", rust_string_literal(v));
      }
      None => out.push_str("None"),
    }
    out.push_str(" },\n");
  }
  indent_line(out, indent);
  let _ = writeln!(out, "],");
}

fn indent_line(out: &mut String, indent: usize) {
  for _ in 0..indent {
    out.push(' ');
  }
}

fn rust_string_literal(value: &str) -> String {
  let mut out = String::with_capacity(value.len() + 2);
  out.push('"');
  for ch in value.chars() {
    out.extend(ch.escape_default());
  }
  out.push('"');
  out
}

pub fn ensure_no_forbidden_tokens(source: &str) -> Result<()> {
  for token in FORBIDDEN_TOKENS {
    if source.contains(token) {
      bail!("generated bindings contain forbidden token: {token}");
    }
  }
  Ok(())
}

/// Format Rust source using the repository's rustfmt config.
pub fn rustfmt(source: &str, rustfmt_config_path: &Path) -> Result<String> {
  let mut input = tempfile::NamedTempFile::new().context("create rustfmt temp file")?;
  input
    .write_all(source.as_bytes())
    .context("write rustfmt input")?;

  let output = Command::new("rustfmt")
    .arg("--edition")
    .arg("2021")
    .arg("--config-path")
    .arg(rustfmt_config_path)
    .args(["--emit", "stdout"])
    .arg(input.path())
    .output()
    .context("run rustfmt")?;

  if !output.status.success() {
    bail!(
      "rustfmt failed with status {}.\nstdout:\n{}\nstderr:\n{}",
      output.status,
      String::from_utf8_lossy(&output.stdout),
      String::from_utf8_lossy(&output.stderr)
    );
  }

  let mut formatted = String::from_utf8(output.stdout).context("decode rustfmt stdout as UTF-8")?;
  if !formatted.ends_with('\n') {
    formatted.push('\n');
  }
  Ok(formatted)
}
