// @generated by `cargo xtask webidl-bindings`. DO NOT EDIT.

use super::DomHost;
use crate::js::webidl::{JsRuntime, VmJsRuntime, WebIdlJsRuntime};
use vm_js::{PropertyKey, Value, VmError};

pub fn install_dom_bindings(rt: &mut VmJsRuntime, host: &mut impl DomHost) -> Result<(), VmError> {
  let k_dom_type: PropertyKey = rt.prop_key("__fastrender_dom_type")?;
  let k_prototype: PropertyKey = rt.prop_key("prototype")?;
  let k_constructor: PropertyKey = rt.prop_key("constructor")?;

  let tag_event_target: Value = rt.alloc_string_value("EventTarget")?;
  let tag_node: Value = rt.alloc_string_value("Node")?;
  let tag_element: Value = rt.alloc_string_value("Element")?;
  let tag_document: Value = rt.alloc_string_value("Document")?;
  let tag_window: Value = rt.alloc_string_value("Window")?;

  let proto_event_target: Value = rt.alloc_object_value()?;
  let ctor_event_target: Value = rt.alloc_function_value({
    let proto: Value = proto_event_target;
    let tag: Value = tag_event_target;
    let k_dom_type: PropertyKey = k_dom_type;
    move |rt, _this, _args| {
      let obj: Value = rt.alloc_object_value()?;
      rt.set_prototype(obj, Some(proto))?;
      rt.define_data_property(obj, k_dom_type, tag, false)?;
      Ok(obj)
    }
  })?;
  rt.define_data_property(ctor_event_target, k_prototype, proto_event_target, false)?;
  rt.define_data_property(proto_event_target, k_constructor, ctor_event_target, false)?;

  let proto_node: Value = rt.alloc_object_value()?;
  let ctor_node: Value = rt.alloc_function_value({
    move |rt, _this, _args| Err(rt.throw_type_error("Illegal constructor"))
  })?;
  rt.define_data_property(ctor_node, k_prototype, proto_node, false)?;
  rt.define_data_property(proto_node, k_constructor, ctor_node, false)?;

  let proto_element: Value = rt.alloc_object_value()?;
  let ctor_element: Value = rt.alloc_function_value({
    move |rt, _this, _args| Err(rt.throw_type_error("Illegal constructor"))
  })?;
  rt.define_data_property(ctor_element, k_prototype, proto_element, false)?;
  rt.define_data_property(proto_element, k_constructor, ctor_element, false)?;

  let proto_document: Value = rt.alloc_object_value()?;
  let ctor_document: Value = rt.alloc_function_value({
    let proto: Value = proto_document;
    let tag: Value = tag_document;
    let k_dom_type: PropertyKey = k_dom_type;
    move |rt, _this, _args| {
      let obj: Value = rt.alloc_object_value()?;
      rt.set_prototype(obj, Some(proto))?;
      rt.define_data_property(obj, k_dom_type, tag, false)?;
      Ok(obj)
    }
  })?;
  rt.define_data_property(ctor_document, k_prototype, proto_document, false)?;
  rt.define_data_property(proto_document, k_constructor, ctor_document, false)?;

  let proto_window: Value = rt.alloc_object_value()?;
  let ctor_window: Value = rt.alloc_function_value({
    move |rt, _this, _args| Err(rt.throw_type_error("Illegal constructor"))
  })?;
  rt.define_data_property(ctor_window, k_prototype, proto_window, false)?;
  rt.define_data_property(proto_window, k_constructor, ctor_window, false)?;

  rt.set_prototype(proto_node, Some(proto_event_target))?;
  rt.set_prototype(proto_element, Some(proto_node))?;
  rt.set_prototype(proto_document, Some(proto_node))?;
  rt.set_prototype(proto_window, Some(proto_event_target))?;

  let k_event_target_add_event_listener: PropertyKey = rt.prop_key("addEventListener")?;
  let fn_event_target_add_event_listener: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_event_target: Value = tag_event_target;
    let tag_node: Value = tag_node;
    let tag_window: Value = tag_window;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document
        || this_type == tag_element
        || this_type == tag_event_target
        || this_type == tag_node
        || this_type == tag_window)
      {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 2 {
        return Err(rt.throw_type_error(&format!(
          "EventTarget.addEventListener: expected at least 2 arguments, got {}",
          args.len()
        )));
      }
      // Overload-style dispatch for `optional (Dictionary or boolean)`.
      // When no third argument is provided, follow the IDL union member order and take the
      // dictionary branch.
      if args.len() >= 3 {
        let opt: Value = args[2];
        if rt.is_boolean(opt) {
          // boolean overload
        } else {
          // dictionary overload
        }
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_event_target,
    k_event_target_add_event_listener,
    fn_event_target_add_event_listener,
    false,
  )?;
  let k_event_target_remove_event_listener: PropertyKey = rt.prop_key("removeEventListener")?;
  let fn_event_target_remove_event_listener: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_event_target: Value = tag_event_target;
    let tag_node: Value = tag_node;
    let tag_window: Value = tag_window;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document
        || this_type == tag_element
        || this_type == tag_event_target
        || this_type == tag_node
        || this_type == tag_window)
      {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 2 {
        return Err(rt.throw_type_error(&format!(
          "EventTarget.removeEventListener: expected at least 2 arguments, got {}",
          args.len()
        )));
      }
      // Overload-style dispatch for `optional (Dictionary or boolean)`.
      // When no third argument is provided, follow the IDL union member order and take the
      // dictionary branch.
      if args.len() >= 3 {
        let opt: Value = args[2];
        if rt.is_boolean(opt) {
          // boolean overload
        } else {
          // dictionary overload
        }
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_event_target,
    k_event_target_remove_event_listener,
    fn_event_target_remove_event_listener,
    false,
  )?;
  let k_event_target_dispatch_event: PropertyKey = rt.prop_key("dispatchEvent")?;
  let fn_event_target_dispatch_event: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_event_target: Value = tag_event_target;
    let tag_node: Value = tag_node;
    let tag_window: Value = tag_window;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document
        || this_type == tag_element
        || this_type == tag_event_target
        || this_type == tag_node
        || this_type == tag_window)
      {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 1 {
        return Err(rt.throw_type_error(&format!(
          "EventTarget.dispatchEvent: expected at least 1 arguments, got {}",
          args.len()
        )));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_event_target,
    k_event_target_dispatch_event,
    fn_event_target_dispatch_event,
    false,
  )?;

  let k_node_node_type: PropertyKey = rt.prop_key("nodeType")?;
  let get_node_node_type: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_node: Value = tag_node;
    move |rt, this, _args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document || this_type == tag_element || this_type == tag_node) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      Ok(Value::Undefined)
    }
  })?;
  rt.define_accessor_property(
    proto_node,
    k_node_node_type,
    get_node_node_type,
    Value::Undefined,
    false,
  )?;
  let k_node_clone_node: PropertyKey = rt.prop_key("cloneNode")?;
  let fn_node_clone_node: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_node: Value = tag_node;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document || this_type == tag_element || this_type == tag_node) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(proto_node, k_node_clone_node, fn_node_clone_node, false)?;
  let k_node_append_child: PropertyKey = rt.prop_key("appendChild")?;
  let fn_node_append_child: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    let tag_element: Value = tag_element;
    let tag_node: Value = tag_node;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document || this_type == tag_element || this_type == tag_node) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 1 {
        return Err(rt.throw_type_error(&format!(
          "Node.appendChild: expected at least 1 arguments, got {}",
          args.len()
        )));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(proto_node, k_node_append_child, fn_node_append_child, false)?;

  let k_element_query_selector: PropertyKey = rt.prop_key("querySelector")?;
  let fn_element_query_selector: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_element: Value = tag_element;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_element) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 1 {
        return Err(rt.throw_type_error(&format!(
          "Element.querySelector: expected at least 1 arguments, got {}",
          args.len()
        )));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_element,
    k_element_query_selector,
    fn_element_query_selector,
    false,
  )?;

  let k_document_body: PropertyKey = rt.prop_key("body")?;
  let get_document_body: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    move |rt, this, _args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      Ok(Value::Undefined)
    }
  })?;
  let set_document_body: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    move |rt, this, _args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_accessor_property(
    proto_document,
    k_document_body,
    get_document_body,
    set_document_body,
    false,
  )?;
  let k_document_create_element: PropertyKey = rt.prop_key("createElement")?;
  let fn_document_create_element: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 1 {
        return Err(rt.throw_type_error(&format!(
          "Document.createElement: expected at least 1 arguments, got {}",
          args.len()
        )));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_document,
    k_document_create_element,
    fn_document_create_element,
    false,
  )?;
  let k_document_query_selector: PropertyKey = rt.prop_key("querySelector")?;
  let fn_document_query_selector: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_document: Value = tag_document;
    move |rt, this, args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_document) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      if args.len() < 1 {
        return Err(rt.throw_type_error(&format!(
          "Document.querySelector: expected at least 1 arguments, got {}",
          args.len()
        )));
      }
      Err(rt.throw_type_error("not implemented"))
    }
  })?;
  rt.define_data_property(
    proto_document,
    k_document_query_selector,
    fn_document_query_selector,
    false,
  )?;

  let k_window_event: PropertyKey = rt.prop_key("event")?;
  let get_window_event: Value = rt.alloc_function_value({
    let k_dom_type: PropertyKey = k_dom_type;
    let tag_window: Value = tag_window;
    move |rt, this, _args| {
      if !rt.is_object(this) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      let this_type: Value = rt.get(this, k_dom_type)?;
      if !(this_type == tag_window) {
        return Err(rt.throw_type_error("Illegal invocation"));
      }
      Ok(Value::Undefined)
    }
  })?;
  rt.define_accessor_property(
    proto_window,
    k_window_event,
    get_window_event,
    Value::Undefined,
    false,
  )?;

  let global: Value = host.global_object();
  let k_global_iface_event_target: PropertyKey = rt.prop_key("EventTarget")?;
  rt.define_data_property(
    global,
    k_global_iface_event_target,
    ctor_event_target,
    false,
  )?;
  let k_global_iface_node: PropertyKey = rt.prop_key("Node")?;
  rt.define_data_property(global, k_global_iface_node, ctor_node, false)?;
  let k_global_iface_element: PropertyKey = rt.prop_key("Element")?;
  rt.define_data_property(global, k_global_iface_element, ctor_element, false)?;
  let k_global_iface_document: PropertyKey = rt.prop_key("Document")?;
  rt.define_data_property(global, k_global_iface_document, ctor_document, false)?;
  let k_global_iface_window: PropertyKey = rt.prop_key("Window")?;
  rt.define_data_property(global, k_global_iface_window, ctor_window, false)?;
  rt.set_prototype(global, Some(proto_window))?;
  rt.define_data_property(global, k_dom_type, tag_window, false)?;
  let document: Value = rt.alloc_object_value()?;
  rt.set_prototype(document, Some(proto_document))?;
  rt.define_data_property(document, k_dom_type, tag_document, false)?;
  let k_global_document: PropertyKey = rt.prop_key("document")?;
  rt.define_data_property(global, k_global_document, document, false)?;
  Ok(())
}
