use crate::accessibility::AccessibilityNode;
use crate::geometry::Rect;
use crate::render_control::StageHeartbeat;
use crate::scroll::ScrollBounds;
use crate::scroll::ScrollState;
use crate::style::media::{ColorScheme, ContrastPreference};
use crate::style::types::CursorKeyword;
use crate::tree::box_tree::SelectControl;
use crate::ui::cancel::CancelGens;
#[cfg(feature = "browser_ui")]
use accesskit::{Node as AccessKitNode, NodeId as AccessKitNodeId};
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc::Sender;
#[cfg(test)]
use std::sync::Mutex;
use std::time::Duration;

pub use crate::interaction::DateTimeInputKind;
pub use crate::interaction::FormSubmission;
pub use crate::interaction::KeyAction;
use tiny_skia::Pixmap;

static NEXT_TAB_ID: AtomicU64 = AtomicU64::new(1);
static NEXT_NAVIGATION_ID: AtomicU64 = AtomicU64::new(1);
static NEXT_DOWNLOAD_ID: AtomicU64 = AtomicU64::new(1);

#[cfg(test)]
pub(crate) static TAB_ID_TEST_LOCK: Mutex<()> = Mutex::new(());
#[cfg(test)]
pub(crate) static NAVIGATION_ID_TEST_LOCK: Mutex<()> = Mutex::new(());

/// Identifier for a browser UI tab.
///
/// This is kept as a thin wrapper to avoid mixing tab ids with other identifiers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TabId(pub u64);

impl TabId {
  /// Generate a new process-unique tab id.
  ///
  /// Intended for UI thread use when creating new tabs.
  pub fn new() -> Self {
    // `fetch_add` returns the previous value.
    //
    // `0` is reserved as an "invalid" `TabId` value, so the counter starts at 1. In the
    // astronomically unlikely event that we wrap around `u64::MAX` (requiring ~1.8e19 allocations
    // in a single process), skip over 0 and keep going rather than panicking.
    loop {
      let id = NEXT_TAB_ID.fetch_add(1, Ordering::Relaxed);
      if id != 0 {
        return Self(id);
      }
    }
  }
}

/// Identifier for a browser navigation.
///
/// This is generated by the browser (UI layer) and is intended to uniquely identify navigation
/// requests/commits within a single process.
///
/// Like [`TabId`], this is kept as a thin wrapper to avoid mixing navigation ids with other
/// identifiers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NavigationId(pub u64);

impl NavigationId {
  /// Generate a new process-unique navigation id.
  ///
  /// `0` is reserved as an "invalid" `NavigationId` value, mirroring `TabId`.
  pub fn new() -> Self {
    loop {
      let id = NEXT_NAVIGATION_ID.fetch_add(1, Ordering::Relaxed);
      if id != 0 {
        return Self(id);
      }
    }
  }
}

/// Identifier for a download managed by the browser UI worker.
///
/// Download ids are process-unique. They are allocated by the worker when handling
/// [`UiToWorker::StartDownload`], and are echoed back by the UI when requesting cancellation via
/// [`UiToWorker::CancelDownload`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DownloadId(pub u64);

impl DownloadId {
  /// Generate a new process-unique download id.
  ///
  /// Intended for worker-thread use when starting new downloads.
  ///
  /// `0` is reserved as an "invalid" `DownloadId` value, mirroring `TabId`.
  pub fn new() -> Self {
    loop {
      let id = NEXT_DOWNLOAD_ID.fetch_add(1, Ordering::Relaxed);
      if id != 0 {
        return Self(id);
      }
    }
  }
}

/// Type of page export requested by the browser UI (e.g. Save Page… / Print…).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PageExportKind {
  SavePage,
  Print,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NavigationReason {
  TypedUrl,
  LinkClick,
  BackForward,
  Reload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RepaintReason {
  Explicit,
  ViewportChanged,
  Scroll,
  Input,
  Navigation,
}

/// Media element kind for native media controls / commands.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaElementKind {
  Audio,
  Video,
}

/// UI-triggered media command for a specific media element (`<audio>`/`<video>`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MediaCommand {
  TogglePlayPause,
  SeekToSeconds(f64),
  SeekBySeconds(f64),
  ToggleMute,
  /// Volume in the inclusive range `0..=1`.
  SetVolume(f64),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WakeReason {
  /// Media playback / A-V timing (video frame presentation, audio scheduling, etc).
  Media,
  /// Generic wakeup reason (future expansion point).
  Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PointerButton {
  None,
  Primary,
  Secondary,
  Middle,
  Back,
  Forward,
  Other(u16),
}

/// Snapshot of modifier keys/buttons active during a pointer event.
///
/// This is part of the UI↔worker protocol, so it must remain small, `Copy`, and independent of any
/// specific windowing backend types (e.g. winit).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct PointerModifiers(u8);

impl PointerModifiers {
  pub const NONE: Self = Self(0);
  pub const CTRL: Self = Self(1 << 0);
  pub const SHIFT: Self = Self(1 << 1);
  pub const ALT: Self = Self(1 << 2);
  pub const META: Self = Self(1 << 3);

  /// Cross-platform "command" modifier (Cmd on macOS, Ctrl elsewhere).
  ///
  /// This is useful for browser-style gestures like Cmd/Ctrl-click to open links in a new tab.
  pub fn command(self) -> bool {
    if cfg!(target_os = "macos") {
      self.meta()
    } else {
      self.ctrl()
    }
  }

  pub fn ctrl(self) -> bool {
    (self.0 & Self::CTRL.0) != 0
  }

  pub fn shift(self) -> bool {
    (self.0 & Self::SHIFT.0) != 0
  }

  pub fn alt(self) -> bool {
    (self.0 & Self::ALT.0) != 0
  }

  pub fn meta(self) -> bool {
    (self.0 & Self::META.0) != 0
  }
}

impl std::ops::BitOr for PointerModifiers {
  type Output = Self;

  fn bitor(self, rhs: Self) -> Self::Output {
    Self(self.0 | rhs.0)
  }
}

impl std::ops::BitOrAssign for PointerModifiers {
  fn bitor_assign(&mut self, rhs: Self) {
    self.0 |= rhs.0;
  }
}

/// Scroll sizing information for the root scroll container (viewport).
///
/// This is intended for UI layers that want to draw scrollbars or otherwise surface scroll state
/// without having to re-run layout queries.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ScrollMetrics {
  /// Viewport size in CSS pixels (matches [`RenderedFrame::viewport_css`]).
  pub viewport_css: (u32, u32),
  /// Current viewport scroll offset in CSS pixels (matches `RenderedFrame.scroll_state.viewport`).
  pub scroll_css: (f32, f32),
  /// Scroll bounds for the root scroll container in CSS pixels.
  ///
  /// For typical documents this is `min_* = 0` and `max_* = content_* - viewport_*`.
  pub bounds_css: ScrollBounds,
  /// Content size for the root scroll container in CSS pixels.
  pub content_css: (f32, f32),
}

/// A single `<option>` entry surfaced in an `<input list=...>` datalist popup.
///
/// This is part of the UI↔worker protocol. It contains only the information needed by UIs to render
/// the suggestion list and report a user choice back to the worker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DatalistOption {
  /// Stable pre-order DOM id for the `<option>` element.
  pub option_node_id: usize,
  /// The value that would be applied to the `<input>` if this option is chosen.
  pub value: String,
  /// True when the option is disabled and must not be selectable.
  pub disabled: bool,
}

/// High-level pointer cursor semantics reported by the render worker.
///
/// This intentionally mirrors a small subset of common browser cursor types so UIs can map them to
/// platform cursor icons.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CursorKind {
  Default,
  /// Hide the OS cursor (CSS `cursor: none`).
  Hidden,
  Pointer,
  Text,
  Crosshair,
  NotAllowed,
  Grab,
  Grabbing,
  Help,
  Wait,
  Progress,
  Move,
  Copy,
  ZoomIn,
  ZoomOut,
  EwResize,
  NsResize,
}

impl Default for CursorKind {
  fn default() -> Self {
    CursorKind::Default
  }
}

impl CursorKind {
  /// Map a CSS [`CursorKeyword`] to a high-level [`CursorKind`].
  ///
  /// Returns `None` for [`CursorKeyword::Auto`], which indicates the UA should choose a cursor based
  /// on the hovered element's semantics (e.g. links → pointer, selectable text → text caret).
  pub fn from_css_cursor_keyword(keyword: CursorKeyword) -> Option<Self> {
    match keyword {
      CursorKeyword::Auto => None,
      CursorKeyword::Default => Some(CursorKind::Default),
      CursorKeyword::None => Some(CursorKind::Hidden),
      CursorKeyword::Help => Some(CursorKind::Help),
      CursorKeyword::Pointer => Some(CursorKind::Pointer),
      CursorKeyword::Text | CursorKeyword::VerticalText => Some(CursorKind::Text),
      CursorKeyword::Crosshair => Some(CursorKind::Crosshair),
      CursorKeyword::NotAllowed | CursorKeyword::NoDrop => Some(CursorKind::NotAllowed),
      CursorKeyword::Grab => Some(CursorKind::Grab),
      CursorKeyword::Grabbing => Some(CursorKind::Grabbing),
      CursorKeyword::Wait => Some(CursorKind::Wait),
      CursorKeyword::Progress => Some(CursorKind::Progress),
      CursorKeyword::Move | CursorKeyword::AllScroll => Some(CursorKind::Move),
      CursorKeyword::Copy | CursorKeyword::Alias => Some(CursorKind::Copy),
      CursorKeyword::ZoomIn => Some(CursorKind::ZoomIn),
      CursorKeyword::ZoomOut => Some(CursorKind::ZoomOut),
      CursorKeyword::NResize | CursorKeyword::SResize => Some(CursorKind::NsResize),
      CursorKeyword::EResize | CursorKeyword::WResize => Some(CursorKind::EwResize),
      CursorKeyword::EwResize | CursorKeyword::ColResize => Some(CursorKind::EwResize),
      CursorKeyword::NsResize | CursorKeyword::RowResize => Some(CursorKind::NsResize),
      // Degrade gracefully for cursor keywords that do not have a dedicated `CursorKind` variant.
      _ => Some(CursorKind::Default),
    }
  }
}

/// An owned rendered frame produced by the render worker.
///
/// This owns the underlying pixel buffer (`tiny_skia::Pixmap`) and is expected to be sent to the
/// UI thread by move (avoid cloning large pixmaps).
pub struct RenderedFrame {
  pub pixmap: Pixmap,
  pub viewport_css: (u32, u32),
  pub dpr: f32,
  pub scroll_state: ScrollState,
  pub scroll_metrics: ScrollMetrics,
  /// Schedule hint for the next [`UiToWorker::Tick`] the UI should deliver for this tab.
  ///
  /// This is a high-level "time-based effects" signal:
  ///
  /// - `None` means the worker does not currently need periodic ticks (no active time-based effects
  ///   such as CSS animations/transitions, animated images, JS timers/`requestAnimationFrame`, etc).
  /// - `Some(d)` means the UI should send a tick after approximately `d` has elapsed so the worker
  ///   can advance time-based state and repaint if needed.
  ///
  /// This replaces the older `wants_ticks: bool` flag so workers can request more nuanced wake-up
  /// cadences (e.g. 60fps CSS animations vs. coarser timer/media deadlines).
  pub next_tick: Option<Duration>,
}

/// A suggestion row shown in a `<datalist>` popup for an `<input list=...>` control.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DatalistSuggestion {
  /// Value that should be inserted into the input when selected.
  pub value: String,
  /// Optional label text shown alongside `value`.
  pub label: Option<String>,
}

/// Media preference defaults supplied by the browser UI (theme/accessibility settings).
///
/// These are used to populate the page’s media-query surface (`prefers-*`) when explicit renderer
/// overrides (e.g. `FASTR_PREFERS_COLOR_SCHEME`) are not set.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct BrowserMediaPreferences {
  pub prefers_color_scheme: ColorScheme,
  pub prefers_contrast: ContrastPreference,
  pub prefers_reduced_motion: bool,
}

impl Default for BrowserMediaPreferences {
  fn default() -> Self {
    Self {
      prefers_color_scheme: ColorScheme::Light,
      prefers_contrast: ContrastPreference::NoPreference,
      prefers_reduced_motion: false,
    }
  }
}

impl std::fmt::Debug for RenderedFrame {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.debug_struct("RenderedFrame")
      .field("pixmap_px", &(self.pixmap.width(), self.pixmap.height()))
      .field("viewport_css", &self.viewport_css)
      .field("dpr", &self.dpr)
      .field("scroll_state", &self.scroll_state)
      .field("scroll_metrics", &self.scroll_metrics)
      .field("next_tick", &self.next_tick)
      .finish()
  }
}

/// AccessKit subtree update representing the *page/document* accessibility tree for a tab.
///
/// This is emitted by the render worker alongside [`WorkerToUi::FrameReady`] so the windowed
/// browser UI can merge the document subtree into its overall AccessKit tree (browser chrome + page).
#[cfg(feature = "browser_ui")]
#[derive(Debug)]
pub struct PageAccessKitSubtree {
  /// Root node id for this subtree (typically a per-tab deterministic id).
  pub root_id: accesskit::NodeId,
  /// All nodes in the subtree (including `root_id`).
  pub nodes: Vec<(accesskit::NodeId, accesskit::Node)>,
  /// Focused node within the subtree, when any.
  pub focus_id: Option<accesskit::NodeId>,
}

/// Lightweight page AccessKit state update (focus/bounds/etc) emitted by the worker.
///
/// This is intended for high-frequency changes (e.g. focus changes) without rebuilding/sending the
/// entire page subtree.
#[cfg(feature = "browser_ui")]
#[derive(Debug)]
pub struct PageAccessKitStateUpdate {
  /// Focused node within the subtree, when any.
  pub focus_id: Option<AccessKitNodeId>,
  /// Nodes to update (id → node). Each entry replaces the prior node definition for that id.
  pub nodes: Vec<(AccessKitNodeId, AccessKitNode)>,
}

/// Messages sent from the UI thread to the render worker.
#[derive(Debug)]
pub enum UiToWorker {
  /// Update browser appearance-derived media preferences used for page rendering.
  ///
  /// The worker should treat these values as **defaults**: explicit renderer overrides (e.g.
  /// `FASTR_PREFERS_COLOR_SCHEME`, `FASTR_PREFERS_CONTRAST`, `FASTR_PREFERS_REDUCED_MOTION`) take
  /// precedence when set.
  SetMediaPreferences {
    prefs: BrowserMediaPreferences,
  },
  /// Configure whether the worker should emit [`WorkerToUi::DebugLog`] messages.
  ///
  /// When disabled, the worker should suppress debug-log emission entirely so production runs that
  /// do not display the debug log UI do not pay for high-volume debug-log message delivery.
  ///
  /// This does **not** affect user-facing error reporting: critical problems should continue to be
  /// surfaced via [`WorkerToUi::Warning`], navigation failure, etc.
  SetDebugLogEnabled {
    enabled: bool,
  },
  /// Enable/disable page accessibility subtree updates for a tab (AccessKit).
  ///
  /// When disabled, the worker should avoid rebuilding/sending the page accessibility tree.
  #[cfg(feature = "browser_ui")]
  SetPageA11yEnabled {
    tab_id: TabId,
    enabled: bool,
  },
  CreateTab {
    tab_id: TabId,
    /// Optional URL to navigate immediately after creating the tab.
    ///
    /// When `None`, the tab is created in an "empty" state and will not produce any navigation or
    /// frame messages until the UI sends an explicit [`UiToWorker::Navigate`].
    ///
    /// UIs that want a default page (for example `about:newtab`) should provide it explicitly.
    initial_url: Option<String>,
    /// Per-tab cancellation generations shared with the UI thread.
    ///
    /// The UI should retain a clone of this `CancelGens` in its per-tab model and bump gens
    /// *before* sending new actions so long-running prepare/layout/paint work can be cooperatively
    /// cancelled mid-flight.
    cancel: CancelGens,
  },
  /// Optional alias for [`UiToWorker::CreateTab`].
  ///
  /// Kept for protocol flexibility as the browser UI evolves.
  NewTab {
    tab_id: TabId,
    /// Optional URL to navigate immediately after creating the tab.
    ///
    /// See [`UiToWorker::CreateTab`] for semantics.
    initial_url: Option<String>,
  },
  CloseTab {
    tab_id: TabId,
  },
  SetActiveTab {
    tab_id: TabId,
  },
  /// Navigate to a new URL (typed in the address bar or clicked on the page).
  Navigate {
    tab_id: TabId,
    url: String,
    reason: NavigationReason,
  },
  /// Navigate using an explicit request (method + headers + optional body), e.g. form POST.
  NavigateRequest {
    tab_id: TabId,
    request: FormSubmission,
    reason: NavigationReason,
  },
  /// Navigate to the previous history entry for this tab.
  ///
  /// The worker owns history state, so the UI does not provide a URL.
  GoBack {
    tab_id: TabId,
  },
  /// Navigate to the next history entry for this tab.
  ///
  /// The worker owns history state, so the UI does not provide a URL.
  GoForward {
    tab_id: TabId,
  },
  /// Reload the current history entry for this tab.
  ///
  /// The worker owns history state, so the UI does not provide a URL.
  Reload {
    tab_id: TabId,
  },
  /// Cancel the current in-flight navigation and/or paint work for a tab.
  ///
  /// This mirrors the "Stop loading" browser chrome action:
  /// - Keep the currently committed document visible (do not navigate to an error page).
  /// - Clear any provisional/pending navigation state (including provisional history entries).
  /// - Set `loading=false` promptly so the chrome can toggle from stop → reload.
  StopLoading {
    tab_id: TabId,
  },
  /// Periodic "tick" from the UI thread used to drive time-based effects and the repaint pipeline.
  ///
  /// The render worker should advance any time-based effects (CSS animations/transitions, animated
  /// images, JS timers/rAF, etc), execute a bounded slice of JS/event-loop work, and, if the tab
  /// becomes dirty, render a new frame.
  ///
  /// This message is intentionally a **wake-up signal**, not a master time source: it does not
  /// carry an absolute timestamp.
  ///
  /// The included [`UiToWorker::Tick::delta`] is best-effort (and may be injected by deterministic
  /// harnesses). Subsystems that require an authoritative clock (especially audio/video playback)
  /// must query their own clocks rather than inferring time from tick cadence or accumulated deltas.
  /// See `docs/media_clocking.md`.
  Tick {
    tab_id: TabId,
    /// Time elapsed since the previous tick delivered for this tab.
    ///
    /// For deterministic harnesses, this can be an injected delta (e.g. exactly 16ms) instead of
    /// being derived from wall-clock time.
    ///
    /// The worker may coalesce back-to-back ticks by summing their deltas.
    delta: Duration,
  },
  ViewportChanged {
    tab_id: TabId,
    viewport_css: (u32, u32),
    dpr: f32,
  },
  Scroll {
    tab_id: TabId,
    delta_css: (f32, f32),
    /// Pointer position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    /// The worker is responsible for converting viewport-local coords to page coords by adding the
    /// current scroll offset.
    pointer_css: Option<(f32, f32)>,
  },
  /// Scroll the viewport to an absolute position (in CSS px).
  ///
  /// Unlike [`UiToWorker::Scroll`], this does not attempt to target element scroll containers under
  /// the pointer; it is intended for UI scrollbars and programmatic scrolling.
  ScrollTo {
    tab_id: TabId,
    pos_css: (f32, f32),
  },
  /// Forward an AccessKit [`accesskit::ActionRequest`] targeting the page content.
  ///
  /// This is used by the windowed browser UI (feature = `browser_ui`) to allow assistive
  /// technologies to request operations (for example scrolling a node into view) without going
  /// through the normal pointer/keyboard focus pipeline.
  ///
  /// Note: some UI surfaces (like the rendered-page host widget) may not have a stable DOM target
  /// node id to attach. In those cases callers may use a synthetic/unknown `request.target`; workers
  /// should fall back to the currently focused node where applicable.
  #[cfg(feature = "browser_ui")]
  AccessKitActionRequest {
    tab_id: TabId,
    request: accesskit::ActionRequest,
  },
  PointerMove {
    tab_id: TabId,
    /// Pointer position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    /// The worker is responsible for converting viewport-local coords to page coords by adding the
    /// current scroll offset.
    pos_css: (f32, f32),
    button: PointerButton,
    modifiers: PointerModifiers,
  },
  PointerDown {
    tab_id: TabId,
    /// Pointer position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    /// The worker is responsible for converting viewport-local coords to page coords by adding the
    /// current scroll offset.
    pos_css: (f32, f32),
    button: PointerButton,
    modifiers: PointerModifiers,
    /// Consecutive click count reported by the UI layer (1 = single click, 2 = double click, ...).
    ///
    /// This is used for browser-style text selection gestures in `<input>`/`<textarea>` (double
    /// click selects a word; triple click selects a line / all).
    ///
    /// UIs that do not implement multi-click detection should always send `1`.
    click_count: u8,
  },
  PointerUp {
    tab_id: TabId,
    /// Pointer position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    /// The worker is responsible for converting viewport-local coords to page coords by adding the
    /// current scroll offset.
    pos_css: (f32, f32),
    button: PointerButton,
    modifiers: PointerModifiers,
  },
  /// Drop one or more local files onto the page at `pos_css`.
  ///
  /// This is primarily used to support native OS drag-and-drop for `<input type="file">` controls.
  /// The worker is responsible for hit-testing and applying HTML `multiple` semantics.
  DropFiles {
    tab_id: TabId,
    /// Drop position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    pos_css: (f32, f32),
    /// File paths provided by the OS/UI layer.
    paths: Vec<PathBuf>,
  },
  /// Request a page hit-test for context menu purposes.
  ///
  /// The worker responds with [`WorkerToUi::ContextMenu`] containing resolved link/image URLs (when
  /// the hit target is a link/image) plus context-sensitive clipboard/editing capability flags.
  ContextMenuRequest {
    tab_id: TabId,
    /// Pointer position in **viewport-local CSS pixels** (0,0 at the top-left of the rendered
    /// viewport).
    ///
    /// This coordinate does **not** include the current scroll offset (`ScrollState.viewport`).
    /// The worker is responsible for converting viewport-local coords to page coords by adding the
    /// current scroll offset.
    pos_css: (f32, f32),
    /// Modifier key state at the time the context menu request was initiated.
    ///
    /// This is used to populate the cancelable JS `contextmenu` `MouseEvent` dispatched by the
    /// render worker so pages can implement modifier-sensitive context menus.
    modifiers: PointerModifiers,
  },
  /// User chose an option in a dropdown `<select>` popup.
  ///
  /// The UI should send this after receiving [`WorkerToUi::SelectDropdownOpened`].
  ///
  /// Workers typically respond with [`WorkerToUi::SelectDropdownClosed`] so UIs can dismiss the
  /// popup deterministically, even when the selection is a no-op (choosing the already-selected
  /// option).
  SelectDropdownChoose {
    tab_id: TabId,
    select_node_id: usize,
    option_node_id: usize,
  },
  /// User dismissed an open dropdown `<select>` popup without choosing an option.
  ///
  /// Front-ends typically send this when the user presses Escape or clicks outside the popup.
  /// Workers may treat this as a no-op or use it to emit [`WorkerToUi::SelectDropdownClosed`].
  SelectDropdownCancel {
    tab_id: TabId,
  },
  /// User chose an option in a `<datalist>` popup associated with an `<input list=...>` control.
  ///
  /// The UI should send this after receiving [`WorkerToUi::DatalistOpened`].
  ///
  /// Workers should respond with [`WorkerToUi::DatalistClosed`] so front-ends can dismiss the popup
  /// deterministically, even when applying the choice is a no-op (e.g. choosing the already-set
  /// value, choosing a disabled option, or spoofing an option id).
  DatalistChoose {
    tab_id: TabId,
    /// The `<input>` element that owns the datalist popup.
    input_node_id: usize,
    /// The `<option>` element chosen by the user.
    option_node_id: usize,
  },
  /// User dismissed an open `<datalist>` popup without choosing an option.
  ///
  /// Front-ends typically send this when the user presses Escape or clicks outside the popup.
  /// Workers may treat this as a no-op or use it to emit [`WorkerToUi::DatalistClosed`].
  DatalistCancel {
    tab_id: TabId,
  },
  /// User chose a value in a date/time picker popup.
  ///
  /// The UI should send this after receiving [`WorkerToUi::DateTimePickerOpened`].
  DateTimePickerChoose {
    tab_id: TabId,
    input_node_id: usize,
    /// The raw value string; workers apply HTML sanitization based on the input type.
    value: String,
  },
  /// User dismissed an open date/time picker popup without choosing a value.
  ///
  /// Front-ends typically send this when the user presses Escape or clicks outside the popup.
  /// Workers may treat this as a no-op or use it to emit [`WorkerToUi::DateTimePickerClosed`].
  DateTimePickerCancel {
    tab_id: TabId,
  },
  /// User chose a color in a color picker popup for an `<input type=color>` control.
  ///
  /// The UI should send this after receiving [`WorkerToUi::ColorPickerOpened`].
  ColorPickerChoose {
    tab_id: TabId,
    input_node_id: usize,
    /// The raw value string; workers apply HTML sanitization rules for `type=color` (simple color).
    value: String,
  },
  /// User dismissed an open color picker popup without choosing a value.
  ///
  /// Front-ends typically send this when the user presses Escape or clicks outside the popup.
  /// Workers may treat this as a no-op or use it to emit [`WorkerToUi::ColorPickerClosed`].
  ColorPickerCancel {
    tab_id: TabId,
  },
  /// User chose one or more files in a file picker popup for an `<input type=file>` control.
  ///
  /// The UI should send this after receiving [`WorkerToUi::FilePickerOpened`].
  FilePickerChoose {
    tab_id: TabId,
    input_node_id: usize,
    paths: Vec<std::path::PathBuf>,
  },
  /// User dismissed an open file picker popup without choosing files.
  ///
  /// Front-ends typically send this when the user presses Escape or clicks outside the popup.
  /// Workers may treat this as a no-op or use it to emit [`WorkerToUi::FilePickerClosed`].
  FilePickerCancel {
    tab_id: TabId,
  },
  TextInput {
    tab_id: TabId,
    text: String,
  },
  /// Assistive-tech hook: replace the full value of a text control (`<input>`/`<textarea>`) by DOM
  /// pre-order id.
  ///
  /// This is intended for screen readers and other accessibility clients that send a single "set
  /// value" request rather than synthesizing a stream of key events.
  A11ySetTextValue {
    tab_id: TabId,
    /// Pre-order DOM node id of the target `<input>`/`<textarea>`.
    node_id: usize,
    value: String,
  },
  /// Assistive-tech hook: set the selection range for a focused text control.
  ///
  /// `anchor` and `focus` are character indices (not bytes).
  ///
  /// The worker clamps indices into the current value length.
  A11ySetTextSelectionRange {
    tab_id: TabId,
    /// Pre-order DOM node id of the focused `<input>`/`<textarea>`.
    node_id: usize,
    anchor: usize,
    focus: usize,
  },
  /// IME preedit update for the focused page text control (input/textarea).
  ///
  /// This represents an in-progress composition string that should be rendered at the caret
  /// position but **not** committed to the DOM value until an [`UiToWorker::ImeCommit`] arrives.
  ImePreedit {
    tab_id: TabId,
    text: String,
    /// Cursor/selection range within `text`, when provided by the platform IME.
    cursor: Option<(usize, usize)>,
  },
  /// IME commit for the focused page text control (input/textarea).
  ///
  /// This is the final committed text from the platform IME and should be inserted into the DOM
  /// value at the caret.
  ImeCommit {
    tab_id: TabId,
    text: String,
  },
  /// Cancels any active IME composition for the focused page text control.
  ImeCancel {
    tab_id: TabId,
  },
  /// Paste text into the currently focused text control (input/textarea).
  ///
  /// The worker is responsible for applying the text at the caret, replacing any selection, and
  /// respecting inert/disabled/readonly rules.
  ///
  /// Security: UIs should clamp `text` to [`crate::ui::clipboard::MAX_CLIPBOARD_TEXT_BYTES`] bytes
  /// before sending. Workers should treat this message as untrusted and may defensively clamp again.
  Paste {
    tab_id: TabId,
    text: String,
  },
  /// Copy the current selection in the focused text control (input/textarea) to the clipboard.
  ///
  /// This should not mutate the DOM; workers respond by sending
  /// [`WorkerToUi::SetClipboardText`].
  Copy {
    tab_id: TabId,
  },
  /// Cut the current selection in the focused text control (input/textarea) to the clipboard.
  ///
  /// Workers respond by sending [`WorkerToUi::SetClipboardText`], and delete the selection when
  /// the control is editable.
  Cut {
    tab_id: TabId,
  },
  /// Select all text in the currently focused text control (input/textarea).
  SelectAll {
    tab_id: TabId,
  },
  KeyAction {
    tab_id: TabId,
    key: KeyAction,
  },
  /// Clear focus within the rendered page for the given tab (blur the currently focused element).
  ///
  /// Windowed UIs treat the rendered page as a focusable widget for routing keyboard input. When
  /// focus moves to browser chrome (address bar, menus, toolbar), the worker must be notified so it
  /// can clear the page's focused element and associated paint state (caret, focus ring /
  /// `:focus-visible`).
  ClearPageFocus {
    tab_id: TabId,
  },
  /// Accessibility action: set accessibility focus to a DOM node.
  ///
  /// `node_id` is a DOM pre-order traversal id (matching `InteractionState`), not the element's
  /// `"id"` attribute.
  ///
  /// UI front-ends should translate platform accessibility action requests (e.g. AccessKit) into
  /// this internal protocol message. This keeps the UI↔worker protocol independent of any specific
  /// accessibility backend types.
  A11ySetFocus {
    tab_id: TabId,
    node_id: usize,
  },
  /// Accessibility action: activate the node's default action (e.g. click a link/button).
  ///
  /// `node_id` is a DOM pre-order traversal id (matching `InteractionState`).
  A11yActivate {
    tab_id: TabId,
    node_id: usize,
  },
  /// Accessibility action: scroll the node into view without changing focus.
  ///
  /// `node_id` is a DOM pre-order traversal id (matching `InteractionState`).
  A11yScrollIntoView {
    tab_id: TabId,
    node_id: usize,
  },
  /// Accessibility action: show the context menu for a node (assistive technology / screen readers).
  ///
  /// `node_id` is a DOM pre-order traversal id (matching `InteractionState`).
  ///
  /// When `None`, workers may fall back to the currently focused node.
  A11yShowContextMenu {
    tab_id: TabId,
    node_id: Option<usize>,
  },
  /// Accessibility action: set the node's value (e.g. textbox contents).
  ///
  /// `node_id` is a DOM pre-order traversal id (matching `InteractionState`).
  A11ySetValue {
    tab_id: TabId,
    node_id: usize,
    value: String,
  },
  /// Send a user action to a media element (play/pause, seek, volume, mute).
  MediaCommand {
    tab_id: TabId,
    node_id: usize,
    command: MediaCommand,
  },
  /// Begin/update an active "find in page" query for this tab.
  ///
  /// An empty query clears all find highlights/results for the tab.
  FindQuery {
    tab_id: TabId,
    query: String,
    case_sensitive: bool,
  },
  /// Jump to the next match for the active find query.
  FindNext {
    tab_id: TabId,
  },
  /// Jump to the previous match for the active find query.
  FindPrev {
    tab_id: TabId,
  },
  /// Explicitly stop/close find in page for this tab (clears highlights/results).
  ///
  /// This is equivalent to sending [`UiToWorker::FindQuery`] with an empty query, but is exposed as
  /// a distinct message for clearer front-end UX and intent.
  FindStop {
    tab_id: TabId,
  },
  RequestRepaint {
    tab_id: TabId,
    reason: RepaintReason,
  },
  SelectDropdownPick {
    tab_id: TabId,
    select_node_id: usize,
    item_index: usize,
  },
  /// Configure the download directory used by the worker for subsequent downloads.
  ///
  /// This is intended to be sent once on browser startup, but can be updated at runtime.
  SetDownloadDirectory {
    path: PathBuf,
  },
  /// Start a download for a URL, saving into the configured download directory.
  StartDownload {
    tab_id: TabId,
    url: String,
    /// Optional filename hint (e.g. from `download=` attribute or UI override).
    filename_hint: Option<String>,
  },
  /// Cancel an in-flight download.
  CancelDownload {
    tab_id: TabId,
    download_id: DownloadId,
  },
  /// Export the current page contents to a file (Save Page… / Print…).
  ///
  /// Workers are expected to write outputs atomically (write to a sibling `.part` file and rename on
  /// success) to avoid leaving partially-written outputs behind.
  PageExport {
    tab_id: TabId,
    kind: PageExportKind,
    path: PathBuf,
  },
  /// Integration-test hook: query the JS tab's DOM for a specific attribute value.
  ///
  /// This is intended for `browser_ui` integration tests that need to assert that JS event
  /// dispatch (e.g. `window.onscroll`) actually ran.
  ///
  /// The worker replies by sending the attribute value (when present) to `response`.
  TestQueryJsDomAttribute {
    tab_id: TabId,
    /// Element `id=` to query; when `None`, queries `document.body`.
    element_id: Option<String>,
    /// Attribute name to query.
    attr: String,
    /// One-shot response channel.
    response: Sender<Option<String>>,
  },
}

impl UiToWorker {
  pub fn select_dropdown_choose(
    tab_id: TabId,
    select_node_id: usize,
    option_node_id: usize,
  ) -> Self {
    UiToWorker::SelectDropdownChoose {
      tab_id,
      select_node_id,
      option_node_id,
    }
  }

  pub fn select_dropdown_cancel(tab_id: TabId) -> Self {
    UiToWorker::SelectDropdownCancel { tab_id }
  }

  pub fn datalist_choose(tab_id: TabId, input_node_id: usize, option_node_id: usize) -> Self {
    UiToWorker::DatalistChoose {
      tab_id,
      input_node_id,
      option_node_id,
    }
  }

  pub fn datalist_cancel(tab_id: TabId) -> Self {
    UiToWorker::DatalistCancel { tab_id }
  }

  pub fn date_time_picker_choose(tab_id: TabId, input_node_id: usize, value: String) -> Self {
    UiToWorker::DateTimePickerChoose {
      tab_id,
      input_node_id,
      value,
    }
  }

  pub fn date_time_picker_cancel(tab_id: TabId) -> Self {
    UiToWorker::DateTimePickerCancel { tab_id }
  }
}

/// Messages sent from the render worker to the UI thread.
#[derive(Debug)]
pub enum WorkerToUi {
  /// Coarse-grained stage heartbeat emitted while preparing or painting a document.
  Stage {
    tab_id: TabId,
    stage: StageHeartbeat,
  },
  /// Best-effort favicon for the currently committed page.
  ///
  /// The payload is a small premultiplied RGBA8 buffer intended for immediate upload into a UI
  /// texture (e.g. wgpu). Workers should keep this bounded (small dimensions and byte length).
  Favicon {
    tab_id: TabId,
    rgba: Vec<u8>,
    width: u32,
    height: u32,
  },
  FrameReady {
    tab_id: TabId,
    frame: RenderedFrame,
  },
  /// Update to the worker's tick scheduling hint for this tab.
  ///
  /// This has the same semantics as [`RenderedFrame::next_tick`], but can be emitted even when the
  /// worker did not produce a new frame (e.g. when JS timers are scheduled/cleared without causing a
  /// repaint).
  TickHint {
    tab_id: TabId,
    next_tick: Option<Duration>,
  },
  /// Snapshot of the currently rendered page's accessibility tree.
  ///
  /// `bounds_css` maps DOM preorder node id → viewport-local CSS rect. The vector is sorted by id
  /// to keep the payload deterministic (useful for tests/snapshots).
  PageAccessibility {
    tab_id: TabId,
    /// Monotonic per-tab generation for page accessibility-tree node ids.
    ///
    /// This is incremented whenever the mapping between renderer `dom_node_id`s and the emitted
    /// page accessibility tree may change (at minimum on navigation commits, and also on DOM
    /// structural changes within a navigation when detectable).
    ///
    /// UIs must treat this as part of the identity for all page nodes to avoid AccessKit `NodeId`
    /// reuse across navigations and page-tree rebuilds (DOM preorder ids restart at 1 for each new
    /// document, and can shift after DOM structural changes within a navigation).
    tree_generation: u32,
    tree: AccessibilityNode,
    bounds_css: Vec<(usize, Rect)>,
  },
  /// Updated page accessibility subtree (AccessKit nodes + focus) for the given tab.
  ///
  /// Feature-gated behind `browser_ui` because it depends on AccessKit types.
  #[cfg(feature = "browser_ui")]
  PageAccessKitSubtree {
    tab_id: TabId,
    subtree: PageAccessKitSubtree,
  },
  /// Lightweight update to the page's AccessKit state (focus/nodes), without replacing the full
  /// subtree.
  #[cfg(feature = "browser_ui")]
  PageAccessKitState {
    tab_id: TabId,
    update: PageAccessKitStateUpdate,
  },
  /// Request that the UI wake up after `after` to drive media/time-based updates for `tab_id`.
  ///
  /// This is primarily intended for tickless media playback scheduling (e.g. video frame
  /// presentation) so the UI can sleep in `ControlFlow::WaitUntil` instead of relying on a fixed
  /// 16ms tick.
  ///
  /// `after == Duration::MAX` means "cancel / no wakeup requested".
  RequestWakeAfter {
    tab_id: TabId,
    after: Duration,
    reason: WakeReason,
  },
  OpenSelectDropdown {
    tab_id: TabId,
    select_node_id: usize,
    control: SelectControl,
  },
  NavigationStarted {
    tab_id: TabId,
    url: String,
  },
  NavigationCommitted {
    tab_id: TabId,
    url: String,
    title: Option<String>,
    can_go_back: bool,
    can_go_forward: bool,
  },
  NavigationFailed {
    tab_id: TabId,
    url: String,
    error: String,
    can_go_back: bool,
    can_go_forward: bool,
  },
  /// Request that the UI open `url` in a new tab (e.g. for `<a target="_blank">` or
  /// Ctrl/Cmd-click/middle-click).
  ///
  /// The worker does not allocate `TabId`s; the UI owns tab identity and is responsible for
  /// creating a new tab and issuing the corresponding [`UiToWorker::CreateTab`] +
  /// [`UiToWorker::Navigate`] messages.
  RequestOpenInNewTab {
    tab_id: TabId,
    url: String,
  },
  /// Request that the UI open `url` in a new **window** (e.g. Shift+click on a link).
  ///
  /// Like [`WorkerToUi::RequestOpenInNewTab`], the worker does not allocate window/tab ids; the UI
  /// is responsible for creating the new window and navigating its initial tab.
  RequestOpenInNewWindow {
    tab_id: TabId,
    url: String,
  },
  /// Request that the UI open a new tab and perform the provided navigation request.
  ///
  /// This is used for form submissions with `target=_blank` when the submission is not a plain GET
  /// (notably POST).
  RequestOpenInNewTabRequest {
    tab_id: TabId,
    request: FormSubmission,
  },
  ScrollStateUpdated {
    tab_id: TabId,
    scroll: ScrollState,
  },
  LoadingState {
    tab_id: TabId,
    loading: bool,
  },
  /// Non-fatal warning intended for user-facing display (e.g. viewport clamping).
  Warning {
    tab_id: TabId,
    text: String,
  },
  DebugLog {
    tab_id: TabId,
    line: String,
  },
  SelectDropdownOpened {
    tab_id: TabId,
    select_node_id: usize,
    control: SelectControl,
    /// Bounding box of the `<select>` control in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  SelectDropdownClosed {
    tab_id: TabId,
  },
  /// Request that the UI open a `<datalist>` suggestion popup for an `<input list=...>` control.
  ///
  /// Workers may emit this repeatedly as the user edits the input value; UIs should treat each
  /// message as an updated suggestion list and reposition the popup accordingly.
  DatalistOpened {
    tab_id: TabId,
    input_node_id: usize,
    options: Vec<DatalistOption>,
    /// Bounding box of the `<input>` control in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  /// Notification that an open `<datalist>` popup should be dismissed.
  ///
  /// Workers emit this whenever the overlay should be dismissed (e.g. after choosing/cancelling a
  /// suggestion, or when the focused input loses focus).
  DatalistClosed {
    tab_id: TabId,
  },
  /// Request that the UI open a date/time picker popup for an `<input>` control.
  ///
  /// This is emitted in response to user activation (click, Enter/Space) on inputs with
  /// `type=date|time|datetime-local|month|week`.
  DateTimePickerOpened {
    tab_id: TabId,
    input_node_id: usize,
    kind: DateTimeInputKind,
    /// Current value string for the input, after applying HTML sanitization rules.
    value: String,
    /// Bounding box of the `<input>` control in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  /// Notification that a date/time picker popup should be dismissed.
  ///
  /// Workers emit this in response to [`UiToWorker::DateTimePickerChoose`] and
  /// [`UiToWorker::DateTimePickerCancel`] so front-ends can close the overlay deterministically.
  DateTimePickerClosed {
    tab_id: TabId,
  },
  /// Request that the UI open a color picker popup for an `<input type=color>` control.
  ///
  /// This is emitted in response to user activation (click, Enter/Space) on inputs with
  /// `type=color`.
  ColorPickerOpened {
    tab_id: TabId,
    input_node_id: usize,
    /// Current value string for the input, after applying HTML sanitization rules.
    value: String,
    /// Bounding box of the `<input>` control in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  /// Notification that a color picker popup should be dismissed.
  ///
  /// Workers emit this in response to [`UiToWorker::ColorPickerChoose`] and
  /// [`UiToWorker::ColorPickerCancel`] so front-ends can close the overlay deterministically.
  ColorPickerClosed {
    tab_id: TabId,
  },
  /// Request that the UI open a file picker popup for an `<input type=file>` control.
  ///
  /// This is emitted in response to user activation (click, Enter/Space) on file inputs.
  FilePickerOpened {
    tab_id: TabId,
    input_node_id: usize,
    multiple: bool,
    accept: Option<String>,
    /// Bounding box of the `<input>` control in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  /// Notification that a file picker popup should be dismissed.
  ///
  /// Workers emit this in response to [`UiToWorker::FilePickerChoose`] and
  /// [`UiToWorker::FilePickerCancel`] so front-ends can close the overlay deterministically.
  FilePickerClosed {
    tab_id: TabId,
  },
  /// Request that the UI show native media controls for a `<video>`/`<audio>` element.
  MediaControlsOpened {
    tab_id: TabId,
    node_id: usize,
    kind: MediaElementKind,
    /// Bounding box of the media element in **viewport CSS coordinates**.
    ///
    /// (0,0 is the top-left of the rendered viewport; does not include scroll offset.)
    anchor_css: Rect,
  },
  /// Notification that an open media controls overlay should be dismissed.
  MediaControlsClosed {
    tab_id: TabId,
  },
  /// Response to [`UiToWorker::ContextMenuRequest`].
  ContextMenu {
    tab_id: TabId,
    /// Pointer position in viewport-local CSS pixels as provided by the UI request.
    pos_css: (f32, f32),
    /// True when page JS called `preventDefault()` on the dispatched cancelable `contextmenu`
    /// event.
    ///
    /// The worker always responds to [`UiToWorker::ContextMenuRequest`] so UIs can clear any
    /// pending context menu state even when the default menu is suppressed.
    default_prevented: bool,
    /// Fully-resolved link URL under the cursor, if any.
    link_url: Option<String>,
    /// Fully-resolved image URL under the cursor, if any.
    image_url: Option<String>,
    /// True when "Copy" is meaningful for this context menu invocation (e.g. there is a selection).
    can_copy: bool,
    /// True when "Cut" is meaningful for this context menu invocation.
    can_cut: bool,
    /// True when "Paste" is meaningful for this context menu invocation (e.g. editable text control).
    can_paste: bool,
    /// True when "Select All" is meaningful for this context menu invocation.
    can_select_all: bool,
  },
  /// Hover metadata changed for a tab (cursor semantics and hovered link URL).
  ///
  /// Workers should only emit this message when the hover state actually changes (deduped) to keep
  /// the protocol lightweight on high-frequency pointer move streams.
  HoverChanged {
    tab_id: TabId,
    hovered_url: Option<String>,
    /// Tooltip text derived from the `title` attribute of the hovered DOM node (or a suitable
    /// ancestor).
    ///
    /// This is intended for browser-like UI tooltips (e.g. hovering over a link or image map `<area>`
    /// with a `title` attribute).
    tooltip: Option<String>,
    cursor: CursorKind,
  },
  /// Updated find-in-page results for a tab.
  ///
  /// - `active_match_index` is **0-based** (UIs can display `+1`).
  /// - When `match_count == 0`, `active_match_index` must be `None`.
  FindResult {
    tab_id: TabId,
    query: String,
    case_sensitive: bool,
    match_count: usize,
    active_match_index: Option<usize>,
  },
  /// Request that the UI set the OS clipboard text.
  ///
  /// This is typically emitted in response to [`UiToWorker::Copy`] or [`UiToWorker::Cut`].
  ///
  /// Security: workers should keep `text` bounded (see
  /// [`crate::ui::clipboard::MAX_CLIPBOARD_TEXT_BYTES`]). Front-ends must treat this payload as
  /// untrusted and clamp before forwarding into the OS clipboard.
  SetClipboardText {
    tab_id: TabId,
    text: String,
  },
  /// A new download was created.
  DownloadStarted {
    tab_id: TabId,
    download_id: DownloadId,
    url: String,
    file_name: String,
    path: PathBuf,
    total_bytes: Option<u64>,
  },
  /// Progress update for an in-flight download.
  DownloadProgress {
    tab_id: TabId,
    download_id: DownloadId,
    received_bytes: u64,
    total_bytes: Option<u64>,
  },
  /// A download finished, either successfully or with an error/cancellation.
  DownloadFinished {
    tab_id: TabId,
    download_id: DownloadId,
    outcome: DownloadOutcome,
  },
  /// A page export finished, either successfully or with an error/cancellation.
  PageExportFinished {
    tab_id: TabId,
    kind: PageExportKind,
    path: PathBuf,
    outcome: PageExportOutcome,
  },
}

impl WorkerToUi {
  /// Extract the tab id for this message.
  ///
  /// Today all `WorkerToUi` variants are per-tab. This helper keeps UI-side bookkeeping (e.g.
  /// watchdog timers) simple and centralised.
  pub fn tab_id(&self) -> TabId {
    match self {
      #[cfg(feature = "browser_ui")]
      WorkerToUi::PageAccessKitSubtree { tab_id, .. }
      | WorkerToUi::PageAccessKitState { tab_id, .. } => *tab_id,
      WorkerToUi::Stage { tab_id, .. }
      | WorkerToUi::RequestWakeAfter { tab_id, .. }
      | WorkerToUi::Favicon { tab_id, .. }
      | WorkerToUi::FrameReady { tab_id, .. }
      | WorkerToUi::TickHint { tab_id, .. }
      | WorkerToUi::PageAccessibility { tab_id, .. }
      | WorkerToUi::OpenSelectDropdown { tab_id, .. }
      | WorkerToUi::NavigationStarted { tab_id, .. }
      | WorkerToUi::NavigationCommitted { tab_id, .. }
      | WorkerToUi::NavigationFailed { tab_id, .. }
      | WorkerToUi::RequestOpenInNewTab { tab_id, .. }
      | WorkerToUi::RequestOpenInNewWindow { tab_id, .. }
      | WorkerToUi::RequestOpenInNewTabRequest { tab_id, .. }
      | WorkerToUi::ScrollStateUpdated { tab_id, .. }
      | WorkerToUi::LoadingState { tab_id, .. }
      | WorkerToUi::RequestWakeAfter { tab_id, .. }
      | WorkerToUi::Warning { tab_id, .. }
      | WorkerToUi::DebugLog { tab_id, .. }
      | WorkerToUi::SelectDropdownOpened { tab_id, .. }
      | WorkerToUi::SelectDropdownClosed { tab_id }
      | WorkerToUi::DatalistOpened { tab_id, .. }
      | WorkerToUi::DatalistClosed { tab_id }
      | WorkerToUi::DateTimePickerOpened { tab_id, .. }
      | WorkerToUi::DateTimePickerClosed { tab_id }
      | WorkerToUi::ColorPickerOpened { tab_id, .. }
      | WorkerToUi::ColorPickerClosed { tab_id }
      | WorkerToUi::FilePickerOpened { tab_id, .. }
      | WorkerToUi::FilePickerClosed { tab_id }
      | WorkerToUi::MediaControlsOpened { tab_id, .. }
      | WorkerToUi::MediaControlsClosed { tab_id }
      | WorkerToUi::ContextMenu { tab_id, .. }
      | WorkerToUi::HoverChanged { tab_id, .. }
      | WorkerToUi::FindResult { tab_id, .. }
      | WorkerToUi::SetClipboardText { tab_id, .. }
      | WorkerToUi::MediaControlsOpened { tab_id, .. }
      | WorkerToUi::MediaControlsClosed { tab_id }
      | WorkerToUi::DownloadStarted { tab_id, .. }
      | WorkerToUi::DownloadProgress { tab_id, .. }
      | WorkerToUi::DownloadFinished { tab_id, .. }
      | WorkerToUi::PageExportFinished { tab_id, .. } => *tab_id,
    }
  }
}

/// Envelope message used on the worker → UI channel.
///
/// `WorkerToUi` often needs to send multiple messages in quick succession (e.g. navigation
/// lifecycle + frame + scroll state). Sending each message separately creates avoidable channel send
/// and allocation overhead.
///
/// The worker therefore batches related messages into a single send where possible.
#[derive(Debug)]
pub enum WorkerToUiMsg {
  /// Single `WorkerToUi` message (no allocation).
  Single(WorkerToUi),
  /// Batch of messages, delivered in order.
  Batch(Vec<WorkerToUi>),
}

pub enum WorkerToUiMsgIter {
  Single(Option<WorkerToUi>),
  Batch(std::vec::IntoIter<WorkerToUi>),
}

impl Iterator for WorkerToUiMsgIter {
  type Item = WorkerToUi;

  fn next(&mut self) -> Option<Self::Item> {
    match self {
      WorkerToUiMsgIter::Single(msg) => msg.take(),
      WorkerToUiMsgIter::Batch(iter) => iter.next(),
    }
  }
}

impl IntoIterator for WorkerToUiMsg {
  type Item = WorkerToUi;
  type IntoIter = WorkerToUiMsgIter;

  fn into_iter(self) -> Self::IntoIter {
    match self {
      WorkerToUiMsg::Single(msg) => WorkerToUiMsgIter::Single(Some(msg)),
      WorkerToUiMsg::Batch(msgs) => WorkerToUiMsgIter::Batch(msgs.into_iter()),
    }
  }
}

/// Receiver wrapper that flattens [`WorkerToUiMsg`] envelopes into individual [`WorkerToUi`]
/// messages.
///
/// This is primarily intended for test code and headless callers that prefer the ergonomics of
/// receiving one logical message at a time, while still benefiting from batching on the underlying
/// channel.
#[derive(Debug)]
pub struct WorkerToUiInbox {
  rx: std::sync::mpsc::Receiver<WorkerToUiMsg>,
  pending: std::cell::RefCell<std::collections::VecDeque<WorkerToUi>>,
}

impl WorkerToUiInbox {
  pub fn new(rx: std::sync::mpsc::Receiver<WorkerToUiMsg>) -> Self {
    Self {
      rx,
      pending: std::cell::RefCell::new(std::collections::VecDeque::new()),
    }
  }

  pub fn recv(&self) -> Result<WorkerToUi, std::sync::mpsc::RecvError> {
    loop {
      if let Some(msg) = self.pending.borrow_mut().pop_front() {
        return Ok(msg);
      }

      let envelope = self.rx.recv()?;
      if let Some(msg) = self.push_envelope(envelope) {
        return Ok(msg);
      }
    }
  }

  pub fn try_recv(&self) -> Result<WorkerToUi, std::sync::mpsc::TryRecvError> {
    loop {
      if let Some(msg) = self.pending.borrow_mut().pop_front() {
        return Ok(msg);
      }

      let envelope = self.rx.try_recv()?;
      if let Some(msg) = self.push_envelope(envelope) {
        return Ok(msg);
      }
    }
  }

  pub fn recv_timeout(
    &self,
    timeout: std::time::Duration,
  ) -> Result<WorkerToUi, std::sync::mpsc::RecvTimeoutError> {
    use std::time::Instant;

    let start = Instant::now();
    loop {
      if let Some(msg) = self.pending.borrow_mut().pop_front() {
        return Ok(msg);
      }

      let remaining = timeout.saturating_sub(start.elapsed());
      if remaining.is_zero() {
        return Err(std::sync::mpsc::RecvTimeoutError::Timeout);
      }

      let envelope = self.rx.recv_timeout(remaining)?;
      if let Some(msg) = self.push_envelope(envelope) {
        return Ok(msg);
      }
    }
  }

  /// Drain any queued messages (including buffered items from an already-received batch).
  pub fn try_iter(&self) -> impl Iterator<Item = WorkerToUi> + '_ {
    std::iter::from_fn(|| self.try_recv().ok())
  }

  pub fn into_inner(self) -> std::sync::mpsc::Receiver<WorkerToUiMsg> {
    self.rx
  }

  fn push_envelope(&self, envelope: WorkerToUiMsg) -> Option<WorkerToUi> {
    match envelope {
      WorkerToUiMsg::Single(msg) => Some(msg),
      WorkerToUiMsg::Batch(msgs) => {
        let mut iter = msgs.into_iter();
        let first = iter.next()?;
        let mut pending = self.pending.borrow_mut();
        pending.extend(iter);
        Some(first)
      }
    }
  }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DownloadOutcome {
  Completed,
  Cancelled,
  Failed { error: String },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PageExportOutcome {
  Completed,
  Cancelled,
  Failed { error: String },
}

// -----------------------------------------------------------------------------
// Compile-time trait assertions
// -----------------------------------------------------------------------------

// The windowed browser UI uses std::sync::mpsc for worker↔UI messaging. If we ever ship AccessKit
// data across that boundary (e.g. for page accessibility), the payload types must remain `Send`.
#[cfg(feature = "browser_ui")]
#[allow(dead_code)]
fn _assert_accesskit_types_are_send() {
  fn assert_send<T: Send>() {}
  assert_send::<accesskit::Node>();
  assert_send::<accesskit::TreeUpdate>();
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::collections::HashSet;
  use std::time::Duration;

  #[test]
  fn tab_id_new_generates_unique_ids() {
    let _lock = TAB_ID_TEST_LOCK.lock().unwrap();
    let mut ids = HashSet::new();
    for _ in 0..1024 {
      assert!(ids.insert(TabId::new()));
    }
  }

  #[test]
  fn tab_id_new_does_not_panic_on_counter_wraparound() {
    let _lock = TAB_ID_TEST_LOCK.lock().unwrap();

    let prev = NEXT_TAB_ID.swap(u64::MAX - 1, Ordering::Relaxed);

    // This will allocate ids at the end of the range and then wrap. The allocator must not panic,
    // and must never return 0.
    let a = TabId::new().0;
    let b = TabId::new().0;
    let c = TabId::new().0;

    assert_eq!(a, u64::MAX - 1);
    assert_eq!(b, u64::MAX);
    assert_ne!(c, 0);

    NEXT_TAB_ID.store(prev, Ordering::Relaxed);
  }

  #[test]
  fn navigation_id_new_generates_unique_ids() {
    let _lock = NAVIGATION_ID_TEST_LOCK.lock().unwrap();
    let mut ids = HashSet::new();
    for _ in 0..1024 {
      assert!(ids.insert(NavigationId::new()));
    }
  }

  #[test]
  fn navigation_id_new_does_not_panic_on_counter_wraparound() {
    let _lock = NAVIGATION_ID_TEST_LOCK.lock().unwrap();

    let prev = NEXT_NAVIGATION_ID.swap(u64::MAX - 1, Ordering::Relaxed);

    // This will allocate ids at the end of the range and then wrap. The allocator must not panic,
    // and must never return 0.
    let a = NavigationId::new().0;
    let b = NavigationId::new().0;
    let c = NavigationId::new().0;

    assert_eq!(a, u64::MAX - 1);
    assert_eq!(b, u64::MAX);
    assert_ne!(c, 0);

    NEXT_NAVIGATION_ID.store(prev, Ordering::Relaxed);
  }

  #[test]
  fn rendered_frame_is_send() {
    fn assert_send<T: Send>() {}
    assert_send::<RenderedFrame>();
  }

  #[cfg(feature = "browser_ui")]
  #[test]
  fn accesskit_types_are_send() {
    // These types may be used in worker→UI payloads when the windowed browser UI is enabled.
    // They must remain `Send` so `WorkerToUi` messages can cross the std::sync::mpsc boundary.
    fn assert_send<T: Send>() {}
    assert_send::<accesskit::Node>();
    assert_send::<accesskit::TreeUpdate>();
  }

  #[test]
  fn ui_to_worker_new_history_actions_are_debug_constructible() {
    let tab_id = TabId(1);

    // Ensure the new variants can be constructed and formatted. This is
    // intentionally lightweight: we just want compilation coverage for the
    // message protocol.
    let msgs = [
      UiToWorker::GoBack { tab_id },
      UiToWorker::GoForward { tab_id },
      UiToWorker::Reload { tab_id },
      UiToWorker::StopLoading { tab_id },
    ];

    for msg in msgs {
      let formatted = format!("{msg:?}");
      assert!(!formatted.is_empty());
    }
  }

  #[test]
  fn ui_to_worker_a11y_text_actions_are_debug_constructible() {
    let tab_id = TabId(1);

    let msgs = [
      UiToWorker::A11ySetTextValue {
        tab_id,
        node_id: 42,
        value: "hello".to_string(),
      },
      UiToWorker::A11ySetTextSelectionRange {
        tab_id,
        node_id: 42,
        start: 0,
        end: 5,
      },
    ];

    for msg in msgs {
      let formatted = format!("{msg:?}");
      assert!(!formatted.is_empty());
    }
  }

  #[test]
  fn find_in_page_messages_are_debug_constructible() {
    let tab_id = TabId(1);
    let query = "test".to_string();

    // Ensure the new variants can be constructed and formatted. This is intentionally lightweight:
    // we just want compilation coverage for the message protocol.
    let ui_msgs = [
      UiToWorker::FindQuery {
        tab_id,
        query: query.clone(),
        case_sensitive: false,
      },
      UiToWorker::FindNext { tab_id },
      UiToWorker::FindPrev { tab_id },
      UiToWorker::FindStop { tab_id },
    ];

    for msg in ui_msgs {
      let formatted = format!("{msg:?}");
      assert!(!formatted.is_empty());
    }

    let worker_msg = WorkerToUi::FindResult {
      tab_id,
      query,
      case_sensitive: false,
      match_count: 3,
      active_match_index: Some(1),
    };
    let formatted = format!("{worker_msg:?}");
    assert!(!formatted.is_empty());
  }

  #[test]
  fn request_wake_after_message_is_debug_constructible() {
    let tab_id = TabId(1);
    let msg = WorkerToUi::RequestWakeAfter {
      tab_id,
      after: Duration::from_millis(10),
      reason: WakeReason::Media,
    };
    let formatted = format!("{msg:?}");
    assert!(!formatted.is_empty());
  }

  #[test]
  fn worker_to_ui_msg_batch_iteration_preserves_order() {
    let tab_id = TabId(1);
    let envelope = WorkerToUiMsg::Batch(vec![
      WorkerToUi::LoadingState {
        tab_id,
        loading: true,
      },
      WorkerToUi::DebugLog {
        tab_id,
        line: "middle".to_string(),
      },
      WorkerToUi::LoadingState {
        tab_id,
        loading: false,
      },
    ]);

    let msgs: Vec<WorkerToUi> = envelope.into_iter().collect();
    assert_eq!(msgs.len(), 3);
    assert!(matches!(
      msgs[0],
      WorkerToUi::LoadingState {
        tab_id: t,
        loading: true
      } if t == tab_id
    ));
    assert!(matches!(
      msgs[1],
      WorkerToUi::DebugLog { tab_id: t, .. } if t == tab_id
    ));
    assert!(matches!(
      msgs[2],
      WorkerToUi::LoadingState {
        tab_id: t,
        loading: false
      } if t == tab_id
    ));
  }

  #[test]
  fn worker_to_ui_inbox_flattens_batch_in_order() {
    let tab_id = TabId(1);
    let (tx, rx) = std::sync::mpsc::channel::<WorkerToUiMsg>();
    tx.send(WorkerToUiMsg::Batch(vec![
      WorkerToUi::LoadingState {
        tab_id,
        loading: true,
      },
      WorkerToUi::DebugLog {
        tab_id,
        line: "two".to_string(),
      },
      WorkerToUi::LoadingState {
        tab_id,
        loading: false,
      },
    ]))
    .unwrap();
    drop(tx);

    let inbox = WorkerToUiInbox::new(rx);
    let a = inbox.recv_timeout(Duration::from_secs(1)).unwrap();
    let b = inbox.recv_timeout(Duration::from_secs(1)).unwrap();
    let c = inbox.recv_timeout(Duration::from_secs(1)).unwrap();

    assert!(matches!(
      a,
      WorkerToUi::LoadingState {
        tab_id: t,
        loading: true
      } if t == tab_id
    ));
    assert!(matches!(b, WorkerToUi::DebugLog { tab_id: t, .. } if t == tab_id));
    assert!(matches!(
      c,
      WorkerToUi::LoadingState {
        tab_id: t,
        loading: false
      } if t == tab_id
    ));

    assert!(matches!(
      inbox.recv_timeout(Duration::from_millis(1)),
      Err(std::sync::mpsc::RecvTimeoutError::Disconnected)
    ));
  }
}
