// @generated by `bash scripts/cargo_agent.sh xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - src/webidl/generated/mod.rs (committed snapshot; produced by `bash scripts/cargo_agent.sh xtask webidl`)

pub mod window {
  use vm_js::{GcObject, Heap, Realm, Scope, Value, Vm, VmError, VmHost, VmHostHooks};
  use webidl_vm_js::bindings_runtime::{
    to_int32_f64, BindingValue, BindingsRuntime, DataPropertyAttributes,
  };
  use webidl_vm_js::{host_from_hooks, IterableKind};

  #[allow(dead_code)]
  fn js_to_dict_foo_options(
    rt: &mut BindingsRuntime<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    value: Value,
  ) -> Result<Value, VmError> {
    let _ = (host, hooks);
    if matches!(value, Value::Undefined | Value::Null) {
      let obj = rt.alloc_object()?;
      return Ok(Value::Object(obj));
    }
    let Value::Object(input) = value else {
      return Err(rt.throw_type_error("expected object for dictionary FooOptions"));
    };
    rt.scope.push_root(Value::Object(input))?;
    let out_obj = rt.alloc_object()?;
    {
      let key = rt.property_key("capture")?;
      let v = rt.vm.get(&mut rt.scope, input, key)?;
      if !matches!(v, Value::Undefined) {
        let converted = Value::Bool(rt.scope.heap().to_boolean(v)?);
        rt.define_data_property_str(
          out_obj,
          "capture",
          converted,
          DataPropertyAttributes::new(true, true, true),
        )?;
      }
    }
    Ok(Value::Object(out_obj))
  }

  #[allow(dead_code)]
  fn bar_entries(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Bar",
      IterableKind::Entries,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn bar_for_each(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let callback = args.get(0).copied().unwrap_or(Value::Undefined);
    let callback = rt.scope.push_root(callback)?;
    let this_arg = args.get(1).copied().unwrap_or(Value::Undefined);
    let this_arg = rt.scope.push_root(this_arg)?;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Bar",
      IterableKind::Entries,
    )?;
    for entry in snapshot {
      let BindingValue::Sequence(mut pair) = entry else {
        return Err(rt.throw_type_error("iterable forEach: expected [key, value] pair"));
      };
      if pair.len() != 2 {
        return Err(rt.throw_type_error("iterable forEach: expected [key, value] pair"));
      }
      let mut iter = pair.into_iter();
      let key = iter
        .next()
        .ok_or_else(|| rt.throw_type_error("iterable forEach: expected [key, value] pair"))?;
      let value = iter
        .next()
        .ok_or_else(|| rt.throw_type_error("iterable forEach: expected [key, value] pair"))?;
      let key_js = rt.binding_value_to_js(key)?;
      let key_js = rt.scope.push_root(key_js)?;
      let value_js = rt.binding_value_to_js(value)?;
      let value_js = rt.scope.push_root(value_js)?;
      let _ = rt.vm.call_with_host_and_hooks(
        _host,
        &mut rt.scope,
        hooks,
        callback,
        this_arg,
        &[value_js, key_js, this],
      )?;
    }
    Ok(Value::Undefined)
  }

  #[allow(dead_code)]
  fn bar_keys(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Bar",
      IterableKind::Keys,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn bar_values(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Bar",
      IterableKind::Values,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn bar_call_without_new(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    _hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    _this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    Err(rt.throw_type_error("Illegal constructor"))
  }

  #[allow(dead_code)]
  fn bar_construct(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    callee: GcObject,
    _args: &[Value],
    new_target: Value,
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let slots = rt.scope.heap().get_function_native_slots(callee)?;
    let proto_slot = slots.get(0).copied().unwrap_or(Value::Undefined);
    let Value::Object(default_proto) = proto_slot else {
      return Err(VmError::InvariantViolation(
        "Bar constructor missing prototype slot",
      ));
    };
    // Derive the wrapper object's prototype from `new.target` (subclassing semantics).
    //
    // This follows the spirit of `GetPrototypeFromConstructor` / `OrdinaryCreateFromConstructor`:
    // - default to the interface prototype cached in native slots,
    // - if `new_target` is an object and `new_target.prototype` is an object, use that instead.
    rt.scope.push_root(Value::Object(default_proto))?;
    rt.scope.push_root(new_target)?;
    let mut wrapper_proto = default_proto;
    if let Value::Object(new_target_obj) = new_target {
      rt.scope.push_root(Value::Object(new_target_obj))?;
      let proto_key = rt.property_key("prototype")?;
      let candidate = rt.scope.ordinary_get_with_host_and_hooks(
        &mut *rt.vm,
        host,
        hooks,
        new_target_obj,
        proto_key,
        Value::Object(new_target_obj),
      )?;
      if let Value::Object(candidate_obj) = candidate {
        rt.scope.push_root(Value::Object(candidate_obj))?;
        wrapper_proto = candidate_obj;
      }
    }
    let obj = rt.scope.alloc_object_with_prototype(Some(wrapper_proto))?;
    rt.scope.push_root(Value::Object(obj))?;

    {
      let converted_args: Vec<Value> = Vec::new();
      let bindings_host = host_from_hooks(hooks)?;
      let _ = bindings_host.call_operation(
        &mut *rt.vm,
        &mut rt.scope,
        Some(Value::Object(obj)),
        "Bar",
        "constructor",
        0,
        &converted_args,
      )?;
      Ok(Value::Object(obj))
    }
  }

  #[allow(dead_code)]
  fn foo_baz(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let args = if args.len() > 1 { &args[..1] } else { args };
    if args.len() == 1 && (matches!(args[0], Value::String(_))) {
      {
        let mut converted_args: Vec<Value> = Vec::new();
        let v0 = if args.len() > 0 {
          args[0]
        } else {
          Value::Undefined
        };
        let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, v0)?);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let bindings_host = host_from_hooks(hooks)?;
        bindings_host.call_operation(
          &mut *rt.vm,
          &mut rt.scope,
          receiver,
          "Foo",
          "baz",
          0,
          &converted_args,
        )
      }
    } else if args.len() == 1 && (matches!(args[0], Value::Number(_))) {
      {
        let mut converted_args: Vec<Value> = Vec::new();
        let v0 = if args.len() > 0 {
          args[0]
        } else {
          Value::Undefined
        };
        let converted =
          Value::Number(to_int32_f64(rt.scope.to_number(&mut *rt.vm, host, hooks, v0)?) as f64);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let bindings_host = host_from_hooks(hooks)?;
        bindings_host.call_operation(
          &mut *rt.vm,
          &mut rt.scope,
          receiver,
          "Foo",
          "baz",
          1,
          &converted_args,
        )
      }
    } else {
      Err(rt.throw_type_error("no matching overload for Foo.baz"))
    }
  }

  #[allow(dead_code)]
  fn foo_do_thing(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let args = if args.len() > 2 { &args[..2] } else { args };
    if args.len() >= 1 && args.len() <= 2 && (matches!(args[0], Value::String(_))) {
      {
        let mut converted_args: Vec<Value> = Vec::new();
        let v0 = if args.len() > 0 {
          args[0]
        } else {
          Value::Undefined
        };
        let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, v0)?);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let v1 = if args.len() > 1 {
          args[1]
        } else {
          Value::Undefined
        };
        let converted = if matches!(v1, Value::Undefined) {
          {
            let obj = rt.alloc_object()?;
            Value::Object(obj)
          }
        } else {
          {
            let v = v1;
            if false {
              Value::Undefined
            } else if matches!(v, Value::Null | Value::Undefined) {
              js_to_dict_foo_options(rt, host, hooks, v)?
            } else if let Value::Object(obj) = v {
              js_to_dict_foo_options(rt, host, hooks, v)?
            } else if matches!(v, Value::Bool(_)) {
              Value::Bool(rt.scope.heap().to_boolean(v)?)
            } else {
              Value::Bool(rt.scope.heap().to_boolean(v)?)
            }
          }
        };
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let bindings_host = host_from_hooks(hooks)?;
        bindings_host.call_operation(
          &mut *rt.vm,
          &mut rt.scope,
          receiver,
          "Foo",
          "doThing",
          0,
          &converted_args,
        )
      }
    } else if args.len() == 2 && (matches!(args[0], Value::String(_))) {
      {
        let mut converted_args: Vec<Value> = Vec::new();
        let v0 = if args.len() > 0 {
          args[0]
        } else {
          Value::Undefined
        };
        let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, v0)?);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let v1 = if args.len() > 1 {
          args[1]
        } else {
          Value::Undefined
        };
        let converted = {
          let v = v1;
          let Value::Object(_obj) = v else {
            return Err(rt.throw_type_error("expected object for sequence"));
          };
          rt.scope.push_root(v)?;
          let mut iterator_record =
            vm_js::iterator::get_iterator(&mut *rt.vm, host, hooks, &mut rt.scope, v)?;
          rt.scope.push_root(iterator_record.iterator)?;
          rt.scope.push_root(iterator_record.next_method)?;

          let out = rt.alloc_array(0)?;
          rt.scope.push_root(Value::Object(out))?;

          let mut idx: usize = 0;
          while let Some(next) = vm_js::iterator::iterator_step_value(
            &mut *rt.vm,
            host,
            hooks,
            &mut rt.scope,
            &mut iterator_record,
          )? {
            rt.scope.push_root(next)?;
            let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, next)?);
            let converted = rt.scope.push_root(converted)?;
            let key_s = rt.scope.alloc_string(&idx.to_string())?;
            rt.scope.push_root(Value::String(key_s))?;
            let key = vm_js::PropertyKey::from_string(key_s);
            rt.scope
              .create_data_property_or_throw(out, key, converted)?;
            idx += 1;
          }
          Value::Object(out)
        };
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let bindings_host = host_from_hooks(hooks)?;
        bindings_host.call_operation(
          &mut *rt.vm,
          &mut rt.scope,
          receiver,
          "Foo",
          "doThing",
          1,
          &converted_args,
        )
      }
    } else if args.len() == 2 && (matches!(args[0], Value::String(_))) {
      {
        let mut converted_args: Vec<Value> = Vec::new();
        let v0 = if args.len() > 0 {
          args[0]
        } else {
          Value::Undefined
        };
        let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, v0)?);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let v1 = if args.len() > 1 {
          args[1]
        } else {
          Value::Undefined
        };
        let converted = Value::String(rt.scope.to_string(&mut *rt.vm, host, hooks, v1)?);
        let converted = rt.scope.push_root(converted)?;
        converted_args.push(converted);
        let bindings_host = host_from_hooks(hooks)?;
        bindings_host.call_operation(
          &mut *rt.vm,
          &mut rt.scope,
          receiver,
          "Foo",
          "doThing",
          2,
          &converted_args,
        )
      }
    } else {
      Err(rt.throw_type_error("no matching overload for Foo.doThing"))
    }
  }

  #[allow(dead_code)]
  fn foo_entries(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Foo",
      IterableKind::Entries,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn foo_for_each(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let callback = args.get(0).copied().unwrap_or(Value::Undefined);
    let callback = rt.scope.push_root(callback)?;
    let this_arg = args.get(1).copied().unwrap_or(Value::Undefined);
    let this_arg = rt.scope.push_root(this_arg)?;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Foo",
      IterableKind::Entries,
    )?;
    for entry in snapshot {
      let BindingValue::Sequence(mut pair) = entry else {
        return Err(rt.throw_type_error("iterable forEach: expected [key, value] pair"));
      };
      if pair.len() != 2 {
        return Err(rt.throw_type_error("iterable forEach: expected [key, value] pair"));
      }
      let mut iter = pair.into_iter();
      let key = iter
        .next()
        .ok_or_else(|| rt.throw_type_error("iterable forEach: expected [key, value] pair"))?;
      let value = iter
        .next()
        .ok_or_else(|| rt.throw_type_error("iterable forEach: expected [key, value] pair"))?;
      let key_js = rt.binding_value_to_js(key)?;
      let key_js = rt.scope.push_root(key_js)?;
      let value_js = rt.binding_value_to_js(value)?;
      let value_js = rt.scope.push_root(value_js)?;
      let _ = rt.vm.call_with_host_and_hooks(
        _host,
        &mut rt.scope,
        hooks,
        callback,
        this_arg,
        &[value_js, key_js, this],
      )?;
    }
    Ok(Value::Undefined)
  }

  #[allow(dead_code)]
  fn foo_keys(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Foo",
      IterableKind::Keys,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn foo_qux(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    {
      let mut converted_args: Vec<Value> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        Value::Undefined
      };
      let converted = if matches!(v0, Value::Undefined) {
        Value::Undefined
      } else {
        js_to_dict_foo_options(rt, host, hooks, v0)?
      };
      let converted = rt.scope.push_root(converted)?;
      converted_args.push(converted);
      let bindings_host = host_from_hooks(hooks)?;
      bindings_host.call_operation(
        &mut *rt.vm,
        &mut rt.scope,
        receiver,
        "Foo",
        "qux",
        0,
        &converted_args,
      )
    }
  }

  #[allow(dead_code)]
  fn foo_takes_frozen_array(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    {
      let mut converted_args: Vec<Value> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        Value::Undefined
      };
      let converted = {
        let v = v0;
        let Value::Object(_obj) = v else {
          return Err(rt.throw_type_error("expected object for FrozenArray"));
        };
        rt.scope.push_root(v)?;
        let mut iterator_record =
          vm_js::iterator::get_iterator(&mut *rt.vm, host, hooks, &mut rt.scope, v)?;
        rt.scope.push_root(iterator_record.iterator)?;
        rt.scope.push_root(iterator_record.next_method)?;

        let out = rt.alloc_array(0)?;
        rt.scope.push_root(Value::Object(out))?;

        let mut idx: usize = 0;
        while let Some(next) = vm_js::iterator::iterator_step_value(
          &mut *rt.vm,
          host,
          hooks,
          &mut rt.scope,
          &mut iterator_record,
        )? {
          rt.scope.push_root(next)?;
          let converted =
            Value::Number(to_int32_f64(rt.scope.to_number(&mut *rt.vm, host, hooks, next)?) as f64);
          let converted = rt.scope.push_root(converted)?;
          let key_s = rt.scope.alloc_string(&idx.to_string())?;
          rt.scope.push_root(Value::String(key_s))?;
          let key = vm_js::PropertyKey::from_string(key_s);
          rt.scope
            .create_data_property_or_throw(out, key, converted)?;
          idx += 1;
        }
        Value::Object(out)
      };
      let converted = rt.scope.push_root(converted)?;
      converted_args.push(converted);
      let bindings_host = host_from_hooks(hooks)?;
      bindings_host.call_operation(
        &mut *rt.vm,
        &mut rt.scope,
        receiver,
        "Foo",
        "takesFrozenArray",
        0,
        &converted_args,
      )
    }
  }

  #[allow(dead_code)]
  fn foo_takes_sequence(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    {
      let mut converted_args: Vec<Value> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        Value::Undefined
      };
      let converted = {
        let v = v0;
        let Value::Object(_obj) = v else {
          return Err(rt.throw_type_error("expected object for sequence"));
        };
        rt.scope.push_root(v)?;
        let mut iterator_record =
          vm_js::iterator::get_iterator(&mut *rt.vm, host, hooks, &mut rt.scope, v)?;
        rt.scope.push_root(iterator_record.iterator)?;
        rt.scope.push_root(iterator_record.next_method)?;

        let out = rt.alloc_array(0)?;
        rt.scope.push_root(Value::Object(out))?;

        let mut idx: usize = 0;
        while let Some(next) = vm_js::iterator::iterator_step_value(
          &mut *rt.vm,
          host,
          hooks,
          &mut rt.scope,
          &mut iterator_record,
        )? {
          rt.scope.push_root(next)?;
          let converted =
            Value::Number(to_int32_f64(rt.scope.to_number(&mut *rt.vm, host, hooks, next)?) as f64);
          let converted = rt.scope.push_root(converted)?;
          let key_s = rt.scope.alloc_string(&idx.to_string())?;
          rt.scope.push_root(Value::String(key_s))?;
          let key = vm_js::PropertyKey::from_string(key_s);
          rt.scope
            .create_data_property_or_throw(out, key, converted)?;
          idx += 1;
        }
        Value::Object(out)
      };
      let converted = rt.scope.push_root(converted)?;
      converted_args.push(converted);
      let bindings_host = host_from_hooks(hooks)?;
      bindings_host.call_operation(
        &mut *rt.vm,
        &mut rt.scope,
        receiver,
        "Foo",
        "takesSequence",
        0,
        &converted_args,
      )
    }
  }

  #[allow(dead_code)]
  fn foo_values(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    rt.scope.push_root(this)?;
    let receiver = Some(this);
    let _ = _args;
    let bindings_host = host_from_hooks(hooks)?;
    let snapshot = bindings_host.iterable_snapshot(
      &mut *rt.vm,
      &mut rt.scope,
      receiver,
      "Foo",
      IterableKind::Values,
    )?;
    let arr = rt.alloc_array(snapshot.len())?;
    for (idx, item) in snapshot.into_iter().enumerate() {
      let value = rt.binding_value_to_js(item)?;
      let value = rt.scope.push_root(value)?;
      let key_s = rt.scope.alloc_string(&idx.to_string())?;
      rt.scope.push_root(Value::String(key_s))?;
      let key = vm_js::PropertyKey::from_string(key_s);
      rt.scope.create_data_property_or_throw(arr, key, value)?;
    }
    let intr = rt
      .vm
      .intrinsics()
      .ok_or(VmError::Unimplemented("intrinsics not initialized"))?;
    let iterator_key = vm_js::PropertyKey::from_symbol(intr.well_known_symbols().iterator);
    let Some(method) = rt
      .vm
      .get_method_from_object(&mut rt.scope, arr, iterator_key)?
    else {
      return Err(rt.throw_type_error("iterable snapshot array is not iterable"));
    };
    rt.vm
      .call_with_host_and_hooks(_host, &mut rt.scope, hooks, method, Value::Object(arr), &[])
  }

  #[allow(dead_code)]
  fn foo_call_without_new(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    _hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    _this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    Err(rt.throw_type_error("Illegal constructor"))
  }

  #[allow(dead_code)]
  fn foo_construct(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    callee: GcObject,
    _args: &[Value],
    new_target: Value,
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    let slots = rt.scope.heap().get_function_native_slots(callee)?;
    let proto_slot = slots.get(0).copied().unwrap_or(Value::Undefined);
    let Value::Object(default_proto) = proto_slot else {
      return Err(VmError::InvariantViolation(
        "Foo constructor missing prototype slot",
      ));
    };
    // Derive the wrapper object's prototype from `new.target` (subclassing semantics).
    //
    // This follows the spirit of `GetPrototypeFromConstructor` / `OrdinaryCreateFromConstructor`:
    // - default to the interface prototype cached in native slots,
    // - if `new_target` is an object and `new_target.prototype` is an object, use that instead.
    rt.scope.push_root(Value::Object(default_proto))?;
    rt.scope.push_root(new_target)?;
    let mut wrapper_proto = default_proto;
    if let Value::Object(new_target_obj) = new_target {
      rt.scope.push_root(Value::Object(new_target_obj))?;
      let proto_key = rt.property_key("prototype")?;
      let candidate = rt.scope.ordinary_get_with_host_and_hooks(
        &mut *rt.vm,
        host,
        hooks,
        new_target_obj,
        proto_key,
        Value::Object(new_target_obj),
      )?;
      if let Value::Object(candidate_obj) = candidate {
        rt.scope.push_root(Value::Object(candidate_obj))?;
        wrapper_proto = candidate_obj;
      }
    }
    let obj = rt.scope.alloc_object_with_prototype(Some(wrapper_proto))?;
    rt.scope.push_root(Value::Object(obj))?;

    {
      let converted_args: Vec<Value> = Vec::new();
      let bindings_host = host_from_hooks(hooks)?;
      let _ = bindings_host.call_operation(
        &mut *rt.vm,
        &mut rt.scope,
        Some(Value::Object(obj)),
        "Foo",
        "constructor",
        0,
        &converted_args,
      )?;
      Ok(Value::Object(obj))
    }
  }

  pub fn install_window_bindings_vm_js(
    vm: &mut Vm,
    heap: &mut Heap,
    realm: &Realm,
  ) -> Result<(), VmError> {
    let mut rt = BindingsRuntime::new(vm, heap);
    let global = realm.global_object();
    rt.scope.push_root(Value::Object(global))?;

    let global_var_attrs = DataPropertyAttributes::new(true, false, true);
    let ctor_link_attrs = DataPropertyAttributes::new(false, false, false);

    let proto_bar = rt.alloc_object()?;
    let proto_foo = rt.alloc_object()?;

    let func = rt.alloc_native_function(bar_entries, None, "entries", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "entries",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_for_each, None, "forEach", 1)?;
    rt.define_data_property_str(
      proto_bar,
      "forEach",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_keys, None, "keys", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "keys",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_values, None, "values", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "values",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let iterator_key = vm_js::PropertyKey::from_symbol(realm.well_known_symbols().iterator);
    rt.define_data_property(
      proto_bar,
      iterator_key,
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let slots = [Value::Object(proto_bar)];
    let ctor_bar = rt.alloc_native_function_with_slots(
      bar_call_without_new,
      Some(bar_construct),
      "Bar",
      0,
      &slots,
    )?;
    rt.define_data_property_str(global, "Bar", Value::Object(ctor_bar), global_var_attrs)?;
    rt.define_data_property_str(
      ctor_bar,
      "prototype",
      Value::Object(proto_bar),
      ctor_link_attrs,
    )?;
    rt.define_data_property_str(
      proto_bar,
      "constructor",
      Value::Object(ctor_bar),
      ctor_link_attrs,
    )?;
    let func = rt.alloc_native_function(foo_baz, None, "baz", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "baz",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_do_thing, None, "doThing", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "doThing",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_entries, None, "entries", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "entries",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let iterator_key = vm_js::PropertyKey::from_symbol(realm.well_known_symbols().iterator);
    rt.define_data_property(
      proto_foo,
      iterator_key,
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_for_each, None, "forEach", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "forEach",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_keys, None, "keys", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "keys",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_qux, None, "qux", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "qux",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_takes_frozen_array, None, "takesFrozenArray", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "takesFrozenArray",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_takes_sequence, None, "takesSequence", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "takesSequence",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_values, None, "values", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "values",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let slots = [Value::Object(proto_foo)];
    let ctor_foo = rt.alloc_native_function_with_slots(
      foo_call_without_new,
      Some(foo_construct),
      "Foo",
      0,
      &slots,
    )?;
    rt.define_data_property_str(global, "Foo", Value::Object(ctor_foo), global_var_attrs)?;
    rt.define_data_property_str(
      ctor_foo,
      "prototype",
      Value::Object(proto_foo),
      ctor_link_attrs,
    )?;
    rt.define_data_property_str(
      proto_foo,
      "constructor",
      Value::Object(ctor_foo),
      ctor_link_attrs,
    )?;
    Ok(())
  }
}

pub use window::install_window_bindings_vm_js;
