// @generated by `bash scripts/cargo_agent.sh xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - src/webidl/generated/mod.rs (committed snapshot; produced by `bash scripts/cargo_agent.sh xtask webidl`)

use super::host::{binding_value_to_js, BindingValue, WebHostBindings};

pub mod window {
  use std::collections::BTreeMap;

  use super::{binding_value_to_js, BindingValue, WebHostBindings};

  use crate::js::webidl::DataPropertyAttributes;

  #[allow(dead_code)]
  fn foo_do_it<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(rt, Some(this), "Foo", "doIt", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn foo_get_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "Foo", "href")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn foo_set_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let v0 = if args.len() > 0 {
      args[0]
    } else {
      rt.js_undefined()
    };
    let converted = {
      let s = rt.to_string(host, v0)?;
      BindingValue::String(rt.js_string_to_rust_string(s)?)
    };
    host.set_attribute(rt, Some(this), "Foo", "href", converted)?;
    Ok(rt.js_undefined())
  }

  #[allow(dead_code)]
  fn foo_get_attribute_size<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "Foo", "size")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn foo_get_static_attribute_ok<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let result = host.get_attribute(rt, None, "Foo", "ok")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn illegal_constructor<Host, R>(
    rt: &mut R,
    _host: &mut Host,
    _this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    Err(rt.throw_type_error("Illegal constructor"))
  }

  pub fn install_window_bindings<Host, R>(rt: &mut R, host: &mut Host) -> Result<(), R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let global = rt.global_object()?;
    let proto_foo = rt.create_object()?;
    let func = rt.create_function("doIt", 0, foo_do_it::<Host, R>)?;
    rt.define_method(proto_foo, "doIt", func)?;
    let get = rt.create_function("get href", 0, foo_get_attribute_href::<Host, R>)?;
    let set = rt.create_function("set href", 1, foo_set_attribute_href::<Host, R>)?;
    rt.define_attribute_accessor(proto_foo, "href", get, set)?;
    let get = rt.create_function("get size", 0, foo_get_attribute_size::<Host, R>)?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(proto_foo, "size", get, set)?;
    let ctor_foo = rt.create_constructor(
      "Foo",
      0,
      illegal_constructor::<Host, R>,
      illegal_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "Foo", ctor_foo, proto_foo)?;
    let get = rt.create_function("get ok", 0, foo_get_static_attribute_ok::<Host, R>)?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(ctor_foo, "ok", get, set)?;
    rt.define_constant(ctor_foo, "ANSWER", rt.js_number(42.0))?;
    rt.define_constant(proto_foo, "ANSWER", rt.js_number(42.0))?;
    let _ = host;
    Ok(())
  }
}

pub use window::install_window_bindings;
