// @generated by `cargo xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - tools/webidl/prelude.idl
// - tools/webidl/overrides/*.idl
// - specs/whatwg-dom/dom.bs
// - specs/whatwg-html/source
// - specs/whatwg-url/url.bs
// - specs/whatwg-fetch/fetch.bs

use std::collections::BTreeMap;

use super::host::{BindingValue, WebHostBindings};

fn binding_value_to_js<Host, R>(
  rt: &mut R,
  value: BindingValue<R::JsValue>,
) -> Result<R::JsValue, R::Error>
where
  R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
{
  match value {
    BindingValue::Undefined => Ok(rt.js_undefined()),
    BindingValue::Null => Ok(rt.js_null()),
    BindingValue::Bool(b) => Ok(rt.js_bool(b)),
    BindingValue::Number(n) => Ok(rt.js_number(n)),
    BindingValue::String(s) => rt.js_string(&s),
    BindingValue::Object(v) => Ok(v),
    BindingValue::Sequence(values) => {
      let obj = rt.create_object()?;
      for (idx, item) in values.into_iter().enumerate() {
        let key = idx.to_string();
        let value = binding_value_to_js::<Host, R>(rt, item)?;
        rt.define_data_property_str(obj, &key, value, true)?;
      }
      Ok(obj)
    }
    BindingValue::Dictionary(map) => {
      let obj = rt.create_object()?;
      for (key, item) in map {
        let value = binding_value_to_js::<Host, R>(rt, item)?;
        rt.define_data_property_str(obj, &key, value, true)?;
      }
      Ok(obj)
    }
  }
}

#[allow(dead_code)]
fn js_to_dict_foo_options<Host, R>(
  rt: &mut R,
  value: R::JsValue,
) -> Result<BindingValue<R::JsValue>, R::Error>
where
  R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
{
  if rt.is_undefined(value) || rt.is_null(value) {
    return Ok(BindingValue::Dictionary(BTreeMap::new()));
  }
  if !rt.is_object(value) {
    return Err(rt.throw_type_error("expected object for dictionary FooOptions"));
  }
  let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
  {
    let key = rt.property_key("capture")?;
    let v = rt.get(value, key)?;
    if !rt.is_undefined(v) {
      let converted = BindingValue::Bool(rt.to_boolean(v)?);
      out_dict.insert("capture".to_string(), converted);
    }
  }
  Ok(BindingValue::Dictionary(out_dict))
}

#[allow(dead_code)]
fn foo_baz<Host, R>(
  rt: &mut R,
  host: &mut Host,
  this: R::JsValue,
  args: &[R::JsValue],
) -> Result<R::JsValue, R::Error>
where
  R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  Host: WebHostBindings<R>,
{
  if args.len() >= 1 && args.len() <= 1 && (rt.is_string(args[0]) || rt.is_string_object(args[0])) {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result = host.call_operation(rt, Some(this), "Foo", "baz", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  } else if args.len() >= 1 && args.len() <= 1 && (rt.is_number(args[0])) {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Number(rt.to_number(v0)?));
      let result = host.call_operation(rt, Some(this), "Foo", "baz", 1, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  } else {
    Err(rt.throw_type_error("no matching overload for Foo.baz"))
  }
}

#[allow(dead_code)]
fn foo_qux<Host, R>(
  rt: &mut R,
  host: &mut Host,
  this: R::JsValue,
  args: &[R::JsValue],
) -> Result<R::JsValue, R::Error>
where
  R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  Host: WebHostBindings<R>,
{
  {
    let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
    let v0 = if args.len() > 0 {
      args[0]
    } else {
      rt.js_undefined()
    };
    converted_args.push(if rt.is_undefined(v0) {
      BindingValue::Undefined
    } else {
      js_to_dict_foo_options::<Host, R>(rt, v0)?
    });
    let result = host.call_operation(rt, Some(this), "Foo", "qux", 0, converted_args)?;
    binding_value_to_js::<Host, R>(rt, result)
  }
}

pub fn install_window_bindings<Host, R>(rt: &mut R, host: &mut Host) -> Result<(), R::Error>
where
  R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  Host: WebHostBindings<R>,
{
  let global = rt.global_object()?;
  let proto_foo = rt.create_object()?;
  let func = rt.create_function(foo_baz::<Host, R>)?;
  rt.define_data_property_str(proto_foo, "baz", func, true)?;
  let func = rt.create_function(foo_qux::<Host, R>)?;
  rt.define_data_property_str(proto_foo, "qux", func, true)?;
  let _ = host;
  Ok(())
}
