// @generated by `bash scripts/cargo_agent.sh xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - src/webidl/generated/mod.rs (committed snapshot; produced by `bash scripts/cargo_agent.sh xtask webidl`)

use super::host::{BindingValue, WebHostBindings};

pub mod window {
  use std::collections::BTreeMap;

  use super::{BindingValue, WebHostBindings};

  use crate::js::webidl::conversions;

  use crate::js::webidl::DataPropertyAttributes;

  fn binding_value_to_js<Host, R>(
    rt: &mut R,
    value: BindingValue<R::JsValue>,
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    match value {
      BindingValue::Undefined => Ok(rt.js_undefined()),
      BindingValue::Null => Ok(rt.js_null()),
      BindingValue::Bool(b) => Ok(rt.js_bool(b)),
      BindingValue::Number(n) => Ok(rt.js_number(n)),
      BindingValue::String(s) => rt.js_string(&s),
      BindingValue::Object(v) => Ok(v),
      BindingValue::Callback(_) => {
        Err(rt.throw_type_error("cannot return callback handles to JavaScript"))
      }
      BindingValue::Sequence(values) | BindingValue::FrozenArray(values) => {
        let obj = rt.create_array(values.len())?;
        for (idx, item) in values.into_iter().enumerate() {
          let key = idx.to_string();
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(
            obj,
            &key,
            value,
            DataPropertyAttributes::new(true, true, true),
          )?;
        }
        Ok(obj)
      }
      BindingValue::Dictionary(map) => {
        let obj = rt.create_object()?;
        for (key, item) in map {
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(
            obj,
            &key,
            value,
            DataPropertyAttributes::new(true, true, true),
          )?;
        }
        Ok(obj)
      }
    }
  }

  #[allow(dead_code, unused_variables)]
  fn js_to_dict_foo_options<Host, R>(
    rt: &mut R,
    host: &mut Host,
    value: R::JsValue,
  ) -> Result<BindingValue<R::JsValue>, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    let is_missing = rt.is_undefined(value) || rt.is_null(value);
    if !is_missing && !rt.is_object(value) {
      return Err(rt.throw_type_error("expected object for dictionary FooOptions"));
    }
    let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("capture")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("capture".to_string(), converted);
      } else {
      }
    }
    Ok(BindingValue::Dictionary(out_dict))
  }

  #[allow(dead_code)]
  fn foo_baz<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let argcount = std::cmp::min(args.len(), 1);
    match argcount {
      1 => {
        let v = args[0];
        if rt.is_string(v) || rt.is_string_object(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let result = host.call_operation(rt, Some(this), "Foo", "baz", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_number(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push(BindingValue::Number(conversions::to_long(rt, v0, conversions::IntegerConversionAttrs::default())? as f64));
            let result = host.call_operation(rt, Some(this), "Foo", "baz", 1, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let result = host.call_operation(rt, Some(this), "Foo", "baz", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        }

      },
      _ => Err(rt.throw_type_error(&format!("No matching overload for Foo.baz with {} arguments.\nCandidates:\n  - Foo.baz(DOMString)\n  - Foo.baz(long)", args.len()))),
    }
  }

  #[allow(dead_code)]
  fn foo_do_thing<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let argcount = std::cmp::min(args.len(), 2);
    match argcount {
      1 => {
        {
          let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
          let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
          converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
          let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
          converted_args.push(if rt.is_undefined(v1) { js_to_dict_foo_options::<Host, R>(rt, host, v1)? } else { {
          if rt.is_null(v1) || rt.is_undefined(v1) {
            js_to_dict_foo_options::<Host, R>(rt, host, v1)?
          } else if rt.is_object(v1) {
            js_to_dict_foo_options::<Host, R>(rt, host, v1)?
          } else {
            BindingValue::Bool(rt.to_boolean(v1)?)
          }
        } });
          let result = host.call_operation(rt, Some(this), "Foo", "doThing", 0, converted_args)?;
          binding_value_to_js::<Host, R>(rt, result)
        }
      },
      2 => {
        let v = args[1];
        if rt.is_undefined(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push(if rt.is_undefined(v1) { js_to_dict_foo_options::<Host, R>(rt, host, v1)? } else { {
            if rt.is_null(v1) || rt.is_undefined(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else if rt.is_object(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else {
              BindingValue::Bool(rt.to_boolean(v1)?)
            }
          } });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_null(v) || rt.is_undefined(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push(if rt.is_undefined(v1) { js_to_dict_foo_options::<Host, R>(rt, host, v1)? } else { {
            if rt.is_null(v1) || rt.is_undefined(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else if rt.is_object(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else {
              BindingValue::Bool(rt.to_boolean(v1)?)
            }
          } });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_string(v) || rt.is_string_object(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v1)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 2, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_object(v) && {
          let iter = rt.symbol_iterator()?;
          rt.get_method(v, iter)?.is_some()
        } {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push({
            if !rt.is_object(v1) {
              return Err(rt.throw_type_error("expected object for sequence"));
            }
            rt.with_stack_roots(&[v1], |rt| {
              let mut iterator_record = rt.get_iterator(host, v1)?;
              rt.with_stack_roots(&[iterator_record.iterator, iterator_record.next_method], |rt| {
                let mut values: Vec<BindingValue<R::JsValue>> = Vec::new();
                while let Some(next) = rt.iterator_step_value(host, &mut iterator_record)? {
                  if values.len() >= rt.limits().max_sequence_length {
                    return Err(rt.throw_range_error("sequence exceeds maximum length"));
                  }
                  let converted = rt.with_stack_roots(&[next], |rt| Ok({ let s = rt.to_string(next)?; BindingValue::String(rt.js_string_to_rust_string(s)?) }))?;
                  values.push(converted);
                }
                Ok(BindingValue::Sequence(values))
              })
            })?
          });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 1, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_object(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push(if rt.is_undefined(v1) { js_to_dict_foo_options::<Host, R>(rt, host, v1)? } else { {
            if rt.is_null(v1) || rt.is_undefined(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else if rt.is_object(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else {
              BindingValue::Bool(rt.to_boolean(v1)?)
            }
          } });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else if rt.is_boolean(v) {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push(if rt.is_undefined(v1) { js_to_dict_foo_options::<Host, R>(rt, host, v1)? } else { {
            if rt.is_null(v1) || rt.is_undefined(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else if rt.is_object(v1) {
              js_to_dict_foo_options::<Host, R>(rt, host, v1)?
            } else {
              BindingValue::Bool(rt.to_boolean(v1)?)
            }
          } });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 0, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        } else {
          {
            let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
            let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let v1 = if args.len() > 1 { args[1] } else { rt.js_undefined() };
            converted_args.push({ let s = rt.to_string(v1)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
            let result = host.call_operation(rt, Some(this), "Foo", "doThing", 2, converted_args)?;
            binding_value_to_js::<Host, R>(rt, result)
          }
        }

      },
      _ => Err(rt.throw_type_error(&format!("No matching overload for Foo.doThing with {} arguments.\nCandidates:\n  - Foo.doThing(DOMString, DOMString)\n  - Foo.doThing(DOMString, optional (FooOptions or boolean) = <default>)\n  - Foo.doThing(DOMString, sequence<DOMString>)", args.len()))),
    }
  }

  #[allow(dead_code)]
  fn foo_qux<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(js_to_dict_foo_options::<Host, R>(rt, host, v0)?);
      let result = host.call_operation(rt, Some(this), "Foo", "qux", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn foo_takes_frozen_array<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        if !rt.is_object(v0) {
          return Err(rt.throw_type_error("expected object for FrozenArray"));
        }
        rt.with_stack_roots(&[v0], |rt| {
          let mut iterator_record = rt.get_iterator(host, v0)?;
          rt.with_stack_roots(
            &[iterator_record.iterator, iterator_record.next_method],
            |rt| {
              let mut values: Vec<BindingValue<R::JsValue>> = Vec::new();
              while let Some(next) = rt.iterator_step_value(host, &mut iterator_record)? {
                if values.len() >= rt.limits().max_sequence_length {
                  return Err(rt.throw_range_error("FrozenArray exceeds maximum length"));
                }
                let converted = rt.with_stack_roots(&[next], |rt| {
                  Ok(BindingValue::Number(conversions::to_long(
                    rt,
                    next,
                    conversions::IntegerConversionAttrs {
                      clamp: false,
                      enforce_range: true,
                    },
                  )? as f64))
                })?;
                values.push(converted);
              }
              Ok(BindingValue::FrozenArray(values))
            },
          )
        })?
      });
      let result =
        host.call_operation(rt, Some(this), "Foo", "takesFrozenArray", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn foo_takes_sequence<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        if !rt.is_object(v0) {
          return Err(rt.throw_type_error("expected object for sequence"));
        }
        rt.with_stack_roots(&[v0], |rt| {
          let mut iterator_record = rt.get_iterator(host, v0)?;
          rt.with_stack_roots(
            &[iterator_record.iterator, iterator_record.next_method],
            |rt| {
              let mut values: Vec<BindingValue<R::JsValue>> = Vec::new();
              while let Some(next) = rt.iterator_step_value(host, &mut iterator_record)? {
                if values.len() >= rt.limits().max_sequence_length {
                  return Err(rt.throw_range_error("sequence exceeds maximum length"));
                }
                let converted = rt.with_stack_roots(&[next], |rt| {
                  Ok(BindingValue::Number(conversions::to_long(
                    rt,
                    next,
                    conversions::IntegerConversionAttrs {
                      clamp: true,
                      enforce_range: false,
                    },
                  )? as f64))
                })?;
                values.push(converted);
              }
              Ok(BindingValue::Sequence(values))
            },
          )
        })?
      });
      let result =
        host.call_operation(rt, Some(this), "Foo", "takesSequence", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  pub fn install_window_bindings<Host, R>(rt: &mut R, host: &mut Host) -> Result<(), R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let global = rt.global_object()?;
    let proto_foo = rt.create_object()?;
    let func = rt.create_function("baz", 1, foo_baz::<Host, R>)?;
    rt.define_method(proto_foo, "baz", func)?;
    let func = rt.create_function("doThing", 1, foo_do_thing::<Host, R>)?;
    rt.define_method(proto_foo, "doThing", func)?;
    let func = rt.create_function("qux", 0, foo_qux::<Host, R>)?;
    rt.define_method(proto_foo, "qux", func)?;
    let func = rt.create_function("takesFrozenArray", 1, foo_takes_frozen_array::<Host, R>)?;
    rt.define_method(proto_foo, "takesFrozenArray", func)?;
    let func = rt.create_function("takesSequence", 1, foo_takes_sequence::<Host, R>)?;
    rt.define_method(proto_foo, "takesSequence", func)?;
    let _ = host;
    Ok(())
  }
}

pub use window::install_window_bindings;
