// @generated by `bash scripts/cargo_agent.sh xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - src/webidl/generated/mod.rs (committed snapshot; produced by `bash scripts/cargo_agent.sh xtask webidl`)

pub mod window {
  use std::ptr::NonNull;
  use std::sync::OnceLock;

  use vm_js::{GcObject, Heap, Realm, Scope, Value, Vm, VmError, VmHost, VmHostHooks};
  use webidl_vm_js::bindings_runtime::{BindingsRuntime, DataPropertyAttributes};
  use webidl_vm_js::{host_from_hooks, VmJsWebIdlCx};

  use webidl_ir::{
    DefaultValue, DictionaryMemberSchema, DictionarySchema, IdlType, NamedType, NamedTypeKind,
    NumericLiteral, NumericType, StringType, TypeAnnotation, TypeContext,
  };
  use webidl_js_runtime::{
    convert_arguments, resolve_overload, ArgumentSchema, ConvertedValue, InterfaceId,
    JsRuntime as _, Optionality, OverloadArg, OverloadSig, WebIdlHooks, WebIdlJsRuntime as _,
    WebIdlLimits,
  };

  struct NoHooks;

  impl WebIdlHooks<Value> for NoHooks {
    fn is_platform_object(&self, _value: Value) -> bool {
      false
    }

    fn implements_interface(&self, _value: Value, _interface: InterfaceId) -> bool {
      false
    }
  }

  static NO_HOOKS: NoHooks = NoHooks;

  fn type_context() -> &'static TypeContext {
    static CTX: OnceLock<TypeContext> = OnceLock::new();
    CTX.get_or_init(|| {
      let mut ctx = TypeContext::default();

      ctx.add_dictionary(DictionarySchema {
        name: "FooOptions".to_string(),
        inherits: None,
        members: vec![DictionaryMemberSchema {
          name: "capture".to_string(),
          required: false,
          ty: IdlType::Boolean,
          default: None,
        }],
      });
      ctx
    })
  }

  fn converted_value_to_js(
    cx: &mut VmJsWebIdlCx<'_>,
    value: ConvertedValue<Value>,
  ) -> Result<Value, VmError> {
    Ok(match value {
      ConvertedValue::Undefined => Value::Undefined,
      ConvertedValue::Null => Value::Null,
      ConvertedValue::Boolean(b) => Value::Bool(b),
      ConvertedValue::Byte(n) => Value::Number(n as f64),
      ConvertedValue::Octet(n) => Value::Number(n as f64),
      ConvertedValue::Short(n) => Value::Number(n as f64),
      ConvertedValue::UnsignedShort(n) => Value::Number(n as f64),
      ConvertedValue::Long(n) => Value::Number(n as f64),
      ConvertedValue::UnsignedLong(n) => Value::Number(n as f64),
      ConvertedValue::LongLong(n) => Value::Number(n as f64),
      ConvertedValue::UnsignedLongLong(n) => Value::Number(n as f64),
      ConvertedValue::Float(n) => Value::Number(n as f64),
      ConvertedValue::UnrestrictedFloat(n) => Value::Number(n as f64),
      ConvertedValue::Double(n) => Value::Number(n),
      ConvertedValue::UnrestrictedDouble(n) => Value::Number(n),
      ConvertedValue::String(s) | ConvertedValue::Enum(s) => cx.alloc_string(&s)?,
      ConvertedValue::Any(v) | ConvertedValue::Object(v) => v,
      ConvertedValue::PlatformObject(obj) => cx
        .platform_object_to_js_value(&obj)
        .ok_or_else(|| cx.throw_type_error("Unsupported platform object value for this runtime"))?,
      ConvertedValue::Sequence { values, .. } => {
        let arr = cx.alloc_array()?;
        for (idx, item) in values.into_iter().enumerate() {
          let key = cx.property_key_from_u32(idx as u32)?;
          let value = converted_value_to_js(cx, item)?;
          cx.define_data_property(arr, key, value, true)?;
        }
        arr
      }
      ConvertedValue::Record { entries, .. } => {
        let obj = cx.alloc_object()?;
        for (k, v) in entries {
          let key = cx.property_key_from_str(&k)?;
          let value = converted_value_to_js(cx, v)?;
          cx.define_data_property(obj, key, value, true)?;
        }
        obj
      }
      ConvertedValue::Dictionary { members, .. } => {
        let obj = cx.alloc_object()?;
        for (k, v) in members {
          let key = cx.property_key_from_str(&k)?;
          let value = converted_value_to_js(cx, v)?;
          cx.define_data_property(obj, key, value, true)?;
        }
        obj
      }
      ConvertedValue::Union { value, .. } => {
        return converted_value_to_js(cx, *value);
      }
    })
  }

  #[allow(dead_code)]
  fn bar_entries(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Bar",
      "entries",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn bar_for_each(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![vec![
        ArgumentSchema {
          name: "callback",
          ty: IdlType::Any,
          optional: false,
          variadic: false,
          default: None,
        },
        ArgumentSchema {
          name: "thisArg",
          ty: IdlType::Any,
          optional: true,
          variadic: false,
          default: None,
        },
      ]]
    });
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Bar",
      "forEach",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn bar_keys(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Bar",
      "keys",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn bar_values(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Bar",
      "values",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn bar_call_without_new(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    _hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    _this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    Err(rt.throw_type_error("Illegal constructor"))
  }

  #[allow(dead_code)]
  fn bar_construct(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    callee: GcObject,
    args: &[Value],
    new_target: Value,
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    let slots = cx.scope.heap().get_function_native_slots(callee)?;
    let proto_slot = slots.get(0).copied().unwrap_or(Value::Undefined);
    let Value::Object(default_proto) = proto_slot else {
      return Err(VmError::InvariantViolation(
        "Bar constructor missing prototype slot",
      ));
    };
    // Derive the wrapper object's prototype from `new.target` (subclassing semantics).
    //
    // This follows the spirit of `GetPrototypeFromConstructor` / `OrdinaryCreateFromConstructor`:
    // - default to the interface prototype cached in native slots,
    // - if `new_target` is an object and `new_target.prototype` is an object, use that instead.
    cx.scope.push_root(Value::Object(default_proto))?;
    cx.scope.push_root(new_target)?;
    let mut wrapper_proto = default_proto;
    if let Value::Object(new_target_obj) = new_target {
      cx.scope.push_root(Value::Object(new_target_obj))?;
      let proto_key = cx.property_key_from_str("prototype")?;
      let candidate = cx.get(Value::Object(new_target_obj), proto_key)?;
      if let Value::Object(candidate_obj) = candidate {
        cx.scope.push_root(Value::Object(candidate_obj))?;
        wrapper_proto = candidate_obj;
      }
    }
    let obj = cx.scope.alloc_object_with_prototype(Some(wrapper_proto))?;
    cx.scope.push_root(Value::Object(obj))?;

    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    let _ = bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      Some(Value::Object(obj)),
      "Bar",
      "constructor",
      overload_index,
      &converted_js_args,
    )?;
    Ok(Value::Object(obj))
  }

  #[allow(dead_code)]
  fn foo_baz(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![
        vec![ArgumentSchema {
          name: "s",
          ty: IdlType::String(StringType::DomString),
          optional: false,
          variadic: false,
          default: None,
        }],
        vec![ArgumentSchema {
          name: "x",
          ty: IdlType::Numeric(NumericType::Long),
          optional: false,
          variadic: false,
          default: None,
        }],
      ]
    });
    let overload_index: usize = {
      static OVERLOADS: OnceLock<Vec<OverloadSig>> = OnceLock::new();
      let overloads = OVERLOADS.get_or_init(|| {
        vec![
          OverloadSig {
            args: vec![OverloadArg {
              ty: IdlType::String(StringType::DomString),
              optionality: Optionality::Required,
              default: None,
            }],
            decl_index: 0,
            distinguishing_arg_index_by_arg_count: None,
          },
          OverloadSig {
            args: vec![OverloadArg {
              ty: IdlType::Numeric(NumericType::Long),
              optionality: Optionality::Required,
              default: None,
            }],
            decl_index: 1,
            distinguishing_arg_index_by_arg_count: None,
          },
        ]
      });
      resolve_overload(&mut cx, overloads, args)?.overload_index
    };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "baz",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_do_thing(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![
        vec![
          ArgumentSchema {
            name: "name",
            ty: IdlType::String(StringType::DomString),
            optional: false,
            variadic: false,
            default: None,
          },
          ArgumentSchema {
            name: "options",
            ty: IdlType::Union(vec![
              IdlType::Named(NamedType {
                name: "FooOptions".to_string(),
                kind: NamedTypeKind::Dictionary,
              }),
              IdlType::Boolean,
            ]),
            optional: true,
            variadic: false,
            default: Some(DefaultValue::EmptyDictionary),
          },
        ],
        vec![
          ArgumentSchema {
            name: "name",
            ty: IdlType::String(StringType::DomString),
            optional: false,
            variadic: false,
            default: None,
          },
          ArgumentSchema {
            name: "items",
            ty: IdlType::Sequence(Box::new(IdlType::String(StringType::DomString))),
            optional: false,
            variadic: false,
            default: None,
          },
        ],
        vec![
          ArgumentSchema {
            name: "name",
            ty: IdlType::String(StringType::DomString),
            optional: false,
            variadic: false,
            default: None,
          },
          ArgumentSchema {
            name: "item",
            ty: IdlType::String(StringType::DomString),
            optional: false,
            variadic: false,
            default: None,
          },
        ],
      ]
    });
    let overload_index: usize = {
      static OVERLOADS: OnceLock<Vec<OverloadSig>> = OnceLock::new();
      let overloads = OVERLOADS.get_or_init(|| {
        vec![
          OverloadSig {
            args: vec![
              OverloadArg {
                ty: IdlType::String(StringType::DomString),
                optionality: Optionality::Required,
                default: None,
              },
              OverloadArg {
                ty: IdlType::Union(vec![
                  IdlType::Named(NamedType {
                    name: "FooOptions".to_string(),
                    kind: NamedTypeKind::Dictionary,
                  }),
                  IdlType::Boolean,
                ]),
                optionality: Optionality::Optional,
                default: Some(DefaultValue::EmptyDictionary),
              },
            ],
            decl_index: 0,
            distinguishing_arg_index_by_arg_count: None,
          },
          OverloadSig {
            args: vec![
              OverloadArg {
                ty: IdlType::String(StringType::DomString),
                optionality: Optionality::Required,
                default: None,
              },
              OverloadArg {
                ty: IdlType::Sequence(Box::new(IdlType::String(StringType::DomString))),
                optionality: Optionality::Required,
                default: None,
              },
            ],
            decl_index: 1,
            distinguishing_arg_index_by_arg_count: None,
          },
          OverloadSig {
            args: vec![
              OverloadArg {
                ty: IdlType::String(StringType::DomString),
                optionality: Optionality::Required,
                default: None,
              },
              OverloadArg {
                ty: IdlType::String(StringType::DomString),
                optionality: Optionality::Required,
                default: None,
              },
            ],
            decl_index: 2,
            distinguishing_arg_index_by_arg_count: None,
          },
        ]
      });
      resolve_overload(&mut cx, overloads, args)?.overload_index
    };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "doThing",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_entries(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "entries",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_for_each(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![vec![
        ArgumentSchema {
          name: "callback",
          ty: IdlType::Any,
          optional: false,
          variadic: false,
          default: None,
        },
        ArgumentSchema {
          name: "thisArg",
          ty: IdlType::Any,
          optional: true,
          variadic: false,
          default: None,
        },
      ]]
    });
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "forEach",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_keys(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "keys",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_qux(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![vec![ArgumentSchema {
        name: "options",
        ty: IdlType::Named(NamedType {
          name: "FooOptions".to_string(),
          kind: NamedTypeKind::Dictionary,
        }),
        optional: true,
        variadic: false,
        default: None,
      }]]
    });
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "qux",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_takes_frozen_array(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![vec![ArgumentSchema {
        name: "values",
        ty: IdlType::Annotated {
          annotations: vec![TypeAnnotation::EnforceRange],
          inner: Box::new(IdlType::FrozenArray(Box::new(IdlType::Numeric(
            NumericType::Long,
          )))),
        },
        optional: false,
        variadic: false,
        default: None,
      }]]
    });
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "takesFrozenArray",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_takes_sequence(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| {
      vec![vec![ArgumentSchema {
        name: "values",
        ty: IdlType::Annotated {
          annotations: vec![TypeAnnotation::Clamp],
          inner: Box::new(IdlType::Sequence(Box::new(IdlType::Numeric(
            NumericType::Long,
          )))),
        },
        optional: false,
        variadic: false,
        default: None,
      }]]
    });
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "takesSequence",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_values(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    this: Value,
    args: &[Value],
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    cx.scope.push_root(this)?;
    let receiver = Some(this);
    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      receiver,
      "Foo",
      "values",
      overload_index,
      &converted_js_args,
    )
  }

  #[allow(dead_code)]
  fn foo_call_without_new(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    _host: &mut dyn VmHost,
    _hooks: &mut dyn VmHostHooks,
    _callee: GcObject,
    _this: Value,
    _args: &[Value],
  ) -> Result<Value, VmError> {
    let mut rt = BindingsRuntime::from_scope(vm, scope.reborrow());
    let rt = &mut rt;
    Err(rt.throw_type_error("Illegal constructor"))
  }

  #[allow(dead_code)]
  fn foo_construct(
    vm: &mut Vm,
    scope: &mut Scope<'_>,
    host: &mut dyn VmHost,
    hooks: &mut dyn VmHostHooks,
    callee: GcObject,
    args: &[Value],
    new_target: Value,
  ) -> Result<Value, VmError> {
    let mut bindings_host = {
      let host = host_from_hooks(hooks)?;
      NonNull::from(host)
    };
    let mut cx =
      VmJsWebIdlCx::from_native_call(vm, scope, host, hooks, WebIdlLimits::default(), &NO_HOOKS);
    let slots = cx.scope.heap().get_function_native_slots(callee)?;
    let proto_slot = slots.get(0).copied().unwrap_or(Value::Undefined);
    let Value::Object(default_proto) = proto_slot else {
      return Err(VmError::InvariantViolation(
        "Foo constructor missing prototype slot",
      ));
    };
    // Derive the wrapper object's prototype from `new.target` (subclassing semantics).
    //
    // This follows the spirit of `GetPrototypeFromConstructor` / `OrdinaryCreateFromConstructor`:
    // - default to the interface prototype cached in native slots,
    // - if `new_target` is an object and `new_target.prototype` is an object, use that instead.
    cx.scope.push_root(Value::Object(default_proto))?;
    cx.scope.push_root(new_target)?;
    let mut wrapper_proto = default_proto;
    if let Value::Object(new_target_obj) = new_target {
      cx.scope.push_root(Value::Object(new_target_obj))?;
      let proto_key = cx.property_key_from_str("prototype")?;
      let candidate = cx.get(Value::Object(new_target_obj), proto_key)?;
      if let Value::Object(candidate_obj) = candidate {
        cx.scope.push_root(Value::Object(candidate_obj))?;
        wrapper_proto = candidate_obj;
      }
    }
    let obj = cx.scope.alloc_object_with_prototype(Some(wrapper_proto))?;
    cx.scope.push_root(Value::Object(obj))?;

    static ARG_SCHEMAS: OnceLock<Vec<Vec<ArgumentSchema>>> = OnceLock::new();
    let arg_schemas = ARG_SCHEMAS.get_or_init(|| vec![vec![]]);
    let overload_index: usize = { 0 };
    let params = &arg_schemas[overload_index];
    let ctx = type_context();
    let converted_args = convert_arguments(&mut cx, args, params, ctx)?;
    let mut converted_js_args: Vec<Value> = Vec::with_capacity(converted_args.len());
    for value in converted_args {
      converted_js_args.push(converted_value_to_js(&mut cx, value)?);
    }
    let bindings_host = unsafe { bindings_host.as_mut() };
    let _ = bindings_host.call_operation(
      cx.vm,
      &mut cx.scope,
      Some(Value::Object(obj)),
      "Foo",
      "constructor",
      overload_index,
      &converted_js_args,
    )?;
    Ok(Value::Object(obj))
  }

  pub fn install_bar_bindings_vm_js(
    vm: &mut Vm,
    heap: &mut Heap,
    realm: &Realm,
  ) -> Result<(), VmError> {
    let mut rt = BindingsRuntime::new(vm, heap);
    let global = realm.global_object();
    rt.scope.push_root(Value::Object(global))?;

    let key = rt.property_key("Bar")?;
    if rt
      .scope
      .heap()
      .object_get_own_property(global, &key)?
      .is_some()
    {
      return Ok(());
    }

    let global_var_attrs = DataPropertyAttributes::new(true, false, true);
    let ctor_link_attrs = DataPropertyAttributes::new(false, false, false);

    let proto_bar = rt.alloc_object()?;
    let func = rt.alloc_native_function(bar_entries, None, "entries", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "entries",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_for_each, None, "forEach", 1)?;
    rt.define_data_property_str(
      proto_bar,
      "forEach",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_keys, None, "keys", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "keys",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(bar_values, None, "values", 0)?;
    rt.define_data_property_str(
      proto_bar,
      "values",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let iterator_key = vm_js::PropertyKey::from_symbol(realm.well_known_symbols().iterator);
    rt.define_data_property(
      proto_bar,
      iterator_key,
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let slots = [Value::Object(proto_bar)];
    let ctor_bar = rt.alloc_native_function_with_slots(
      bar_call_without_new,
      Some(bar_construct),
      "Bar",
      0,
      &slots,
    )?;
    rt.define_data_property_str(global, "Bar", Value::Object(ctor_bar), global_var_attrs)?;
    rt.define_data_property_str(
      ctor_bar,
      "prototype",
      Value::Object(proto_bar),
      ctor_link_attrs,
    )?;
    rt.define_data_property_str(
      proto_bar,
      "constructor",
      Value::Object(ctor_bar),
      ctor_link_attrs,
    )?;
    Ok(())
  }

  pub fn install_foo_bindings_vm_js(
    vm: &mut Vm,
    heap: &mut Heap,
    realm: &Realm,
  ) -> Result<(), VmError> {
    let mut rt = BindingsRuntime::new(vm, heap);
    let global = realm.global_object();
    rt.scope.push_root(Value::Object(global))?;

    let key = rt.property_key("Foo")?;
    if rt
      .scope
      .heap()
      .object_get_own_property(global, &key)?
      .is_some()
    {
      return Ok(());
    }

    let global_var_attrs = DataPropertyAttributes::new(true, false, true);
    let ctor_link_attrs = DataPropertyAttributes::new(false, false, false);

    let proto_foo = rt.alloc_object()?;
    let func = rt.alloc_native_function(foo_baz, None, "baz", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "baz",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_do_thing, None, "doThing", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "doThing",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_entries, None, "entries", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "entries",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let iterator_key = vm_js::PropertyKey::from_symbol(realm.well_known_symbols().iterator);
    rt.define_data_property(
      proto_foo,
      iterator_key,
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_for_each, None, "forEach", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "forEach",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_keys, None, "keys", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "keys",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_qux, None, "qux", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "qux",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_takes_frozen_array, None, "takesFrozenArray", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "takesFrozenArray",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_takes_sequence, None, "takesSequence", 1)?;
    rt.define_data_property_str(
      proto_foo,
      "takesSequence",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.alloc_native_function(foo_values, None, "values", 0)?;
    rt.define_data_property_str(
      proto_foo,
      "values",
      Value::Object(func),
      DataPropertyAttributes::METHOD,
    )?;
    let slots = [Value::Object(proto_foo)];
    let ctor_foo = rt.alloc_native_function_with_slots(
      foo_call_without_new,
      Some(foo_construct),
      "Foo",
      0,
      &slots,
    )?;
    rt.define_data_property_str(global, "Foo", Value::Object(ctor_foo), global_var_attrs)?;
    rt.define_data_property_str(
      ctor_foo,
      "prototype",
      Value::Object(proto_foo),
      ctor_link_attrs,
    )?;
    rt.define_data_property_str(
      proto_foo,
      "constructor",
      Value::Object(ctor_foo),
      ctor_link_attrs,
    )?;
    Ok(())
  }

  pub fn install_window_bindings_vm_js(
    vm: &mut Vm,
    heap: &mut Heap,
    realm: &Realm,
  ) -> Result<(), VmError> {
    install_bar_bindings_vm_js(vm, heap, realm)?;
    install_foo_bindings_vm_js(vm, heap, realm)?;
    Ok(())
  }
}

pub use window::install_bar_bindings_vm_js;
pub use window::install_foo_bindings_vm_js;
pub use window::install_window_bindings_vm_js;
