//! Spec-shaped HTML `<script>` scheduling state machine.
//!
//! This scheduler is designed to be deterministic and unit-testable. It does not execute scripts or
//! fetch network resources directly. Instead, callers drive it with explicit discovery/completion
//! events and perform the returned [`HtmlScriptSchedulerAction`] values.
//!
//! Compared to the legacy classic-only `ScriptScheduler` (removed), this scheduler models:
//! - classic scripts (parser-blocking vs `async` vs `defer`)
//! - module scripts (`type="module"`, inline + external)
//! - import maps (`type="importmap"`, inline-only)
//! - `nomodule` (when modules are supported)
//! - spec-correct ordering for dynamically inserted external scripts without `async`
//!
//! The scheduling model follows the WHATWG HTML Standard's conceptual lists/sets:
//! - "set of scripts that will execute as soon as possible" (async)
//! - "list of scripts that will execute in order as soon as possible" (ordered-asap)
//! - "list of scripts that will execute when the document has finished parsing" (post-parse)

use crate::error::{Error, Result};
use crate::resource::{FetchCredentialsMode, FetchDestination};

use super::{JsExecutionOptions, ScriptElementSpec, ScriptType};

use std::collections::HashMap;

/// Opaque ID for a `<script>` element managed by [`HtmlScriptScheduler`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct HtmlScriptId(u64);

impl HtmlScriptId {
  /// Construct an [`HtmlScriptId`] from a raw numeric value.
  ///
  /// This is `pub(crate)` because `HtmlScriptId` values are normally generated by
  /// [`HtmlScriptScheduler`]. It exists for internal tests and embeddings that need to build
  /// synthetic script identifiers.
  pub(crate) fn from_u64(id: u64) -> Self {
    Self(id)
  }

  pub fn as_u64(self) -> u64 {
    self.0
  }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptEventKind {
  Load,
  Error,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HtmlScriptWork {
  Classic {
    source_text: Option<String>,
  },
  Module {
    source_text: Option<String>,
  },
  ImportMap {
    source_text: String,
    base_url: Option<String>,
  },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HtmlDiscoveredScript<NodeId> {
  pub id: HtmlScriptId,
  pub actions: Vec<HtmlScriptSchedulerAction<NodeId>>,
}

/// Action stream produced by [`HtmlScriptScheduler`].
///
/// This is intentionally spec-shaped: it models the host obligations described by WHATWG HTML
/// ("start a fetch", "queue a task", "execute now", ...), but leaves the embedding responsible for
/// performing the actual work.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HtmlScriptSchedulerAction<NodeId> {
  /// Begin fetching an external classic script.
  StartClassicFetch {
    script_id: HtmlScriptId,
    node_id: NodeId,
    url: String,
    destination: FetchDestination,
    credentials_mode: FetchCredentialsMode,
  },
  /// Begin fetching the module graph for an external module script (`type="module" src=...`).
  ///
  /// The full [`ScriptElementSpec`] is included so the orchestrator can extract module fetch options
  /// (credentials mode, referrer policy, etc.) as the spec surface evolves.
  StartModuleGraphFetch {
    script_id: HtmlScriptId,
    node_id: NodeId,
    url: String,
    destination: FetchDestination,
    element: ScriptElementSpec,
  },
  /// Begin fetching the module graph for an inline module script (`type="module"` with no `src`).
  StartInlineModuleGraphFetch {
    script_id: HtmlScriptId,
    node_id: NodeId,
    source_text: String,
    base_url: Option<String>,
    element: ScriptElementSpec,
  },
  /// Block parsing until the referenced script has executed.
  ///
  /// This is emitted for parser-blocking external classic scripts (no `async`/`defer`).
  BlockParserUntilExecuted {
    script_id: HtmlScriptId,
    node_id: NodeId,
  },
  /// Execute a script immediately (synchronously in the caller's stack).
  ///
  /// The orchestrator must perform a microtask checkpoint immediately after execution.
  ExecuteNow {
    script_id: HtmlScriptId,
    node_id: NodeId,
    work: HtmlScriptWork,
  },
  /// Queue script execution as an event-loop task.
  ///
  /// The event loop performs a microtask checkpoint after each task, satisfying the HTML microtask
  /// checkpoint requirement after script execution.
  QueueTask {
    script_id: HtmlScriptId,
    node_id: NodeId,
    work: HtmlScriptWork,
  },
  /// Queue an "element task" to dispatch a `load` or `error` event at a `<script>` element.
  QueueScriptEventTask {
    script_id: HtmlScriptId,
    node_id: NodeId,
    event: ScriptEventKind,
  },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ScriptKind {
  Classic,
  Module,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ScheduleMode {
  /// Parser-blocking external classic scripts (no `async`/`defer`).
  ParserBlocking,
  /// "as soon as possible" unordered set (async scripts).
  Async,
  /// "in order as soon as possible" list (non-parser-inserted scripts without `async`).
  OrderedAsap,
  /// "when parsing is complete" list (classic defer, parser-inserted modules).
  PostParse,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ReadyPayload {
  ClassicSource(Option<String>),
  ModuleSource(Option<String>),
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ScriptEntry<NodeId> {
  node_id: NodeId,
  #[allow(dead_code)]
  base_url_at_discovery: Option<String>,
  kind: ScriptKind,
  mode: ScheduleMode,
  ready: Option<ReadyPayload>,
  queued_for_execution: bool,
}

pub struct HtmlScriptScheduler<NodeId> {
  next_script_id: u64,
  /// Whether this document supports module scripts (and related features such as import maps).
  ///
  /// When `false`, `<script type="module">` and `<script type="importmap">` are treated as unknown
  /// and ignored, and the `nomodule` attribute has no effect on classic scripts.
  modules_supported: bool,

  scripts: HashMap<HtmlScriptId, ScriptEntry<NodeId>>,

  // "list of scripts that will execute in order as soon as possible"
  ordered_asap: Vec<HtmlScriptId>,
  next_ordered_asap_to_queue: usize,

  // "list of scripts that will execute when the document has finished parsing"
  post_parse: Vec<HtmlScriptId>,
  next_post_parse_to_queue: usize,
  parsing_completed: bool,
}

impl<NodeId> Default for HtmlScriptScheduler<NodeId> {
  fn default() -> Self {
    Self {
      next_script_id: 1,
      modules_supported: true,
      scripts: HashMap::new(),
      ordered_asap: Vec::new(),
      next_ordered_asap_to_queue: 0,
      post_parse: Vec::new(),
      next_post_parse_to_queue: 0,
      parsing_completed: false,
    }
  }
}

impl<NodeId: Clone> HtmlScriptScheduler<NodeId> {
  pub fn new() -> Self {
    Self::default()
  }

  pub fn modules_supported(&self) -> bool {
    self.modules_supported
  }

  pub fn with_modules_supported(modules_supported: bool) -> Self {
    Self {
      modules_supported,
      ..Self::default()
    }
  }

  pub fn set_modules_supported(&mut self, modules_supported: bool) {
    self.modules_supported = modules_supported;
  }

  pub fn set_options(&mut self, options: JsExecutionOptions) {
    self.set_modules_supported(options.supports_module_scripts);
  }

  fn alloc_script_id(&mut self) -> HtmlScriptId {
    let id = HtmlScriptId(self.next_script_id);
    self.next_script_id += 1;
    id
  }

  /// Notify the scheduler that the HTML parser has discovered a parser-inserted `<script>`.
  pub fn discovered_parser_script(
    &mut self,
    element: ScriptElementSpec,
    node_id: NodeId,
    base_url_at_discovery: Option<String>,
  ) -> Result<HtmlDiscoveredScript<NodeId>> {
    let mut element = element;
    element.parser_inserted = true;
    self.discovered_script(element, node_id, base_url_at_discovery)
  }

  /// Notify the scheduler that a `<script>` element has been discovered.
  pub fn discovered_script(
    &mut self,
    element: ScriptElementSpec,
    node_id: NodeId,
    base_url_at_discovery: Option<String>,
  ) -> Result<HtmlDiscoveredScript<NodeId>> {
    let id = self.alloc_script_id();
    let mut actions: Vec<HtmlScriptSchedulerAction<NodeId>> = Vec::new();

    // HTML: If there is no `src` attribute and the source text is empty, "prepare a script" returns
    // early.
    if !element.src_attr_present && element.inline_text.is_empty() {
      return Ok(HtmlDiscoveredScript { id, actions });
    }

    // If the host does not support module scripts, ignore both module scripts and import maps.
    //
    // This mirrors browser behavior on engines without module support:
    // - `<script type="module">` is ignored
    // - `<script type="importmap">` is ignored (treated as an unknown script type)
    //
    // In this mode, `nomodule` classic scripts should still execute.
    if !self.modules_supported
      && matches!(
        element.script_type,
        ScriptType::Module | ScriptType::ImportMap
      )
    {
      return Ok(HtmlDiscoveredScript { id, actions });
    }

    // `nomodule` only applies to classic scripts when modules are supported.
    if element.script_type == ScriptType::Classic && element.nomodule_attr && self.modules_supported
    {
      return Ok(HtmlDiscoveredScript { id, actions });
    }

    match element.script_type {
      ScriptType::Unknown => {}
      ScriptType::ImportMap => {
        // Import maps must be inline-only.
        if element.src_attr_present {
          actions.push(HtmlScriptSchedulerAction::QueueScriptEventTask {
            script_id: id,
            node_id,
            event: ScriptEventKind::Error,
          });
          return Ok(HtmlDiscoveredScript { id, actions });
        }

        let base_url = base_url_at_discovery
          .clone()
          .or_else(|| element.base_url.clone());
        let work = HtmlScriptWork::ImportMap {
          source_text: element.inline_text,
          base_url,
        };

        // HTML: parser-inserted import maps are processed synchronously. For dynamically inserted
        // import maps, queue a task (mirroring the legacy scheduler's behavior and keeping script
        // execution out of the current JS stack).
        if element.parser_inserted {
          actions.push(HtmlScriptSchedulerAction::ExecuteNow {
            script_id: id,
            node_id,
            work,
          });
        } else {
          actions.push(HtmlScriptSchedulerAction::QueueTask {
            script_id: id,
            node_id,
            work,
          });
        }
        return Ok(HtmlDiscoveredScript { id, actions });
      }
      ScriptType::Classic => {
        if !element.src_attr_present {
          actions.push(HtmlScriptSchedulerAction::ExecuteNow {
            script_id: id,
            node_id,
            work: HtmlScriptWork::Classic {
              source_text: Some(element.inline_text),
            },
          });
          return Ok(HtmlDiscoveredScript { id, actions });
        }

        let Some(url) = element.src.clone().filter(|s| !s.is_empty()) else {
          // `src` attribute present but empty/invalid/unresolvable: HTML fires an error event and does
          // not fall back to inline execution.
          actions.push(HtmlScriptSchedulerAction::QueueScriptEventTask {
            script_id: id,
            node_id,
            event: ScriptEventKind::Error,
          });
          return Ok(HtmlDiscoveredScript { id, actions });
        };

        let is_async = element.async_attr || element.force_async;
        let mode = if element.parser_inserted && !is_async && !element.defer_attr {
          ScheduleMode::ParserBlocking
        } else if is_async {
          ScheduleMode::Async
        } else if element.parser_inserted {
          // `defer` scripts, in document order.
          ScheduleMode::PostParse
        } else {
          // Dynamically inserted classic scripts without async: execute in insertion order as soon as
          // possible (spec "ordered as soon as possible" list).
          ScheduleMode::OrderedAsap
        };

        if mode == ScheduleMode::OrderedAsap {
          self.ordered_asap.push(id);
        }
        if mode == ScheduleMode::PostParse {
          self.post_parse.push(id);
        }

        self.scripts.insert(
          id,
          ScriptEntry {
            node_id: node_id.clone(),
            base_url_at_discovery,
            kind: ScriptKind::Classic,
            mode,
            ready: None,
            queued_for_execution: false,
          },
        );

        let (destination, credentials_mode) = if let Some(cors_mode) = element.crossorigin {
          (FetchDestination::ScriptCors, cors_mode.credentials_mode())
        } else {
          (FetchDestination::Script, FetchCredentialsMode::Include)
        };
        actions.push(HtmlScriptSchedulerAction::StartClassicFetch {
          script_id: id,
          node_id: node_id.clone(),
          url,
          destination,
          credentials_mode,
        });

        if mode == ScheduleMode::ParserBlocking {
          actions.push(HtmlScriptSchedulerAction::BlockParserUntilExecuted {
            script_id: id,
            node_id,
          });
        }

        return Ok(HtmlDiscoveredScript { id, actions });
      }
      ScriptType::Module => {
        // HTML: `defer` has no effect on module scripts.
        let is_async = element.async_attr || element.force_async;
        let mode = if is_async {
          ScheduleMode::Async
        } else if element.parser_inserted {
          // Parser-inserted module scripts are deferred by default.
          ScheduleMode::PostParse
        } else {
          // Dynamically inserted module scripts that are not async-like execute in insertion order.
          ScheduleMode::OrderedAsap
        };

        if element.src_attr_present {
          let Some(url) = element.src.clone().filter(|s| !s.is_empty()) else {
            actions.push(HtmlScriptSchedulerAction::QueueScriptEventTask {
              script_id: id,
              node_id,
              event: ScriptEventKind::Error,
            });
            return Ok(HtmlDiscoveredScript { id, actions });
          };

          if mode == ScheduleMode::OrderedAsap {
            self.ordered_asap.push(id);
          }
          if mode == ScheduleMode::PostParse {
            self.post_parse.push(id);
          }

          self.scripts.insert(
            id,
            ScriptEntry {
              node_id: node_id.clone(),
              base_url_at_discovery,
              kind: ScriptKind::Module,
              mode,
              ready: None,
              queued_for_execution: false,
            },
          );

          // Module scripts are fetched in CORS mode regardless of the `crossorigin` attribute.
          actions.push(HtmlScriptSchedulerAction::StartModuleGraphFetch {
            script_id: id,
            node_id: node_id.clone(),
            url,
            destination: FetchDestination::ScriptCors,
            element: element.clone(),
          });
          return Ok(HtmlDiscoveredScript { id, actions });
        }

        // Inline module script.
        let base_url = base_url_at_discovery
          .clone()
          .or_else(|| element.base_url.clone());

        if mode == ScheduleMode::OrderedAsap {
          self.ordered_asap.push(id);
        }
        if mode == ScheduleMode::PostParse {
          self.post_parse.push(id);
        }

        self.scripts.insert(
          id,
          ScriptEntry {
            node_id: node_id.clone(),
            base_url_at_discovery,
            kind: ScriptKind::Module,
            mode,
            ready: None,
            queued_for_execution: false,
          },
        );

        actions.push(HtmlScriptSchedulerAction::StartInlineModuleGraphFetch {
          script_id: id,
          node_id,
          source_text: element.inline_text.clone(),
          base_url,
          element,
        });
        return Ok(HtmlDiscoveredScript { id, actions });
      }
    }

    Ok(HtmlDiscoveredScript { id, actions })
  }

  /// Notify the scheduler that a previously requested classic external script fetch completed.
  pub fn classic_fetch_completed(
    &mut self,
    script_id: HtmlScriptId,
    source_text: String,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    self.classic_fetch_finished(script_id, Some(source_text))
  }

  /// Notify the scheduler that a previously requested classic external script fetch failed.
  pub fn classic_fetch_failed(
    &mut self,
    script_id: HtmlScriptId,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    self.classic_fetch_finished(script_id, None)
  }

  fn classic_fetch_finished(
    &mut self,
    script_id: HtmlScriptId,
    source_text: Option<String>,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    let Some(entry) = self.scripts.get_mut(&script_id) else {
      return Err(Error::Other(format!(
        "classic_fetch_completed called for unknown script_id={}",
        script_id.as_u64()
      )));
    };
    if entry.kind != ScriptKind::Classic {
      return Err(Error::Other(format!(
        "classic_fetch_completed called for non-classic script_id={}",
        script_id.as_u64()
      )));
    }
    if entry.ready.is_some() {
      return Err(Error::Other(format!(
        "classic_fetch_completed called more than once for script_id={}",
        script_id.as_u64()
      )));
    }

    entry.ready = Some(ReadyPayload::ClassicSource(source_text));

    match entry.mode {
      ScheduleMode::ParserBlocking => self.queue_blocking_if_ready(script_id),
      ScheduleMode::Async => self.queue_async_if_ready(script_id),
      ScheduleMode::OrderedAsap => self.queue_ordered_asap_if_ready(),
      ScheduleMode::PostParse => self.queue_post_parse_if_ready(),
    }
  }

  /// Notify the scheduler that a previously requested module graph fetch completed.
  pub fn module_graph_completed(
    &mut self,
    script_id: HtmlScriptId,
    module_source_text: String,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    self.module_graph_finished(script_id, Some(module_source_text))
  }

  /// Notify the scheduler that a previously requested module graph fetch failed.
  pub fn module_graph_failed(
    &mut self,
    script_id: HtmlScriptId,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    self.module_graph_finished(script_id, None)
  }

  fn module_graph_finished(
    &mut self,
    script_id: HtmlScriptId,
    module_source_text: Option<String>,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    let failed = module_source_text.is_none();
    let (node_id, mode) = {
      let Some(entry) = self.scripts.get_mut(&script_id) else {
        return Err(Error::Other(format!(
          "module_graph_completed called for unknown script_id={}",
          script_id.as_u64()
        )));
      };
      if entry.kind != ScriptKind::Module {
        return Err(Error::Other(format!(
          "module_graph_completed called for non-module script_id={}",
          script_id.as_u64()
        )));
      }
      if entry.ready.is_some() {
        return Err(Error::Other(format!(
          "module_graph_completed called more than once for script_id={}",
          script_id.as_u64()
        )));
      }

      entry.ready = Some(ReadyPayload::ModuleSource(module_source_text));
      // Module fetch failures should dispatch `error` as soon as the graph fetch completes,
      // regardless of whether the script would otherwise be deferred until parsing is complete.
      //
      // Mark the script as "queued" so ordered/deferred queues can advance past it.
      if failed {
        entry.queued_for_execution = true;
      }
      (entry.node_id.clone(), entry.mode)
    };

    if failed {
      let mut actions = vec![HtmlScriptSchedulerAction::QueueScriptEventTask {
        script_id,
        node_id,
        event: ScriptEventKind::Error,
      }];

      // Unblock any ordered script queues now that this script is considered completed.
      match mode {
        ScheduleMode::ParserBlocking => {
          // Module scripts never block the parser.
          debug_assert!(false, "module scripts should never be parser-blocking");
        }
        ScheduleMode::Async => {}
        ScheduleMode::OrderedAsap => {
          actions.extend(self.queue_ordered_asap_if_ready()?);
        }
        ScheduleMode::PostParse => {
          actions.extend(self.queue_post_parse_if_ready()?);
        }
      }
      return Ok(actions);
    }

    match mode {
      ScheduleMode::ParserBlocking => {
        // Module scripts never block the parser.
        debug_assert!(false, "module scripts should never be parser-blocking");
        self.queue_blocking_if_ready(script_id)
      }
      ScheduleMode::Async => self.queue_async_if_ready(script_id),
      ScheduleMode::OrderedAsap => self.queue_ordered_asap_if_ready(),
      ScheduleMode::PostParse => self.queue_post_parse_if_ready(),
    }
  }

  /// Notify the scheduler that HTML parsing has completed.
  pub fn parsing_completed(&mut self) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    self.parsing_completed = true;
    self.queue_post_parse_if_ready()
  }

  fn take_ready_work(entry: &mut ScriptEntry<NodeId>) -> Result<HtmlScriptWork> {
    let payload = entry.ready.take().ok_or_else(|| {
      Error::Other("internal error: script queued without ready payload".to_string())
    })?;

    Ok(match payload {
      ReadyPayload::ClassicSource(source_text) => HtmlScriptWork::Classic { source_text },
      ReadyPayload::ModuleSource(source_text) => HtmlScriptWork::Module { source_text },
    })
  }

  fn queue_blocking_if_ready(
    &mut self,
    script_id: HtmlScriptId,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    let Some(entry) = self.scripts.get_mut(&script_id) else {
      return Err(Error::Other(format!(
        "internal error: missing script entry for script_id={}",
        script_id.as_u64()
      )));
    };

    if entry.queued_for_execution {
      return Ok(Vec::new());
    }

    if entry.ready.is_none() {
      return Ok(Vec::new());
    }

    entry.queued_for_execution = true;
    let node_id = entry.node_id.clone();
    let work = Self::take_ready_work(entry)?;
    Ok(vec![HtmlScriptSchedulerAction::ExecuteNow {
      script_id,
      node_id,
      work,
    }])
  }

  fn queue_async_if_ready(
    &mut self,
    script_id: HtmlScriptId,
  ) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    let Some(entry) = self.scripts.get_mut(&script_id) else {
      return Err(Error::Other(format!(
        "internal error: missing script entry for script_id={}",
        script_id.as_u64()
      )));
    };

    if entry.queued_for_execution {
      return Ok(Vec::new());
    }

    if entry.ready.is_none() {
      return Ok(Vec::new());
    }

    entry.queued_for_execution = true;
    let node_id = entry.node_id.clone();
    let work = Self::take_ready_work(entry)?;
    Ok(vec![HtmlScriptSchedulerAction::QueueTask {
      script_id,
      node_id,
      work,
    }])
  }

  fn queue_ordered_asap_if_ready(&mut self) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    let mut actions: Vec<HtmlScriptSchedulerAction<NodeId>> = Vec::new();
    while self.next_ordered_asap_to_queue < self.ordered_asap.len() {
      let script_id = self.ordered_asap[self.next_ordered_asap_to_queue];
      let Some(entry) = self.scripts.get_mut(&script_id) else {
        return Err(Error::Other(format!(
          "internal error: ordered_asap references missing script_id={}",
          script_id.as_u64()
        )));
      };

      if entry.queued_for_execution {
        self.next_ordered_asap_to_queue += 1;
        continue;
      }

      if entry.ready.is_none() {
        break;
      }

      entry.queued_for_execution = true;
      let node_id = entry.node_id.clone();
      let work = Self::take_ready_work(entry)?;
      actions.push(HtmlScriptSchedulerAction::QueueTask {
        script_id,
        node_id,
        work,
      });
      self.next_ordered_asap_to_queue += 1;
    }
    Ok(actions)
  }

  fn queue_post_parse_if_ready(&mut self) -> Result<Vec<HtmlScriptSchedulerAction<NodeId>>> {
    if !self.parsing_completed {
      return Ok(Vec::new());
    }

    let mut actions: Vec<HtmlScriptSchedulerAction<NodeId>> = Vec::new();
    while self.next_post_parse_to_queue < self.post_parse.len() {
      let script_id = self.post_parse[self.next_post_parse_to_queue];
      let Some(entry) = self.scripts.get_mut(&script_id) else {
        return Err(Error::Other(format!(
          "internal error: post_parse references missing script_id={}",
          script_id.as_u64()
        )));
      };

      if entry.queued_for_execution {
        self.next_post_parse_to_queue += 1;
        continue;
      }

      if entry.ready.is_none() {
        break;
      }

      entry.queued_for_execution = true;
      let node_id = entry.node_id.clone();
      let work = Self::take_ready_work(entry)?;
      actions.push(HtmlScriptSchedulerAction::QueueTask {
        script_id,
        node_id,
        work,
      });
      self.next_post_parse_to_queue += 1;
    }
    Ok(actions)
  }
}

#[cfg(test)]
mod state_machine_tests {
  use super::*;
  use crate::js::{EventLoop, RunLimits, TaskSource};
  use std::collections::{HashMap, HashSet};

  #[derive(Default)]
  struct Host {
    log: Vec<String>,
  }

  fn execute_fake_work(
    host: &mut Host,
    event_loop: &mut EventLoop<Host>,
    work: &HtmlScriptWork,
  ) -> Result<()> {
    let label = match work {
      HtmlScriptWork::Classic { source_text } => {
        let body = source_text.as_deref().unwrap_or("<null>");
        format!("classic:{body}")
      }
      HtmlScriptWork::Module { source_text } => {
        let body = source_text.as_deref().unwrap_or("<null>");
        format!("module:{body}")
      }
      HtmlScriptWork::ImportMap { source_text, .. } => format!("importmap:{source_text}"),
    };

    host.log.push(label.clone());
    let micro = format!("microtask:{label}");
    event_loop.queue_microtask(move |host, _| {
      host.log.push(micro);
      Ok(())
    })?;
    Ok(())
  }

  fn classic_external(
    src: &str,
    async_attr: bool,
    defer_attr: bool,
    parser_inserted: bool,
  ) -> ScriptElementSpec {
    ScriptElementSpec {
      base_url: None,
      src: Some(src.to_string()),
      src_attr_present: true,
      inline_text: String::new(),
      async_attr,
      defer_attr,
      nomodule_attr: false,
      crossorigin: None,
      integrity_attr_present: false,
      integrity: None,
      referrer_policy: None,
      fetch_priority: None,
      parser_inserted,
      force_async: false,
      node_id: None,
      script_type: ScriptType::Classic,
    }
  }

  fn classic_inline(source: &str, nomodule_attr: bool) -> ScriptElementSpec {
    ScriptElementSpec {
      base_url: None,
      src: None,
      src_attr_present: false,
      inline_text: source.to_string(),
      async_attr: false,
      defer_attr: false,
      nomodule_attr,
      crossorigin: None,
      integrity_attr_present: false,
      integrity: None,
      referrer_policy: None,
      fetch_priority: None,
      parser_inserted: true,
      force_async: false,
      node_id: None,
      script_type: ScriptType::Classic,
    }
  }

  fn module_external(src: &str, async_attr: bool, parser_inserted: bool) -> ScriptElementSpec {
    ScriptElementSpec {
      base_url: None,
      src: Some(src.to_string()),
      src_attr_present: true,
      inline_text: String::new(),
      async_attr,
      defer_attr: false,
      nomodule_attr: false,
      crossorigin: None,
      integrity_attr_present: false,
      integrity: None,
      referrer_policy: None,
      fetch_priority: None,
      parser_inserted,
      force_async: false,
      node_id: None,
      script_type: ScriptType::Module,
    }
  }

  fn module_external_with_force_async(
    src: &str,
    async_attr: bool,
    force_async: bool,
    parser_inserted: bool,
  ) -> ScriptElementSpec {
    let mut spec = module_external(src, async_attr, parser_inserted);
    spec.force_async = force_async;
    spec
  }

  fn module_inline(source: &str, async_attr: bool, parser_inserted: bool) -> ScriptElementSpec {
    ScriptElementSpec {
      base_url: Some("https://example.com/".to_string()),
      src: None,
      src_attr_present: false,
      inline_text: source.to_string(),
      async_attr,
      defer_attr: false,
      nomodule_attr: false,
      crossorigin: None,
      integrity_attr_present: false,
      integrity: None,
      referrer_policy: None,
      fetch_priority: None,
      parser_inserted,
      force_async: false,
      node_id: None,
      script_type: ScriptType::Module,
    }
  }

  fn import_map_inline(source: &str) -> ScriptElementSpec {
    ScriptElementSpec {
      base_url: Some("https://example.com/".to_string()),
      src: None,
      src_attr_present: false,
      inline_text: source.to_string(),
      async_attr: false,
      defer_attr: false,
      nomodule_attr: false,
      crossorigin: None,
      integrity_attr_present: false,
      integrity: None,
      referrer_policy: None,
      fetch_priority: None,
      parser_inserted: true,
      force_async: false,
      node_id: None,
      script_type: ScriptType::ImportMap,
    }
  }

  struct Harness {
    scheduler: HtmlScriptScheduler<u32>,
    event_loop: EventLoop<Host>,
    host: Host,

    started_classic_fetches: Vec<(
      HtmlScriptId,
      u32,
      String,
      FetchDestination,
      FetchCredentialsMode,
    )>,
    started_module_fetches: Vec<(HtmlScriptId, u32, String, FetchDestination, usize)>,
    started_inline_module_fetches: Vec<(HtmlScriptId, u32, String, usize)>,

    import_map_version: usize,
  }

  impl Harness {
    fn new() -> Self {
      Self::new_with_modules_supported(true)
    }

    fn new_with_modules_supported(modules_supported: bool) -> Self {
      Self {
        scheduler: HtmlScriptScheduler::with_modules_supported(modules_supported),
        event_loop: EventLoop::new(),
        host: Host::default(),
        started_classic_fetches: Vec::new(),
        started_module_fetches: Vec::new(),
        started_inline_module_fetches: Vec::new(),
        import_map_version: 0,
      }
    }

    fn apply_actions(&mut self, actions: Vec<HtmlScriptSchedulerAction<u32>>) -> Result<()> {
      for action in actions {
        match action {
          HtmlScriptSchedulerAction::StartClassicFetch {
            script_id,
            node_id,
            url,
            destination,
            credentials_mode,
          } => {
            self.started_classic_fetches.push((
              script_id,
              node_id,
              url,
              destination,
              credentials_mode,
            ));
          }
          HtmlScriptSchedulerAction::StartModuleGraphFetch {
            script_id,
            node_id,
            url,
            destination,
            element: _,
          } => {
            self.started_module_fetches.push((
              script_id,
              node_id,
              url,
              destination,
              self.import_map_version,
            ));
          }
          HtmlScriptSchedulerAction::StartInlineModuleGraphFetch {
            script_id,
            node_id,
            source_text,
            base_url: _,
            element: _,
          } => {
            self.started_inline_module_fetches.push((
              script_id,
              node_id,
              source_text,
              self.import_map_version,
            ));
          }
          HtmlScriptSchedulerAction::BlockParserUntilExecuted { .. } => {
            // These state-machine tests do not model parser pausing; legacy `ScriptScheduler` tests
            // cover that contract. Here we focus on ordering decisions.
          }
          HtmlScriptSchedulerAction::ExecuteNow { work, .. } => {
            if matches!(&work, HtmlScriptWork::ImportMap { .. }) {
              self.import_map_version += 1;
            }
            execute_fake_work(&mut self.host, &mut self.event_loop, &work)?;
            self
              .event_loop
              .perform_microtask_checkpoint(&mut self.host)?;
          }
          HtmlScriptSchedulerAction::QueueTask { work, .. } => {
            if matches!(&work, HtmlScriptWork::ImportMap { .. }) {
              self.import_map_version += 1;
            }
            self
              .event_loop
              .queue_task(TaskSource::Script, move |host, event_loop| {
                execute_fake_work(host, event_loop, &work)
              })?;
          }
          HtmlScriptSchedulerAction::QueueScriptEventTask { event, .. } => {
            let name = match event {
              ScriptEventKind::Load => "load",
              ScriptEventKind::Error => "error",
            };
            self
              .event_loop
              .queue_task(TaskSource::DOMManipulation, move |host, _| {
                host.log.push(format!("event:{name}"));
                Ok(())
              })?;
          }
        }
      }
      Ok(())
    }

    fn discover(&mut self, element: ScriptElementSpec) -> Result<HtmlScriptId> {
      let discovered = self.scheduler.discovered_script(
        element, /* node_id */ 1, /* base_url_at_discovery */ None,
      )?;
      let id = discovered.id;
      self.apply_actions(discovered.actions)?;
      Ok(id)
    }

    fn classic_fetch_complete(&mut self, script_id: HtmlScriptId, source_text: &str) -> Result<()> {
      let actions = self
        .scheduler
        .classic_fetch_completed(script_id, source_text.to_string())?;
      self.apply_actions(actions)
    }

    fn module_graph_complete(&mut self, script_id: HtmlScriptId, source_text: &str) -> Result<()> {
      let actions = self
        .scheduler
        .module_graph_completed(script_id, source_text.to_string())?;
      self.apply_actions(actions)
    }

    fn parsing_completed(&mut self) -> Result<()> {
      let actions = self.scheduler.parsing_completed()?;
      self.apply_actions(actions)
    }

    fn run_event_loop(&mut self) -> Result<()> {
      self
        .event_loop
        .run_until_idle(&mut self.host, RunLimits::unbounded())?;
      Ok(())
    }
  }

  #[test]
  fn classic_fetch_completed_rejects_module_script_ids() -> Result<()> {
    let mut h = Harness::new();
    let module_id = h.discover(module_external(
      "m.js", /* async */ false, /* parser_inserted */ true,
    ))?;

    let err = h
      .scheduler
      .classic_fetch_completed(module_id, "console.log('x')".to_string())
      .expect_err("expected classic_fetch_completed to reject module script");
    assert!(
      err.to_string().contains("non-classic"),
      "unexpected error: {err}"
    );
    Ok(())
  }

  #[test]
  fn parser_inserted_deferred_module_scripts_execute_after_parsing_completed_in_order() -> Result<()>
  {
    let mut h = Harness::new();

    let m1 = h.discover(module_external(
      "m1.js", /* async */ false, /* parser_inserted */ true,
    ))?;
    let m2 = h.discover(module_external(
      "m2.js", /* async */ false, /* parser_inserted */ true,
    ))?;

    // Complete out-of-order before parsing completes.
    h.module_graph_complete(m2, "2")?;
    h.parsing_completed()?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      Vec::<String>::new(),
      "deferred module scripts must not run until prior scripts are ready"
    );

    h.module_graph_complete(m1, "1")?;
    h.run_event_loop()?;

    assert_eq!(
      h.host.log,
      vec![
        "module:1".to_string(),
        "microtask:module:1".to_string(),
        "module:2".to_string(),
        "microtask:module:2".to_string(),
      ]
    );
    Ok(())
  }

  #[test]
  fn async_module_script_queues_task_on_graph_ready_without_waiting_for_parsing_completed(
  ) -> Result<()> {
    let mut h = Harness::new();

    // A parser-inserted, non-async module script is deferred by default.
    let deferred = h.discover(module_external(
      "deferred.js",
      /* async */ false,
      /* parser_inserted */ true,
    ))?;

    // An async module script should run ASAP once its graph is ready, even before parsing completes.
    let async_id = h.discover(module_external(
      "async.js", /* async */ true, /* parser_inserted */ true,
    ))?;
    h.module_graph_complete(async_id, "9")?;
    h.run_event_loop()?;

    assert_eq!(
      h.host.log,
      vec!["module:9".to_string(), "microtask:module:9".to_string()]
    );

    // The deferred module script still must not run before parsing_completed.
    h.module_graph_complete(deferred, "1")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec!["module:9".to_string(), "microtask:module:9".to_string()]
    );

    h.parsing_completed()?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec![
        "module:9".to_string(),
        "microtask:module:9".to_string(),
        "module:1".to_string(),
        "microtask:module:1".to_string(),
      ]
    );
    Ok(())
  }

  #[test]
  fn dynamic_module_scripts_without_async_execute_in_insertion_order_asap() -> Result<()> {
    let mut h = Harness::new();

    let m1 = h.discover(module_external(
      "dyn1.js", /* async */ false, /* parser_inserted */ false,
    ))?;
    let m2 = h.discover(module_external(
      "dyn2.js", /* async */ false, /* parser_inserted */ false,
    ))?;

    // Complete out of order: m2 ready before m1.
    h.module_graph_complete(m2, "2")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      Vec::<String>::new(),
      "ordered-asap scripts must not run ahead of earlier scripts"
    );

    h.module_graph_complete(m1, "1")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec![
        "module:1".to_string(),
        "microtask:module:1".to_string(),
        "module:2".to_string(),
        "microtask:module:2".to_string(),
      ]
    );
    Ok(())
  }

  #[test]
  fn dynamic_module_scripts_with_force_async_true_execute_in_completion_order() -> Result<()> {
    let mut h = Harness::new();

    let m1 = h.discover(module_external_with_force_async(
      "dyn1.js", /* async */ false, /* force_async */ true,
      /* parser_inserted */ false,
    ))?;
    let m2 = h.discover(module_external_with_force_async(
      "dyn2.js", /* async */ false, /* force_async */ true,
      /* parser_inserted */ false,
    ))?;

    // Complete out of order: m2 ready before m1.
    h.module_graph_complete(m2, "2")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec!["module:2".to_string(), "microtask:module:2".to_string()],
      "async-like module scripts should run as soon as possible when ready"
    );

    h.module_graph_complete(m1, "1")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec![
        "module:2".to_string(),
        "microtask:module:2".to_string(),
        "module:1".to_string(),
        "microtask:module:1".to_string(),
      ]
    );
    Ok(())
  }

  #[test]
  fn dynamic_classic_external_without_async_executes_in_insertion_order_asap() -> Result<()> {
    let mut h = Harness::new();

    let c1 = h.discover(classic_external(
      "c1.js", /* async */ false, /* defer */ false, /* parser_inserted */ false,
    ))?;
    let c2 = h.discover(classic_external(
      "c2.js", /* async */ false, /* defer */ false, /* parser_inserted */ false,
    ))?;

    // Complete out of order: c2 finishes first.
    h.classic_fetch_complete(c2, "C2")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      Vec::<String>::new(),
      "ordered-asap classic scripts must not run ahead of earlier scripts"
    );

    h.classic_fetch_complete(c1, "C1")?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec![
        "classic:C1".to_string(),
        "microtask:classic:C1".to_string(),
        "classic:C2".to_string(),
        "microtask:classic:C2".to_string(),
      ]
    );
    Ok(())
  }

  #[test]
  fn import_map_executes_synchronously_at_discovery_and_is_visible_to_later_module_fetch(
  ) -> Result<()> {
    let mut h = Harness::new();

    // Import map must execute synchronously at discovery.
    let _map_id = h.discover(import_map_inline("{\"imports\":{}}"))?;
    assert_eq!(h.import_map_version, 1);
    assert_eq!(
      h.host.log,
      vec![
        "importmap:{\"imports\":{}}".to_string(),
        "microtask:importmap:{\"imports\":{}}".to_string(),
      ]
    );

    // A later module script should observe the updated import map state when starting its graph
    // fetch (represented here by our harness recording the version at StartInlineModuleGraphFetch).
    let _m = h.discover(module_inline(
      "export {}",
      /* async */ false,
      /* parser_inserted */ true,
    ))?;
    assert_eq!(h.started_inline_module_fetches.len(), 1);
    assert_eq!(h.started_inline_module_fetches[0].3, 1);
    Ok(())
  }

  #[test]
  fn script_fetch_actions_use_script_destinations() -> Result<()> {
    let mut h = Harness::new();

    let _classic = h.discover(classic_external(
      "classic.js",
      /* async */ false,
      /* defer */ false,
      /* parser_inserted */ true,
    ))?;
    assert_eq!(h.started_classic_fetches.len(), 1);
    assert_eq!(h.started_classic_fetches[0].3, FetchDestination::Script);
    assert_eq!(
      h.started_classic_fetches[0].4,
      FetchCredentialsMode::Include
    );

    let mut classic_cors = classic_external(
      "classic_cors.js",
      /* async */ false,
      /* defer */ false,
      /* parser_inserted */ true,
    );
    classic_cors.crossorigin = Some(crate::resource::CorsMode::Anonymous);
    let _classic_cors_id = h.discover(classic_cors)?;
    assert_eq!(h.started_classic_fetches.len(), 2);
    assert_eq!(h.started_classic_fetches[1].3, FetchDestination::ScriptCors);
    assert_eq!(
      h.started_classic_fetches[1].4,
      FetchCredentialsMode::SameOrigin
    );

    let mut classic_use_credentials = classic_external(
      "classic_use_credentials.js",
      /* async */ false,
      /* defer */ false,
      /* parser_inserted */ true,
    );
    classic_use_credentials.crossorigin = Some(crate::resource::CorsMode::UseCredentials);
    let _classic_use_credentials_id = h.discover(classic_use_credentials)?;
    assert_eq!(h.started_classic_fetches.len(), 3);
    assert_eq!(h.started_classic_fetches[2].3, FetchDestination::ScriptCors);
    assert_eq!(
      h.started_classic_fetches[2].4,
      FetchCredentialsMode::Include
    );

    let _module = h.discover(module_external(
      "mod.js", /* async */ false, /* parser_inserted */ true,
    ))?;
    assert_eq!(h.started_module_fetches.len(), 1);
    assert_eq!(h.started_module_fetches[0].3, FetchDestination::ScriptCors);
    Ok(())
  }

  #[test]
  fn nomodule_classic_script_is_ignored_when_modules_are_supported() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(true);
    h.discover(classic_inline("A", /* nomodule */ true))?;
    assert!(h.host.log.is_empty());
    Ok(())
  }

  #[test]
  fn nomodule_external_classic_script_does_not_start_fetch_when_modules_are_supported() -> Result<()>
  {
    let mut h = Harness::new_with_modules_supported(true);
    let mut spec = classic_external(
      "legacy.js",
      /* async */ false,
      /* defer */ false,
      /* parser_inserted */ true,
    );
    spec.nomodule_attr = true;
    h.discover(spec)?;
    assert!(
      h.started_classic_fetches.is_empty(),
      "expected no fetch to be started for nomodule classic scripts when modules are supported"
    );
    assert!(
      h.host.log.is_empty(),
      "expected nomodule classic scripts not to execute"
    );
    Ok(())
  }

  #[test]
  fn nomodule_classic_script_executes_when_modules_are_not_supported() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(false);
    h.discover(classic_inline("A", /* nomodule */ true))?;
    assert_eq!(
      h.host.log,
      vec!["classic:A".to_string(), "microtask:classic:A".to_string()]
    );
    Ok(())
  }

  #[test]
  fn module_scripts_are_ignored_when_modules_are_not_supported() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(false);
    h.discover(module_external(
      "m.js", /* async */ false, /* parser_inserted */ true,
    ))?;
    h.discover(module_inline(
      "export const x = 1;",
      /* async */ false,
      /* parser_inserted */ true,
    ))?;
    assert!(
      h.started_module_fetches.is_empty(),
      "module fetches must not start when modules are not supported"
    );
    assert!(
      h.started_inline_module_fetches.is_empty(),
      "inline module graph fetches must not start when modules are not supported"
    );
    assert!(h.host.log.is_empty(), "module scripts must not execute");
    Ok(())
  }

  #[test]
  fn importmap_scripts_are_ignored_when_modules_are_not_supported() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(false);
    h.discover(import_map_inline("{\"imports\":{}}"))?;
    assert_eq!(
      h.import_map_version, 0,
      "import maps must not be registered when modules are not supported"
    );
    assert!(h.host.log.is_empty(), "import maps must not execute");
    Ok(())
  }

  #[test]
  fn nomodule_external_classic_script_starts_fetch_when_modules_are_not_supported() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(false);
    let mut spec = classic_external(
      "legacy.js",
      /* async */ false,
      /* defer */ false,
      /* parser_inserted */ true,
    );
    spec.nomodule_attr = true;
    h.discover(spec)?;
    assert_eq!(
      h.started_classic_fetches.len(),
      1,
      "expected classic nomodule scripts to run normally when modules are not supported"
    );
    Ok(())
  }

  #[test]
  fn nomodule_does_not_block_module_scripts() -> Result<()> {
    let mut h = Harness::new_with_modules_supported(true);
    let mut spec = module_external(
      "mod.js", /* async */ false, /* parser_inserted */ true,
    );
    spec.nomodule_attr = true;
    let id = h.discover(spec)?;
    assert_eq!(
      h.started_module_fetches.len(),
      1,
      "expected module graph fetch to start even when `nomodule` is present"
    );
    h.module_graph_complete(id, "M")?;
    h.parsing_completed()?;
    h.run_event_loop()?;
    assert_eq!(
      h.host.log,
      vec!["module:M".to_string(), "microtask:module:M".to_string()]
    );
    Ok(())
  }

  #[test]
  fn empty_inline_classic_script_is_noop() -> Result<()> {
    let mut h = Harness::new();
    let discovered = h.scheduler.discovered_script(
      classic_inline("", /* nomodule */ false),
      /* node_id */ 1,
      /* base_url_at_discovery */ None,
    )?;
    assert!(discovered.actions.is_empty());
    h.apply_actions(discovered.actions)?;
    h.run_event_loop()?;
    assert!(h.host.log.is_empty());
    Ok(())
  }

  #[test]
  fn empty_inline_module_script_is_noop() -> Result<()> {
    let mut h = Harness::new();
    let discovered = h.scheduler.discovered_script(
      module_inline("", /* async */ false, /* parser_inserted */ true),
      /* node_id */ 1,
      /* base_url_at_discovery */ None,
    )?;
    assert!(discovered.actions.is_empty());
    h.apply_actions(discovered.actions)?;
    h.run_event_loop()?;
    assert!(h.started_inline_module_fetches.is_empty());
    assert!(h.host.log.is_empty());
    Ok(())
  }

  #[test]
  fn empty_inline_importmap_script_is_noop() -> Result<()> {
    let mut h = Harness::new();
    let discovered = h.scheduler.discovered_script(
      import_map_inline(""),
      /* node_id */ 1,
      /* base_url_at_discovery */ None,
    )?;
    assert!(discovered.actions.is_empty());
    h.apply_actions(discovered.actions)?;
    h.run_event_loop()?;
    assert_eq!(h.import_map_version, 0);
    assert!(h.host.log.is_empty());
    Ok(())
  }

  // ---------------------------------------------------------------------------
  // Randomized stress tests for ordering invariants.
  // ---------------------------------------------------------------------------

  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  enum ExpectedMode {
    ImmediateExecuteNow,
    ImmediateQueueTask,
    ParserBlocking,
    Async,
    OrderedAsap,
    PostParse,
  }

  #[derive(Debug, Clone)]
  struct ScriptMeta {
    kind: ScriptType,
    mode: ExpectedMode,
    parser_inserted: bool,
    external: bool,
  }

  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  enum WorkActionKind {
    ExecuteNow,
    QueueTask,
  }

  #[derive(Debug, Clone)]
  struct WorkRecord {
    step: usize,
    action: WorkActionKind,
    script_id: HtmlScriptId,
    work: HtmlScriptWork,
  }

  fn make_classic_external_with_force_async(
    src: &str,
    async_attr: bool,
    defer_attr: bool,
    parser_inserted: bool,
    force_async: bool,
  ) -> ScriptElementSpec {
    let mut spec = classic_external(src, async_attr, defer_attr, parser_inserted);
    spec.force_async = force_async;
    spec
  }

  fn make_module_external_with_force_async(
    src: &str,
    async_attr: bool,
    parser_inserted: bool,
    force_async: bool,
  ) -> ScriptElementSpec {
    let mut spec = module_external(src, async_attr, parser_inserted);
    spec.force_async = force_async;
    spec
  }

  fn make_import_map_inline_with_parser_inserted(source: &str, parser_inserted: bool) -> ScriptElementSpec {
    let mut spec = import_map_inline(source);
    spec.parser_inserted = parser_inserted;
    spec
  }

  fn expected_mode_for_spec(spec: &ScriptElementSpec) -> ExpectedMode {
    match spec.script_type {
      ScriptType::Classic => {
        if !spec.src_attr_present {
          return ExpectedMode::ImmediateExecuteNow;
        }
        let is_async = spec.async_attr || spec.force_async;
        if spec.parser_inserted && !is_async && !spec.defer_attr {
          ExpectedMode::ParserBlocking
        } else if is_async {
          ExpectedMode::Async
        } else if spec.parser_inserted {
          ExpectedMode::PostParse
        } else {
          ExpectedMode::OrderedAsap
        }
      }
      ScriptType::Module => {
        let is_async = spec.async_attr || spec.force_async;
        if is_async {
          ExpectedMode::Async
        } else if spec.parser_inserted {
          ExpectedMode::PostParse
        } else {
          ExpectedMode::OrderedAsap
        }
      }
      ScriptType::ImportMap => {
        if spec.parser_inserted {
          ExpectedMode::ImmediateExecuteNow
        } else {
          ExpectedMode::ImmediateQueueTask
        }
      }
      ScriptType::Unknown => ExpectedMode::ImmediateExecuteNow,
    }
  }

  struct StressHarness {
    scheduler: HtmlScriptScheduler<u32>,
    next_node_id: u32,

    // Global state for validating parser-blocking behavior.
    parser_blocked_on: Option<HtmlScriptId>,

    parsing_completed_step: Option<usize>,

    // Metadata/expectations.
    meta: HashMap<HtmlScriptId, ScriptMeta>,

    // Ordering lists in discovery order.
    ordered_asap: Vec<HtmlScriptId>,
    ordered_asap_idx: HashMap<HtmlScriptId, usize>,
    post_parse: Vec<HtmlScriptId>,
    post_parse_idx: HashMap<HtmlScriptId, usize>,

    // Completion tracking for ordered lists: "completed" means either:
    // - a work action was emitted (success or classic failure), or
    // - a module failure was emitted via QueueScriptEventTask.
    ordered_asap_completed: HashSet<HtmlScriptId>,
    post_parse_completed: HashSet<HtmlScriptId>,

    // Pending fetches to drive completion events.
    pending_classic_fetches: Vec<HtmlScriptId>,
    pending_module_fetches: Vec<HtmlScriptId>,
    classic_fetch_outcome: HashMap<HtmlScriptId, bool>,
    module_fetch_outcome: HashMap<HtmlScriptId, bool>,

    // Logs for assertions.
    seen_work_action: HashSet<HtmlScriptId>,
    executed: HashSet<HtmlScriptId>,
    module_failed: HashSet<HtmlScriptId>,
    work_log: Vec<WorkRecord>,
  }

  impl StressHarness {
    fn new() -> Self {
      Self {
        scheduler: HtmlScriptScheduler::new(),
        next_node_id: 1,
        parser_blocked_on: None,
        parsing_completed_step: None,
        meta: HashMap::new(),
        ordered_asap: Vec::new(),
        ordered_asap_idx: HashMap::new(),
        post_parse: Vec::new(),
        post_parse_idx: HashMap::new(),
        ordered_asap_completed: HashSet::new(),
        post_parse_completed: HashSet::new(),
        pending_classic_fetches: Vec::new(),
        pending_module_fetches: Vec::new(),
        classic_fetch_outcome: HashMap::new(),
        module_fetch_outcome: HashMap::new(),
        seen_work_action: HashSet::new(),
        executed: HashSet::new(),
        module_failed: HashSet::new(),
        work_log: Vec::new(),
      }
    }

    fn discover(&mut self, spec: ScriptElementSpec, step: usize) -> Result<HtmlScriptId> {
      let node_id = self.next_node_id;
      self.next_node_id += 1;

      let mode = expected_mode_for_spec(&spec);
      let meta = ScriptMeta {
        kind: spec.script_type,
        mode,
        parser_inserted: spec.parser_inserted,
        external: spec.src_attr_present,
      };

      let discovered = if spec.parser_inserted {
        // Exercise the parser-specific API as well.
        self
          .scheduler
          .discovered_parser_script(spec, node_id, /* base_url_at_discovery */ None)?
      } else {
        self
          .scheduler
          .discovered_script(spec, node_id, /* base_url_at_discovery */ None)?
      };
      let id = discovered.id;
      self.meta.insert(id, meta);

      // Record membership in ordering lists based on expected scheduling mode.
      match mode {
        ExpectedMode::OrderedAsap => {
          let idx = self.ordered_asap.len();
          self.ordered_asap.push(id);
          self.ordered_asap_idx.insert(id, idx);
        }
        ExpectedMode::PostParse => {
          let idx = self.post_parse.len();
          self.post_parse.push(id);
          self.post_parse_idx.insert(id, idx);
        }
        _ => {}
      }

      self.apply_actions(discovered.actions, step)?;
      Ok(id)
    }

    fn complete_classic_fetch(&mut self, id: HtmlScriptId, success: bool, step: usize) -> Result<()> {
      assert!(
        self.classic_fetch_outcome.insert(id, success).is_none(),
        "classic fetch completed twice for script_id={}",
        id.as_u64()
      );
      let actions = if success {
        self
          .scheduler
          .classic_fetch_completed(id, format!("classic:{}", id.as_u64()))?
      } else {
        self.scheduler.classic_fetch_failed(id)?
      };
      self.apply_actions(actions, step)
    }

    fn complete_module_graph(&mut self, id: HtmlScriptId, success: bool, step: usize) -> Result<()> {
      assert!(
        self.module_fetch_outcome.insert(id, success).is_none(),
        "module graph completed twice for script_id={}",
        id.as_u64()
      );
      let actions = if success {
        self
          .scheduler
          .module_graph_completed(id, format!("module:{}", id.as_u64()))?
      } else {
        self.scheduler.module_graph_failed(id)?
      };
      self.apply_actions(actions, step)
    }

    fn parsing_completed(&mut self, step: usize) -> Result<()> {
      if self.parsing_completed_step.is_none() {
        self.parsing_completed_step = Some(step);
      }
      let actions = self.scheduler.parsing_completed()?;
      self.apply_actions(actions, step)
    }

    fn apply_actions(&mut self, actions: Vec<HtmlScriptSchedulerAction<u32>>, step: usize) -> Result<()> {
      for action in actions {
        match action {
          HtmlScriptSchedulerAction::StartClassicFetch { script_id, .. } => {
            self.pending_classic_fetches.push(script_id);
          }
          HtmlScriptSchedulerAction::StartModuleGraphFetch { script_id, .. }
          | HtmlScriptSchedulerAction::StartInlineModuleGraphFetch { script_id, .. } => {
            self.pending_module_fetches.push(script_id);
          }
          HtmlScriptSchedulerAction::BlockParserUntilExecuted { script_id, .. } => {
            assert!(
              self.parser_blocked_on.is_none(),
              "attempted to block parser twice (existing={:?}, new={})",
              self.parser_blocked_on,
              script_id.as_u64()
            );
            let meta = self
              .meta
              .get(&script_id)
              .unwrap_or_else(|| panic!("missing meta for blocked script_id={}", script_id.as_u64()));
            assert_eq!(
              meta.mode,
              ExpectedMode::ParserBlocking,
              "BlockParserUntilExecuted must only be emitted for parser-blocking classic scripts"
            );
            assert_eq!(meta.kind, ScriptType::Classic);
            self.parser_blocked_on = Some(script_id);
          }
          HtmlScriptSchedulerAction::ExecuteNow {
            script_id, work, ..
          } => {
            self.on_work_action(step, WorkActionKind::ExecuteNow, script_id, work);
          }
          HtmlScriptSchedulerAction::QueueTask {
            script_id, work, ..
          } => {
            self.on_work_action(step, WorkActionKind::QueueTask, script_id, work);
          }
          HtmlScriptSchedulerAction::QueueScriptEventTask {
            script_id, event, ..
          } => {
            if event == ScriptEventKind::Error {
              if let Some(meta) = self.meta.get(&script_id) {
                if meta.kind == ScriptType::Module {
                  // Module graph failure completion. This is intentionally dispatched ASAP and can
                  // happen even for deferred scripts; treat it as completing the script so ordered
                  // queues can advance.
                  self.module_failed.insert(script_id);
                  if meta.mode == ExpectedMode::OrderedAsap {
                    self.ordered_asap_completed.insert(script_id);
                  }
                  if meta.mode == ExpectedMode::PostParse {
                    self.post_parse_completed.insert(script_id);
                  }
                }
              }
            }
          }
        }
      }
      Ok(())
    }

    fn on_work_action(&mut self, step: usize, kind: WorkActionKind, script_id: HtmlScriptId, work: HtmlScriptWork) {
      assert!(
        self.seen_work_action.insert(script_id),
        "script_id={} scheduled for work more than once (step={step})",
        script_id.as_u64()
      );

      let meta = self
        .meta
        .get(&script_id)
        .unwrap_or_else(|| panic!("missing meta for script_id={}", script_id.as_u64()));

      // Validate that the scheduler chose the expected execution mechanism for this script.
      match meta.mode {
        ExpectedMode::ImmediateExecuteNow => {
          assert_eq!(
            kind,
            WorkActionKind::ExecuteNow,
            "expected ExecuteNow for script_id={} mode={:?} (step={step})",
            script_id.as_u64(),
            meta.mode
          );
        }
        ExpectedMode::ImmediateQueueTask => {
          assert_eq!(
            kind,
            WorkActionKind::QueueTask,
            "expected QueueTask for script_id={} mode={:?} (step={step})",
            script_id.as_u64(),
            meta.mode
          );
        }
        ExpectedMode::ParserBlocking => {
          assert_eq!(
            kind,
            WorkActionKind::ExecuteNow,
            "parser-blocking scripts must ExecuteNow (script_id={}, step={step})",
            script_id.as_u64()
          );
        }
        ExpectedMode::Async | ExpectedMode::OrderedAsap | ExpectedMode::PostParse => {
          assert_eq!(
            kind,
            WorkActionKind::QueueTask,
            "non-blocking scripts must QueueTask (script_id={}, mode={:?}, step={step})",
            script_id.as_u64(),
            meta.mode
          );
        }
      }

      // Validate work kind matches script kind (import maps are only work items; they are not tracked
      // in ordered queues).
      match (&work, meta.kind) {
        (HtmlScriptWork::Classic { .. }, ScriptType::Classic)
        | (HtmlScriptWork::Module { .. }, ScriptType::Module)
        | (HtmlScriptWork::ImportMap { .. }, ScriptType::ImportMap) => {}
        _ => panic!(
          "work kind mismatch for script_id={} meta.kind={:?} work={:?}",
          script_id.as_u64(),
          meta.kind,
          work
        ),
      }

      // A script must never execute more than once.
      let source_present = match &work {
        HtmlScriptWork::Classic { source_text } => source_text.is_some(),
        HtmlScriptWork::Module { source_text } => source_text.is_some(),
        HtmlScriptWork::ImportMap { .. } => true,
      };
      if source_present {
        assert!(
          self.executed.insert(script_id),
          "script_id={} executed more than once (step={step})",
          script_id.as_u64()
        );
      }

      // Parser-blocking scripts must not "unblock" until the work action fires (success or error).
      if meta.mode == ExpectedMode::ParserBlocking {
        assert_eq!(
          self.parser_blocked_on,
          Some(script_id),
          "parser-blocking work must correspond to the currently blocked script_id={} (blocked_on={:?}, step={step})",
          script_id.as_u64(),
          self.parser_blocked_on
        );
        self.parser_blocked_on = None;
      }

      // Post-parse scripts must not be queued before parsing completes.
      if meta.mode == ExpectedMode::PostParse {
        assert!(
          self.parsing_completed_step.is_some(),
          "post-parse work queued before parsing_completed (script_id={}, step={step})",
          script_id.as_u64()
        );
      }

      // Ordering invariants:
      // - ordered-asap scripts may only be queued once all earlier ordered-asap scripts have
      //   completed (executed or errored).
      // - post-parse scripts may only be queued once all earlier post-parse scripts have completed
      //   (including module failures that were reported early).
      match meta.mode {
        ExpectedMode::OrderedAsap => {
          let idx = *self.ordered_asap_idx.get(&script_id).unwrap();
          for prior in &self.ordered_asap[..idx] {
            assert!(
              self.ordered_asap_completed.contains(prior),
              "ordered-asap script_id={} queued before earlier script_id={} completed (step={step})",
              script_id.as_u64(),
              prior.as_u64()
            );
          }
          self.ordered_asap_completed.insert(script_id);
        }
        ExpectedMode::PostParse => {
          let idx = *self.post_parse_idx.get(&script_id).unwrap();
          for prior in &self.post_parse[..idx] {
            assert!(
              self.post_parse_completed.contains(prior),
              "post-parse script_id={} queued before earlier script_id={} completed (step={step})",
              script_id.as_u64(),
              prior.as_u64()
            );
          }
          self.post_parse_completed.insert(script_id);
        }
        _ => {}
      }

      self.work_log.push(WorkRecord {
        step,
        action: kind,
        script_id,
        work,
      });
    }
  }

  #[test]
  fn randomized_state_machine_stress_ordering_invariants() -> Result<()> {
    use rand::{Rng, SeedableRng};
    use rand_chacha::ChaCha8Rng;

    // Multiple seeds to cover a variety of interleavings, while remaining fully deterministic.
    for seed in [1_u64, 2, 3, 4, 5] {
      let mut rng = ChaCha8Rng::seed_from_u64(seed);
      let mut h = StressHarness::new();

      // Pre-seed with a baseline mix to guarantee coverage even if the RNG happens to skew.
      let mut parser_specs: Vec<ScriptElementSpec> = vec![
        // Classic defer (post-parse, document order).
        classic_external(
          "p_defer_classic.js",
          /* async */ false,
          /* defer */ true,
          /* parser_inserted */ true,
        ),
        // Non-async module (post-parse by default).
        module_external("p_defer_mod.js", /* async */ false, /* parser_inserted */ true),
        // Import map (sync at discovery when parser-inserted).
        import_map_inline("{\"imports\":{}}"),
        // Async classic script.
        classic_external(
          "p_async_classic.js",
          /* async */ true,
          /* defer */ false,
          /* parser_inserted */ true,
        ),
        // Parser-blocking classic script.
        classic_external(
          "p_blocking.js",
          /* async */ false,
          /* defer */ false,
          /* parser_inserted */ true,
        ),
        // Inline module script (post-parse when non-async and parser inserted).
        module_inline(
          "export const x = 1;",
          /* async */ false,
          /* parser_inserted */ true,
        ),
      ];

      let mut dynamic_specs: Vec<ScriptElementSpec> = vec![
        // Ordered-asap dynamic classic.
        classic_external(
          "d_ordered_classic.js",
          /* async */ false,
          /* defer */ false,
          /* parser_inserted */ false,
        ),
        // Ordered-asap dynamic module.
        module_external("d_ordered_mod.js", /* async */ false, /* parser_inserted */ false),
        // Async-like dynamic classic via force_async.
        make_classic_external_with_force_async(
          "d_force_async_classic.js",
          /* async_attr */ false,
          /* defer_attr */ false,
          /* parser_inserted */ false,
          /* force_async */ true,
        ),
        // Async module.
        make_module_external_with_force_async(
          "d_async_mod.js",
          /* async_attr */ true,
          /* parser_inserted */ false,
          /* force_async */ false,
        ),
        // Dynamically inserted import map (queued task).
        make_import_map_inline_with_parser_inserted("{\"imports\":{\"x\":\"./x.js\"}}", false),
        // Inline dynamic module (ordered-asap when non-async).
        module_inline(
          "export const y = 2;",
          /* async */ false,
          /* parser_inserted */ false,
        ),
      ];

      // Add a randomized tail to shake out edge cases.
      const EXTRA_PARSER: usize = 12;
      const EXTRA_DYNAMIC: usize = 12;

      for i in 0..EXTRA_PARSER {
        let roll = rng.gen_range(0..100);
        let spec = if roll < 55 {
          // Classic external, with parser-blocking/defer/async variants.
          let variant = rng.gen_range(0..3);
          let (async_attr, defer_attr) = match variant {
            0 => (false, false), // parser-blocking
            1 => (false, true),  // defer
            _ => (true, false),  // async
          };
          classic_external(
            &format!("p_rand_classic_{i}.js"),
            async_attr,
            defer_attr,
            /* parser_inserted */ true,
          )
        } else if roll < 85 {
          // Module (external or inline).
          let async_attr = rng.gen_range(0..4) == 0;
          if rng.gen_range(0..2) == 0 {
            make_module_external_with_force_async(
              &format!("p_rand_mod_{i}.js"),
              async_attr,
              /* parser_inserted */ true,
              /* force_async */ false,
            )
          } else {
            module_inline(
              &format!("export const p{i} = {i};"),
              async_attr,
              /* parser_inserted */ true,
            )
          }
        } else {
          import_map_inline(&format!("{{\"imports\":{{\"p{i}\":\"./p{i}.js\"}}}}"))
        };
        parser_specs.push(spec);
      }

      for i in 0..EXTRA_DYNAMIC {
        let roll = rng.gen_range(0..100);
        let spec = if roll < 55 {
          // Dynamic classic external.
          let ordered = rng.gen_range(0..2) == 0;
          if ordered {
            classic_external(
              &format!("d_rand_ordered_classic_{i}.js"),
              /* async */ false,
              /* defer */ rng.gen_range(0..2) == 0,
              /* parser_inserted */ false,
            )
          } else {
            make_classic_external_with_force_async(
              &format!("d_rand_async_classic_{i}.js"),
              /* async_attr */ rng.gen_range(0..2) == 0,
              /* defer_attr */ false,
              /* parser_inserted */ false,
              /* force_async */ true,
            )
          }
        } else if roll < 90 {
          // Dynamic module.
          let ordered = rng.gen_range(0..2) == 0;
          let async_attr = !ordered && rng.gen_range(0..2) == 0;
          let force_async = !ordered && !async_attr && rng.gen_range(0..2) == 0;
          if rng.gen_range(0..2) == 0 {
            make_module_external_with_force_async(
              &format!("d_rand_mod_{i}.js"),
              async_attr,
              /* parser_inserted */ false,
              force_async,
            )
          } else {
            let mut spec = module_inline(
              &format!("export const d{i} = {i};"),
              async_attr,
              /* parser_inserted */ false,
            );
            spec.force_async = force_async;
            spec
          }
        } else {
          make_import_map_inline_with_parser_inserted(
            &format!("{{\"imports\":{{\"d{i}\":\"./d{i}.js\"}}}}"),
            false,
          )
        };
        dynamic_specs.push(spec);
      }

      let mut next_parser = 0usize;
      let mut next_dynamic = 0usize;
      let mut parsing_completed = false;

      // Drive a randomized interleaving of discovery and fetch completions.
      // This is intentionally not a perfect HTML model; it's meant to stress the scheduler's
      // state machine without using full DOM parsing.
      const MAX_STEPS: usize = 4096;
      for step in 0..MAX_STEPS {
        // Termination: all scripts discovered, parsing completed, and all fetches finished.
        if parsing_completed
          && next_parser >= parser_specs.len()
          && next_dynamic >= dynamic_specs.len()
          && h.pending_classic_fetches.is_empty()
          && h.pending_module_fetches.is_empty()
        {
          break;
        }

        let mut choices: Vec<&'static str> = Vec::new();
        if !parsing_completed && h.parser_blocked_on.is_none() && next_parser < parser_specs.len()
        {
          choices.push("discover_parser");
        }
        if next_dynamic < dynamic_specs.len() {
          choices.push("discover_dynamic");
        }
        if !h.pending_classic_fetches.is_empty() {
          choices.push("complete_classic");
        }
        if !h.pending_module_fetches.is_empty() {
          choices.push("complete_module");
        }
        if !parsing_completed
          && next_parser >= parser_specs.len()
          && h.parser_blocked_on.is_none()
        {
          choices.push("parsing_completed");
        }

        assert!(
          !choices.is_empty(),
          "deadlock in stress harness (seed={seed})"
        );

        let choice = choices[rng.gen_range(0..choices.len())];
        match choice {
          "discover_parser" => {
            let spec = parser_specs[next_parser].clone();
            next_parser += 1;
            let _ = h.discover(spec, step)?;
          }
          "discover_dynamic" => {
            let spec = dynamic_specs[next_dynamic].clone();
            next_dynamic += 1;
            let _ = h.discover(spec, step)?;
          }
          "complete_classic" => {
            let idx = rng.gen_range(0..h.pending_classic_fetches.len());
            let id = h.pending_classic_fetches.swap_remove(idx);
            let success = rng.gen_range(0..5) != 0; // ~80% success.
            h.complete_classic_fetch(id, success, step)?;
          }
          "complete_module" => {
            let idx = rng.gen_range(0..h.pending_module_fetches.len());
            let id = h.pending_module_fetches.swap_remove(idx);
            let success = rng.gen_range(0..5) != 0; // ~80% success.
            h.complete_module_graph(id, success, step)?;
          }
          "parsing_completed" => {
            parsing_completed = true;
            h.parsing_completed(step)?;
          }
          other => panic!("unexpected choice: {other}"),
        }

        if step == MAX_STEPS - 1 {
          panic!("stress test exceeded max steps (seed={seed})");
        }
      }

      assert!(
        h.parser_blocked_on.is_none(),
        "parser remained blocked at end of run (seed={seed})"
      );

      // Every completed classic fetch must result in exactly one work action (success or failure).
      for (&id, _) in &h.classic_fetch_outcome {
        assert!(
          h.seen_work_action.contains(&id),
          "classic script_id={} fetch finished but no work action was emitted (seed={seed})",
          id.as_u64()
        );
      }

      // Every completed module graph fetch must either:
      // - succeed and emit exactly one work action, or
      // - fail and emit exactly one error event task (with no work action).
      for (&id, &success) in &h.module_fetch_outcome {
        if success {
          assert!(
            h.seen_work_action.contains(&id),
            "module script_id={} graph fetch succeeded but no work action was emitted (seed={seed})",
            id.as_u64()
          );
          assert!(
            !h.module_failed.contains(&id),
            "module script_id={} graph fetch succeeded but error event was emitted (seed={seed})",
            id.as_u64()
          );
        } else {
          assert!(
            h.module_failed.contains(&id),
            "module script_id={} graph fetch failed but no error event was emitted (seed={seed})",
            id.as_u64()
          );
          assert!(
            !h.seen_work_action.contains(&id),
            "module script_id={} graph fetch failed but a work action was emitted (seed={seed})",
            id.as_u64()
          );
        }
      }

      for (&id, meta) in &h.meta {
        match meta.kind {
          ScriptType::Classic => {
            if meta.external {
              assert!(
                h.classic_fetch_outcome.contains_key(&id),
                "classic external script_id={} missing fetch completion (seed={seed})",
                id.as_u64()
              );
            } else {
              assert!(
                h.seen_work_action.contains(&id),
                "classic inline script_id={} missing ExecuteNow action (seed={seed})",
                id.as_u64()
              );
            }
          }
          ScriptType::Module => {
            assert!(
              h.module_fetch_outcome.contains_key(&id),
              "module script_id={} missing module graph completion (seed={seed})",
              id.as_u64()
            );
          }
          ScriptType::ImportMap => {
            assert!(
              h.seen_work_action.contains(&id),
              "importmap script_id={} missing work action (seed={seed})",
              id.as_u64()
            );
          }
          ScriptType::Unknown => {}
        }
      }

      // Validate classic defer ordering invariant (document order after parsing complete).
      let parsing_step = h
        .parsing_completed_step
        .unwrap_or_else(|| panic!("missing parsing_completed_step (seed={seed})"));
      let defer_classic_ids: Vec<HtmlScriptId> = h
        .post_parse
        .iter()
        .copied()
        .filter(|id| h.meta.get(id).is_some_and(|m| m.kind == ScriptType::Classic))
        .collect();
      let defer_classic_work: Vec<(HtmlScriptId, usize)> = h
        .work_log
        .iter()
        .filter_map(|rec| {
          let meta = h.meta.get(&rec.script_id)?;
          if meta.kind != ScriptType::Classic || meta.mode != ExpectedMode::PostParse {
            return None;
          }
          Some((rec.script_id, rec.step))
        })
        .collect();
      // Ensure all deferred classic work actions are after parsing completion.
      for (id, step) in &defer_classic_work {
        assert!(
          *step >= parsing_step,
          "defer classic script_id={} queued before parsing_completed (queued_at={step}, parsing_completed_at={parsing_step}, seed={seed})",
          id.as_u64()
        );
      }
      // Ensure they are queued in document order (relative order of the post-parse list).
      let mut expected_idx = 0usize;
      for (id, _step) in &defer_classic_work {
        while expected_idx < defer_classic_ids.len() && defer_classic_ids[expected_idx] != *id {
          expected_idx += 1;
        }
        assert!(
          expected_idx < defer_classic_ids.len(),
          "defer classic script_id={} not found in expected document order list (seed={seed})",
          id.as_u64()
        );
        expected_idx += 1;
      }

      // Validate ordered-asap invariant: scripts that execute as "ordered as soon as possible"
      // cannot be queued until all earlier ordered-asap scripts have completed.
      let ordered_asap_work: Vec<HtmlScriptId> = h
        .work_log
        .iter()
        .filter_map(|rec| {
          let meta = h.meta.get(&rec.script_id)?;
          (meta.mode == ExpectedMode::OrderedAsap).then_some(rec.script_id)
        })
        .collect();
      let mut expected_idx = 0usize;
      for id in ordered_asap_work {
        while expected_idx < h.ordered_asap.len() && h.ordered_asap[expected_idx] != id {
          expected_idx += 1;
        }
        assert!(
          expected_idx < h.ordered_asap.len(),
          "ordered-asap script_id={} not found in insertion-order list (seed={seed})",
          id.as_u64()
        );
        expected_idx += 1;
      }

      // Validate non-async module scripts: parser-inserted non-async modules behave as deferred
      // (post-parse) and preserve ordering.
      let deferred_module_exec: Vec<(HtmlScriptId, usize)> = h
        .work_log
        .iter()
        .filter_map(|rec| {
          let meta = h.meta.get(&rec.script_id)?;
          if meta.kind != ScriptType::Module || meta.mode != ExpectedMode::PostParse {
            return None;
          }
          let executed = matches!(
            &rec.work,
            HtmlScriptWork::Module {
              source_text: Some(_)
            }
          );
          executed.then_some((rec.script_id, rec.step))
        })
        .collect();
      for (id, step) in &deferred_module_exec {
        assert!(
          *step >= parsing_step,
          "deferred module script_id={} queued before parsing_completed (queued_at={step}, parsing_completed_at={parsing_step}, seed={seed})",
          id.as_u64()
        );
      }

      // Sanity: every script that was scheduled to run (ExecuteNow or QueueTask) should appear only
      // once, and every execution (source present) should be unique.
      assert_eq!(
        h.seen_work_action.len(),
        h.work_log.len(),
        "work action log contains duplicate script_ids (seed={seed})"
      );
    }
    Ok(())
  }
}
