//! Tree module tests

mod box_generation_ad_placeholders;
mod box_generation_blockification;
mod box_generation_onenav;
mod box_generation_whitespace_items;
mod container_query_box_generation_options;
mod form_controls_appearance_none_fallback;
mod select_control_option_dom_ids;
mod svg_intrinsic_size;
mod svg_root_transform_neutralization;
mod svg_transform_override;
mod svg_transform_presentation_attributes;
mod svg_transform_serialization;
mod test_anonymous_boxes;
