//! Canonical toolkit-agnostic renderer-chrome runtime for the browser chrome frame.
//!
//! This runtime renders the HTML generated by [`chrome_frame_html_from_state`](super::chrome_frame_html_from_state)
//! using [`BrowserDocument`] (dom1, no JS/event loop) and an allowlisted, trusted resource fetcher.
//!
//! User interaction is handled by [`InteractionEngine`]. Any resulting navigations to `chrome-action:`
//! URLs are intercepted and surfaced as [`ChromeAction`] values instead of navigating the chrome
//! document.

use crate::dom::DomNode;
use crate::geometry::Point;
use crate::interaction::dom_index::DomIndex;
use crate::interaction::{fragment_tree_with_scroll, InteractionAction, InteractionEngine, KeyAction};
use crate::ui::browser_app::BrowserAppState;
use crate::ui::chrome_action_url::ChromeActionUrl;
use crate::ui::chrome_assets::ChromeAssetsFetcher;
use crate::ui::chrome_dynamic_asset_fetcher::ChromeDynamicAssetFetcher;
use crate::ui::trusted_chrome_fetcher::TrustedChromeFetcher;
use crate::ui::{ChromeAction, PointerButton, PointerModifiers};
use crate::{BrowserDocument, Error, FastRender, RenderOptions, Result};
use std::sync::Arc;

use super::chrome_frame_html_from_state;
use super::{ChromeFrameEvent, CHROME_ADDRESS_BAR_ID, CHROME_ADDRESS_FORM_ID};

/// Default document/base URL used for resolving relative references inside the chrome frame.
///
/// Note: chrome-frame HTML should not contain relative navigations; all interactive targets should
/// be `chrome-action:` URLs. A parseable base URL still helps keep URL resolution deterministic.
const DEFAULT_CHROME_FRAME_URL: &str = "chrome://chrome-frame/";

#[derive(Debug, Default)]
pub struct ChromeFrameRuntimeOutput {
  pub actions: Vec<ChromeAction>,
  pub events: Vec<ChromeFrameEvent>,
}

impl ChromeFrameRuntimeOutput {
  pub fn push_action(&mut self, action: ChromeAction) {
    self.actions.push(action);
  }

  pub fn push_event(&mut self, event: ChromeFrameEvent) {
    self.events.push(event);
  }

  pub fn extend(&mut self, other: Self) {
    self.actions.extend(other.actions);
    self.events.extend(other.events);
  }
}

/// Renderer-chrome runtime for the `chrome_frame_html_from_state` document.
pub struct ChromeFrameRuntime {
  document: BrowserDocument,
  interaction: InteractionEngine,
  /// Handle to the dynamic chrome fetcher used by this runtime (favicons).
  chrome_dynamic_fetcher: ChromeDynamicAssetFetcher,
  /// Base render options (viewport + DPR) used when resetting the chrome document from fresh HTML.
  render_options: RenderOptions,
  /// Cached HTML string for change detection.
  last_html: String,
  address_bar_node_id: usize,
  address_form_node_id: usize,
  /// Cached address bar value for DOM-driven change detection.
  last_address_bar_value: String,
  /// Cached address bar focus state for DOM-driven change detection.
  last_address_bar_focused: bool,
}

impl ChromeFrameRuntime {
  /// Build a deterministic, trusted FastRender instance suitable for rendering chrome HTML.
  ///
  /// This configures:
  /// - bundled fonts only (determinism and no host font scans),
  /// - a trusted chrome fetcher stack (chrome:// allowlist + data: + no network/filesystem),
  /// - a stable `chrome://chrome-frame/` base URL.
  fn build_renderer() -> Result<(FastRender, ChromeDynamicAssetFetcher)> {
    let chrome_assets: Arc<dyn crate::resource::ResourceFetcher> =
      Arc::new(ChromeAssetsFetcher::new());
    let dynamic_fetcher = ChromeDynamicAssetFetcher::new(chrome_assets);
    let trusted_fetcher = TrustedChromeFetcher::new(Arc::new(dynamic_fetcher.clone()));

    // Keep renderer output deterministic in tests and in the browser-UI integration: use bundled
    // fonts and avoid host font discovery IO.
    let renderer = FastRender::builder()
      .base_url(DEFAULT_CHROME_FRAME_URL)
      .font_sources(crate::text::font_db::FontConfig::bundled_only())
      .fetcher(Arc::new(trusted_fetcher))
      .build()?;

    Ok((renderer, dynamic_fetcher))
  }

  pub fn new(app: &BrowserAppState, viewport_css: (u32, u32), dpr: f32) -> Result<Self> {
    let (renderer, dynamic_fetcher) = Self::build_renderer()?;
    Self::new_with_renderer(renderer, dynamic_fetcher, app, viewport_css, dpr)
  }

  pub fn new_with_renderer(
    renderer: FastRender,
    chrome_dynamic_fetcher: ChromeDynamicAssetFetcher,
    app: &BrowserAppState,
    viewport_css: (u32, u32),
    dpr: f32,
  ) -> Result<Self> {
    let html = chrome_frame_html_from_state(app);
    let render_options = RenderOptions::new()
      .with_viewport(viewport_css.0, viewport_css.1)
      .with_device_pixel_ratio(dpr);

    let mut document = BrowserDocument::new(renderer, &html, render_options.clone())?;
    document.set_document_url(Some(DEFAULT_CHROME_FRAME_URL.to_string()));

    let mut this = Self {
      document,
      interaction: InteractionEngine::new(),
      chrome_dynamic_fetcher,
      render_options,
      last_html: html,
      // Filled by `refresh_cached_dom_ids`.
      address_bar_node_id: 0,
      address_form_node_id: 0,
      last_address_bar_value: String::new(),
      last_address_bar_focused: false,
    };
    this.refresh_cached_dom_ids()?;
    // Seed caches from the initial DOM.
    this.last_address_bar_value = this.address_bar_value();
    Ok(this)
  }

  pub fn chrome_dynamic_fetcher(&self) -> &ChromeDynamicAssetFetcher {
    &self.chrome_dynamic_fetcher
  }

  pub fn document(&self) -> &BrowserDocument {
    &self.document
  }

  pub fn document_mut(&mut self) -> &mut BrowserDocument {
    &mut self.document
  }

  pub fn interaction(&self) -> &InteractionEngine {
    &self.interaction
  }

  pub fn interaction_mut(&mut self) -> &mut InteractionEngine {
    &mut self.interaction
  }

  fn refresh_cached_dom_ids(&mut self) -> Result<()> {
    let mut address_bar_node_id: Option<usize> = None;
    let mut address_form_node_id: Option<usize> = None;
    self.document.mutate_dom(|dom| {
      let index = DomIndex::build(dom);
      address_bar_node_id = index.id_by_element_id.get(CHROME_ADDRESS_BAR_ID).copied();
      address_form_node_id = index.id_by_element_id.get(CHROME_ADDRESS_FORM_ID).copied();
      false
    });

    self.address_bar_node_id = address_bar_node_id.ok_or_else(|| {
      Error::Other(format!(
        "chrome frame HTML missing required element id={CHROME_ADDRESS_BAR_ID:?}"
      ))
    })?;
    self.address_form_node_id = address_form_node_id.ok_or_else(|| {
      Error::Other(format!(
        "chrome frame HTML missing required element id={CHROME_ADDRESS_FORM_ID:?}"
      ))
    })?;
    Ok(())
  }

  fn ensure_layout_cache(&mut self) -> Result<()> {
    if self.document.prepared().is_none() {
      let _ = self.render_frame()?;
    }
    Ok(())
  }

  /// Replace the current chrome-frame DOM with a fresh HTML snapshot from browser state.
  ///
  /// Returns `true` when the underlying HTML changed (and therefore the document was reset).
  pub fn set_state(&mut self, app: &BrowserAppState) -> Result<bool> {
    let html = chrome_frame_html_from_state(app);
    if html == self.last_html {
      return Ok(false);
    }

    // Preserve address-bar caret/selection/IME state best-effort across DOM resets so frequent
    // `set_state` calls (e.g. omnibox suggestion updates) do not disrupt text editing.
    let prev_text_edit = self
      .interaction
      .interaction_state()
      .text_edit
      .filter(|edit| edit.node_id == self.address_bar_node_id);
    let prev_ime_preedit = self
      .interaction
      .interaction_state()
      .ime_preedit
      .clone()
      .filter(|ime| ime.node_id == self.address_bar_node_id);

    let should_focus_address_bar = app.chrome.address_bar_has_focus;

    self.document.reset_with_html(&html, self.render_options.clone())?;
    self.document.set_document_url(Some(DEFAULT_CHROME_FRAME_URL.to_string()));
    self.last_html = html;

    self.refresh_cached_dom_ids()?;

    // Reset interaction state: node ids can change when the chrome HTML changes (tabs added/removed,
    // omnibox popup updated, etc). Rehydrating a minimal subset is safer than trying to keep stale
    // node ids alive.
    self.interaction = InteractionEngine::new();
    self.last_address_bar_focused = false;

    if should_focus_address_bar {
      // Focus without emitting an event (state is the authoritative source).
      self.document.mutate_dom(|dom| {
        let _ = self
          .interaction
          .focus_node_id(dom, Some(self.address_bar_node_id), true);
        false
      });
      self.last_address_bar_focused = true;

      if let Some(edit) = prev_text_edit {
        match edit.selection {
          Some((start, end)) => self.interaction.set_text_selection_range(self.address_bar_node_id, start, end),
          None => self.interaction.set_text_selection_caret(self.address_bar_node_id, edit.caret),
        }
      }

      if let Some(ime) = prev_ime_preedit {
        let cursor = ime.cursor;
        let text = ime.text;
        self.document.mutate_dom(|dom| {
          let _ = self.interaction.ime_preedit(dom, &text, cursor);
          false
        });
      }
    }

    // Seed cached value from the (new) DOM so the first user edit is detected correctly.
    self.last_address_bar_value = self.address_bar_value();
    Ok(true)
  }

  pub fn render_if_needed(&mut self) -> Result<Option<crate::Pixmap>> {
    self
      .document
      .render_if_needed_with_interaction_state(Some(self.interaction.interaction_state()))
  }

  pub fn render_frame(&mut self) -> Result<crate::Pixmap> {
    self
      .document
      .render_frame_with_scroll_state_and_interaction_state(Some(self.interaction.interaction_state()))
      .map(|frame| frame.pixmap)
  }

  fn address_bar_value(&mut self) -> String {
    let mut out: Option<String> = None;
    let node_id = self.address_bar_node_id;
    self.document.mutate_dom(|dom| {
      let index = DomIndex::build(dom);
      out = index
        .node(node_id)
        .and_then(|node| node.get_attribute_ref("value"))
        .map(str::to_string);
      false
    });
    out.unwrap_or_default()
  }

  fn dispatch_focus_event_if_needed(&mut self, output: &mut ChromeFrameRuntimeOutput) {
    let focused = self.interaction.interaction_state().focused == Some(self.address_bar_node_id);
    if focused != self.last_address_bar_focused {
      self.last_address_bar_focused = focused;
      output.push_event(ChromeFrameEvent::AddressBarFocusChanged(focused));
    }
  }

  fn chrome_action_from_href(&self, href: &str) -> Result<ChromeAction> {
    let parsed = ChromeActionUrl::parse(href).map_err(|err| {
      Error::Other(format!(
        "blocked chrome-frame navigation to {href:?}: {err}"
      ))
    })?;
    parsed.into_chrome_action().map_err(|err| {
      Error::Other(format!("invalid chrome-action URL {href:?}: {err}"))
    })
  }

  fn output_for_interaction_action(&mut self, action: InteractionAction) -> Result<ChromeFrameRuntimeOutput> {
    let mut out = ChromeFrameRuntimeOutput::default();
    match action {
      InteractionAction::None => {}
      InteractionAction::FocusChanged { .. } => {
        // Defer to the shared focus-state checker so we also catch focus changes that occur alongside
        // other actions.
      }
      InteractionAction::Navigate { href }
      | InteractionAction::OpenInNewTab { href }
      | InteractionAction::OpenInNewWindow { href } => {
        out.push_action(self.chrome_action_from_href(&href)?);
      }
      InteractionAction::NavigateRequest { request }
      | InteractionAction::OpenInNewTabRequest { request } => {
        out.push_action(self.chrome_action_from_href(&request.url)?);
      }
      // Chrome documents should not include arbitrary downloads or non-chrome actions.
      InteractionAction::Download { href, .. } => {
        return Err(Error::Other(format!(
          "blocked chrome-frame download navigation to {href:?}: downloads are not allowed in chrome documents"
        )));
      }
      InteractionAction::TextDrop { .. }
      | InteractionAction::OpenSelectDropdown { .. }
      | InteractionAction::OpenDateTimePicker { .. }
      | InteractionAction::OpenColorPicker { .. }
      | InteractionAction::OpenFilePicker { .. }
      | InteractionAction::OpenMediaControls { .. } => {
        // Ignore: chrome-frame HTML should not contain these controls (yet). Embeddings can add a
        // richer surface later if needed.
      }
    }
    // Always check focus state after any interaction action: some actions (e.g. clicking a text
    // control) change focus but may not return `InteractionAction::FocusChanged` when another action
    // takes precedence.
    self.dispatch_focus_event_if_needed(&mut out);
    Ok(out)
  }

  pub fn focus_address_bar(&mut self) -> Result<ChromeFrameRuntimeOutput> {
    self.focus_node_id(Some(self.address_bar_node_id), true)
  }

  pub fn blur_address_bar(&mut self) -> Result<ChromeFrameRuntimeOutput> {
    self.focus_node_id(None, false)
  }

  pub fn focus_node_id(
    &mut self,
    node_id: Option<usize>,
    focus_visible: bool,
  ) -> Result<ChromeFrameRuntimeOutput> {
    let mut action: InteractionAction = InteractionAction::None;
    self.document.mutate_dom(|dom| {
      let (_changed, got_action) = self.interaction.focus_node_id(dom, node_id, focus_visible);
      action = got_action;
      // Focus changes are reflected via interaction state hashing; avoid invalidating DOM/layout.
      false
    });
    self.output_for_interaction_action(action)
  }

  fn mutate_address_bar_text(
    &mut self,
    mut f: impl FnMut(&mut InteractionEngine, &mut DomNode) -> bool,
  ) -> Result<ChromeFrameRuntimeOutput> {
    let mut after: Option<String> = None;
    let node_id = self.address_bar_node_id;

    self.document.mutate_dom(|dom| {
      let index = DomIndex::build(dom);
      let before = index
        .node(node_id)
        .and_then(|node| node.get_attribute_ref("value"))
        .unwrap_or("")
        .to_string();

      let _engine_changed = f(&mut self.interaction, dom);

      let index = DomIndex::build(dom);
      let next = index
        .node(node_id)
        .and_then(|node| node.get_attribute_ref("value"))
        .unwrap_or("")
        .to_string();

      if next != before {
        after = Some(next);
        true
      } else {
        // Avoid invalidating the document for interaction-only mutations (e.g. focus-visible).
        false
      }
    });

    let mut out = ChromeFrameRuntimeOutput::default();
    if let Some(after) = after {
      if after != self.last_address_bar_value {
        self.last_address_bar_value = after.clone();
      }
      out.push_event(ChromeFrameEvent::AddressBarTextChanged(after));
    }
    self.dispatch_focus_event_if_needed(&mut out);
    Ok(out)
  }

  pub fn text_input(&mut self, text: &str) -> Result<ChromeFrameRuntimeOutput> {
    self.mutate_address_bar_text(|engine, dom| engine.text_input(dom, text))
  }

  pub fn paste(&mut self, text: &str) -> Result<ChromeFrameRuntimeOutput> {
    self.mutate_address_bar_text(|engine, dom| engine.clipboard_paste(dom, text))
  }

  /// Update the active IME preedit (composition) string for the focused text control.
  pub fn ime_preedit(&mut self, text: &str, cursor: Option<(usize, usize)>) -> Result<bool> {
    let mut changed = false;
    self.document.mutate_dom(|dom| {
      changed = self.interaction.ime_preedit(dom, text, cursor);
      // IME preedit is non-DOM state; do not invalidate style/layout.
      false
    });
    Ok(changed)
  }

  pub fn ime_commit(&mut self, text: &str) -> Result<ChromeFrameRuntimeOutput> {
    self.mutate_address_bar_text(|engine, dom| engine.ime_commit(dom, text))
  }

  /// Cancel any active IME preedit string without mutating the DOM value.
  pub fn ime_cancel(&mut self) -> Result<bool> {
    let mut changed = false;
    self.document.mutate_dom(|dom| {
      changed = self.interaction.ime_cancel(dom);
      // IME cancel is non-DOM state; do not invalidate style/layout.
      false
    });
    Ok(changed)
  }

  pub fn key_activate(&mut self, key: KeyAction) -> Result<ChromeFrameRuntimeOutput> {
    let document_url = self
      .document
      .document_url()
      .unwrap_or(DEFAULT_CHROME_FRAME_URL)
      .to_string();
    let base_url = self
      .document
      .base_url()
      .unwrap_or(document_url.as_str())
      .to_string();

    let mut action: InteractionAction = InteractionAction::None;
    self.document.mutate_dom(|dom| {
      let (_changed, got_action) = self.interaction.key_activate(dom, key, &document_url, &base_url);
      action = got_action;
      // Keyboard activation should not invalidate the DOM cache unless it mutates DOM (text input
      // paths are handled via `text_input`/`paste`/`ime_commit`).
      false
    });
    self.output_for_interaction_action(action)
  }

  pub fn pointer_move(&mut self, viewport_point: Point) -> Result<bool> {
    self.ensure_layout_cache()?;
    let scroll = self.document.scroll_state();
    let interaction = &mut self.interaction;
    self.document.mutate_dom_with_layout_artifacts(|dom, box_tree, fragment_tree| {
      let scrolled_tree =
        (!scroll.elements.is_empty()).then(|| fragment_tree_with_scroll(fragment_tree, &scroll));
      let hit_tree = scrolled_tree.as_ref().unwrap_or(fragment_tree);
      let changed = interaction.pointer_move(dom, box_tree, hit_tree, &scroll, viewport_point);
      // Hover changes are represented in interaction state, so do not invalidate DOM/layout cache.
      (false, changed)
    })
  }

  pub fn pointer_down(&mut self, viewport_point: Point) -> Result<bool> {
    self.ensure_layout_cache()?;
    let scroll = self.document.scroll_state();
    let interaction = &mut self.interaction;
    self.document.mutate_dom_with_layout_artifacts(|dom, box_tree, fragment_tree| {
      let scrolled_tree =
        (!scroll.elements.is_empty()).then(|| fragment_tree_with_scroll(fragment_tree, &scroll));
      let hit_tree = scrolled_tree.as_ref().unwrap_or(fragment_tree);
      let changed = interaction.pointer_down_with_click_count(
        dom,
        box_tree,
        hit_tree,
        &scroll,
        viewport_point,
        PointerButton::Primary,
        PointerModifiers::NONE,
        1,
      );
      (false, changed)
    })
  }

  pub fn pointer_up(&mut self, viewport_point: Point) -> Result<ChromeFrameRuntimeOutput> {
    self.ensure_layout_cache()?;

    let scroll = self.document.scroll_state();
    let document_url = self
      .document
      .document_url()
      .unwrap_or(DEFAULT_CHROME_FRAME_URL)
      .to_string();
    let base_url = self
      .document
      .base_url()
      .unwrap_or(document_url.as_str())
      .to_string();

    let interaction = &mut self.interaction;
    let action = self.document.mutate_dom_with_layout_artifacts(|dom, box_tree, fragment_tree| {
      let scrolled_tree =
        (!scroll.elements.is_empty()).then(|| fragment_tree_with_scroll(fragment_tree, &scroll));
      let hit_tree = scrolled_tree.as_ref().unwrap_or(fragment_tree);
      let (_changed, action) = interaction.pointer_up_with_scroll(
        dom,
        box_tree,
        hit_tree,
        &scroll,
        viewport_point,
        PointerButton::Primary,
        PointerModifiers::NONE,
        true,
        &document_url,
        &base_url,
      );
      (false, action)
    })?;

    self.output_for_interaction_action(action)
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::dom::{DomNode, DomNodeType, HTML_NAMESPACE};
  use crate::interaction::KeyAction;
  use crate::ui::browser_app::BrowserAppState;
  use crate::ui::messages::TabId;
  use crate::ui::BrowserTabState;

  fn find_preorder_id_by_href(root: &DomNode, href: &str) -> Option<usize> {
    let mut next_id = 1usize;
    let mut stack: Vec<&DomNode> = vec![root];
    while let Some(node) = stack.pop() {
      let current_id = next_id;
      next_id += 1;
      if node.is_element()
        && node
          .get_attribute_ref("href")
          .is_some_and(|value| value == href)
      {
        return Some(current_id);
      }
      for child in node.children.iter().rev() {
        stack.push(child);
      }
    }
    None
  }

  fn insert_https_img(dom: &mut DomNode) -> bool {
    // Find <body>.
    let mut stack: Vec<&mut DomNode> = vec![dom];
    while let Some(node) = stack.pop() {
      if node
        .tag_name()
        .is_some_and(|tag| tag.eq_ignore_ascii_case("body"))
      {
        node.children.push(DomNode {
          node_type: DomNodeType::Element {
            tag_name: "img".to_string(),
            namespace: HTML_NAMESPACE.to_string(),
            attributes: vec![
              (
                "src".to_string(),
                "https://example.com/bad.png".to_string(),
              ),
              ("style".to_string(), "width:1px;height:1px".to_string()),
            ],
          },
          children: Vec::new(),
        });
        return true;
      }
      for child in node.children.iter_mut().rev() {
        stack.push(child);
      }
    }
    false
  }

  #[test]
  fn address_bar_submit_emits_chrome_action() -> Result<()> {
    let mut app = BrowserAppState::new();
    app.push_tab(BrowserTabState::new(TabId(1), "https://example.invalid/".to_string()), true);
    app.chrome.address_bar_text.clear();

    let mut runtime = ChromeFrameRuntime::new(&app, (360, 80), 1.0)?;
    // Prime the layout cache for pointer interactions (not strictly required for key activation).
    let _ = runtime.render_frame()?;

    let focus = runtime.focus_address_bar()?;
    assert!(
      focus
        .events
        .iter()
        .any(|e| matches!(e, ChromeFrameEvent::AddressBarFocusChanged(true))),
      "expected focus event when focusing address bar, got {:?}",
      focus.events
    );

    let typed = runtime.text_input("example.com")?;
    assert_eq!(
      typed.events,
      vec![ChromeFrameEvent::AddressBarTextChanged("example.com".to_string())]
    );

    let submitted = runtime.key_activate(KeyAction::Enter)?;
    assert_eq!(
      submitted.actions,
      vec![ChromeAction::NavigateTo("example.com".to_string())]
    );
    Ok(())
  }

  #[test]
  fn focused_chrome_action_link_emits_action() -> Result<()> {
    let mut app = BrowserAppState::new();
    app.push_tab(BrowserTabState::new(TabId(1), "https://example.invalid/".to_string()), true);
    let mut runtime = ChromeFrameRuntime::new(&app, (360, 80), 1.0)?;
    let _ = runtime.render_frame()?;

    let home_id = find_preorder_id_by_href(runtime.document.dom(), "chrome-action:home")
      .expect("expected toolbar home link");
    let _ = runtime.focus_node_id(Some(home_id), true)?;
    let out = runtime.key_activate(KeyAction::Enter)?;
    assert_eq!(out.actions, vec![ChromeAction::Home]);
    Ok(())
  }

  #[test]
  fn trusted_fetcher_blocks_https_subresource() -> Result<()> {
    let mut app = BrowserAppState::new();
    app.push_tab(BrowserTabState::new(TabId(1), "https://example.invalid/".to_string()), true);
    let mut runtime = ChromeFrameRuntime::new(&app, (360, 80), 1.0)?;

    runtime.document.mutate_dom(|dom| insert_https_img(dom));
    let err = runtime
      .render_frame()
      .expect_err("expected https subresource to be blocked");
    let msg = err.to_string();
    assert!(
      msg.contains("blocked by trusted chrome fetcher"),
      "unexpected error message: {msg}"
    );
    assert!(
      msg.contains("https://example.com/bad.png"),
      "expected URL in error message: {msg}"
    );
    Ok(())
  }
}
