// @generated by `bash scripts/cargo_agent.sh xtask webidl-bindings`. DO NOT EDIT.
//
// Source inputs:
// - src/webidl/generated/mod.rs (committed snapshot; produced by `bash scripts/cargo_agent.sh xtask webidl`)

use super::host::{BindingValue, WebHostBindings};

pub mod window {
  use std::collections::BTreeMap;

  use super::{BindingValue, WebHostBindings};

  use crate::js::webidl::conversions;
  use crate::js::webidl::DataPropertyAttributes;

  fn binding_value_to_js<Host, R>(
    rt: &mut R,
    value: BindingValue<R::JsValue>,
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    match value {
      BindingValue::Undefined => Ok(rt.js_undefined()),
      BindingValue::Null => Ok(rt.js_null()),
      BindingValue::Bool(b) => Ok(rt.js_bool(b)),
      BindingValue::Number(n) => Ok(rt.js_number(n)),
      BindingValue::String(s) => rt.js_string(&s),
      BindingValue::Object(v) => Ok(v),
      BindingValue::Callback(_) => {
        Err(rt.throw_type_error("cannot return callback handles to JavaScript"))
      }
      BindingValue::Sequence(values) | BindingValue::FrozenArray(values) => {
        let obj = rt.create_array(values.len())?;
        for (idx, item) in values.into_iter().enumerate() {
          let key = idx.to_string();
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(obj, &key, value, DataPropertyAttributes::new(true, true, true))?;
        }
        Ok(obj)
      }
      BindingValue::Dictionary(map) => {
        let obj = rt.create_object()?;
        for (key, item) in map {
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(obj, &key, value, DataPropertyAttributes::new(true, true, true))?;
        }
        Ok(obj)
      }
    }
  }

  #[allow(dead_code, unused_variables)]
  fn js_to_dict_add_event_listener_options<Host, R>(
    rt: &mut R,
    host: &mut Host,
    value: R::JsValue,
  ) -> Result<BindingValue<R::JsValue>, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    let is_missing = rt.is_undefined(value) || rt.is_null(value);
    if !is_missing && !rt.is_object(value) {
      return Err(rt.throw_type_error("expected object for dictionary AddEventListenerOptions"));
    }
    let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("capture")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("capture".to_string(), converted);
      } else {
        out_dict.insert("capture".to_string(), BindingValue::Bool(false));
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("once")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("once".to_string(), converted);
      } else {
        out_dict.insert("once".to_string(), BindingValue::Bool(false));
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("passive")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("passive".to_string(), converted);
      } else {
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("signal")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Object(js_member_value);
        out_dict.insert("signal".to_string(), converted);
      } else {
      }
    }
    Ok(BindingValue::Dictionary(out_dict))
  }

  #[allow(dead_code, unused_variables)]
  fn js_to_dict_event_listener_options<Host, R>(
    rt: &mut R,
    host: &mut Host,
    value: R::JsValue,
  ) -> Result<BindingValue<R::JsValue>, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    let is_missing = rt.is_undefined(value) || rt.is_null(value);
    if !is_missing && !rt.is_object(value) {
      return Err(rt.throw_type_error("expected object for dictionary EventListenerOptions"));
    }
    let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("capture")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("capture".to_string(), converted);
      } else {
        out_dict.insert("capture".to_string(), BindingValue::Bool(false));
      }
    }
    Ok(BindingValue::Dictionary(out_dict))
  }

  #[allow(dead_code)]
  fn event_target_add_event_listener<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_null(v1) || rt.is_undefined(v1) {
        BindingValue::Null
      } else {
        BindingValue::Callback(rt.root_callback_interface(v1)?)
      });
      let v2 = if args.len() > 2 {
        args[2]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v2) {
        js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
      } else {
        {
          if rt.is_null(v2) || rt.is_undefined(v2) {
            js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
          } else if rt.is_object(v2) {
            js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
          } else {
            BindingValue::Bool(rt.to_boolean(v2)?)
          }
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "addEventListener",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_dispatch_event<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "dispatchEvent",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_remove_event_listener<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_null(v1) || rt.is_undefined(v1) {
        BindingValue::Null
      } else {
        BindingValue::Callback(rt.root_callback_interface(v1)?)
      });
      let v2 = if args.len() > 2 {
        args[2]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v2) {
        js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
      } else {
        {
          if rt.is_null(v2) || rt.is_undefined(v2) {
            js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
          } else if rt.is_object(v2) {
            js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
          } else {
            BindingValue::Bool(rt.to_boolean(v2)?)
          }
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "removeEventListener",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result =
        host.call_operation(rt, None, "EventTarget", "constructor", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_to_j_s_o_n<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(rt, Some(this), "URL", "toJSON", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_can_parse<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "canParse", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_parse<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "parse", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "href")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_origin<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "origin")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_set_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let v0 = if args.len() > 0 {
      args[0]
    } else {
      rt.js_undefined()
    };
    let converted = {
      let s = rt.to_string(v0)?;
      BindingValue::String(rt.js_string_to_rust_string(s)?)
    };
    host.set_attribute(rt, Some(this), "URL", "href", converted)?;
    Ok(rt.js_undefined())
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_origin<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "origin")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "constructor", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_append<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v1)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "append",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_delete<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "delete",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_entries<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "entries",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_for_each<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        BindingValue::Object(v1)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "forEach",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "get", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get_all<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "getAll",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_has<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "has", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_keys<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "keys", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_set<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v1)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "set", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_values<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "values",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get_attribute_size<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URLSearchParams", "size")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v0) {
        BindingValue::String("".to_string())
      } else {
        BindingValue::Object(v0)
      });
      let result = host.call_operation(
        rt,
        None,
        "URLSearchParams",
        "constructor",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn window_alert<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let argcount = std::cmp::min(args.len(), 1);
    match argcount {
      0 => {
        {
          let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
          let result = host.call_operation(rt, None, "Window", "alert", 0, converted_args)?;
          binding_value_to_js::<Host, R>(rt, result)
        }
      },
      1 => {
        {
          let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
          let v0 = if args.len() > 0 { args[0] } else { rt.js_undefined() };
          converted_args.push({ let s = rt.to_string(v0)?; BindingValue::String(rt.js_string_to_rust_string(s)?) });
          let result = host.call_operation(rt, None, "Window", "alert", 1, converted_args)?;
          binding_value_to_js::<Host, R>(rt, result)
        }
      },
      _ => Err(rt.throw_type_error(&format!("No matching overload for Window.alert with {} arguments.\nCandidates:\n  - Window.alert()\n  - Window.alert(DOMString)", args.len()))),
    }
  }

  #[allow(dead_code)]
  fn window_clear_interval<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v0) {
        BindingValue::Number(0.0)
      } else {
        BindingValue::Number(conversions::to_long(
          rt,
          v0,
          conversions::IntegerConversionAttrs::default(),
        )? as f64)
      });
      let result = host.call_operation(rt, None, "Window", "clearInterval", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn window_clear_timeout<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v0) {
        BindingValue::Number(0.0)
      } else {
        BindingValue::Number(conversions::to_long(
          rt,
          v0,
          conversions::IntegerConversionAttrs::default(),
        )? as f64)
      });
      let result = host.call_operation(rt, None, "Window", "clearTimeout", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn window_queue_microtask<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Callback(rt.root_callback_function(v0)?));
      let result = host.call_operation(rt, None, "Window", "queueMicrotask", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn window_alert<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    // `Window.alert` is defined as `void alert(optional DOMString message = "")`.
    //
    // The legacy `webidl-js-runtime` bindings keep overloads as separate host operations, so we
    // dispatch based on argument count.
    let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
    let overload = if args.is_empty() { 0 } else { 1 };
    if overload == 1 {
      let v0 = args[0];
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
    }
    let result = host.call_operation(rt, None, "Window", "alert", overload, converted_args)?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn window_set_interval<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Number(0.0)
      } else {
        BindingValue::Number(conversions::to_long(
          rt,
          v1,
          conversions::IntegerConversionAttrs::default(),
        )? as f64)
      });
      let mut rest: Vec<BindingValue<R::JsValue>> = Vec::new();
      for v in args.iter().copied().skip(2) {
        rest.push(BindingValue::Object(v));
      }
      converted_args.push(BindingValue::Sequence(rest));
      let result = host.call_operation(rt, None, "Window", "setInterval", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn window_set_timeout<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Number(0.0)
      } else {
        BindingValue::Number(conversions::to_long(
          rt,
          v1,
          conversions::IntegerConversionAttrs::default(),
        )? as f64)
      });
      let mut rest: Vec<BindingValue<R::JsValue>> = Vec::new();
      for v in args.iter().copied().skip(2) {
        rest.push(BindingValue::Object(v));
      }
      converted_args.push(BindingValue::Sequence(rest));
      let result = host.call_operation(rt, None, "Window", "setTimeout", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn illegal_constructor<Host, R>(
    rt: &mut R,
    _host: &mut Host,
    _this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    Err(rt.throw_type_error("Illegal constructor"))
  }

  pub fn install_window_bindings<Host, R>(rt: &mut R, host: &mut Host) -> Result<(), R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let global = rt.global_object()?;
    let proto_event_target = rt.create_object()?;
    let proto_node = rt.create_object()?;
    let proto_u_r_l = rt.create_object()?;
    let proto_u_r_l_search_params = rt.create_object()?;
    rt.set_prototype(proto_node, Some(proto_event_target))?;
    let func = rt.create_function(
      "addEventListener",
      2,
      event_target_add_event_listener::<Host, R>,
    )?;
    rt.define_method(proto_event_target, "addEventListener", func)?;
    let func = rt.create_function("dispatchEvent", 1, event_target_dispatch_event::<Host, R>)?;
    rt.define_method(proto_event_target, "dispatchEvent", func)?;
    let func = rt.create_function(
      "removeEventListener",
      2,
      event_target_remove_event_listener::<Host, R>,
    )?;
    rt.define_method(proto_event_target, "removeEventListener", func)?;
    let ctor_event_target = rt.create_constructor(
      "EventTarget",
      0,
      illegal_constructor::<Host, R>,
      event_target_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "EventTarget", ctor_event_target, proto_event_target)?;
    let ctor_node = rt.create_constructor(
      "Node",
      0,
      illegal_constructor::<Host, R>,
      illegal_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "Node", ctor_node, proto_node)?;
    rt.define_constant(ctor_node, "ATTRIBUTE_NODE", rt.js_number(2.0))?;
    rt.define_constant(proto_node, "ATTRIBUTE_NODE", rt.js_number(2.0))?;
    rt.define_constant(ctor_node, "CDATA_SECTION_NODE", rt.js_number(4.0))?;
    rt.define_constant(proto_node, "CDATA_SECTION_NODE", rt.js_number(4.0))?;
    rt.define_constant(ctor_node, "COMMENT_NODE", rt.js_number(8.0))?;
    rt.define_constant(proto_node, "COMMENT_NODE", rt.js_number(8.0))?;
    rt.define_constant(ctor_node, "DOCUMENT_FRAGMENT_NODE", rt.js_number(11.0))?;
    rt.define_constant(proto_node, "DOCUMENT_FRAGMENT_NODE", rt.js_number(11.0))?;
    rt.define_constant(ctor_node, "DOCUMENT_NODE", rt.js_number(9.0))?;
    rt.define_constant(proto_node, "DOCUMENT_NODE", rt.js_number(9.0))?;
    rt.define_constant(
      ctor_node,
      "DOCUMENT_POSITION_CONTAINED_BY",
      rt.js_number(16.0),
    )?;
    rt.define_constant(
      proto_node,
      "DOCUMENT_POSITION_CONTAINED_BY",
      rt.js_number(16.0),
    )?;
    rt.define_constant(ctor_node, "DOCUMENT_POSITION_CONTAINS", rt.js_number(8.0))?;
    rt.define_constant(proto_node, "DOCUMENT_POSITION_CONTAINS", rt.js_number(8.0))?;
    rt.define_constant(
      ctor_node,
      "DOCUMENT_POSITION_DISCONNECTED",
      rt.js_number(1.0),
    )?;
    rt.define_constant(
      proto_node,
      "DOCUMENT_POSITION_DISCONNECTED",
      rt.js_number(1.0),
    )?;
    rt.define_constant(ctor_node, "DOCUMENT_POSITION_FOLLOWING", rt.js_number(4.0))?;
    rt.define_constant(proto_node, "DOCUMENT_POSITION_FOLLOWING", rt.js_number(4.0))?;
    rt.define_constant(
      ctor_node,
      "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      rt.js_number(32.0),
    )?;
    rt.define_constant(
      proto_node,
      "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
      rt.js_number(32.0),
    )?;
    rt.define_constant(ctor_node, "DOCUMENT_POSITION_PRECEDING", rt.js_number(2.0))?;
    rt.define_constant(proto_node, "DOCUMENT_POSITION_PRECEDING", rt.js_number(2.0))?;
    rt.define_constant(ctor_node, "DOCUMENT_TYPE_NODE", rt.js_number(10.0))?;
    rt.define_constant(proto_node, "DOCUMENT_TYPE_NODE", rt.js_number(10.0))?;
    rt.define_constant(ctor_node, "ELEMENT_NODE", rt.js_number(1.0))?;
    rt.define_constant(proto_node, "ELEMENT_NODE", rt.js_number(1.0))?;
    rt.define_constant(ctor_node, "ENTITY_NODE", rt.js_number(6.0))?;
    rt.define_constant(proto_node, "ENTITY_NODE", rt.js_number(6.0))?;
    rt.define_constant(ctor_node, "ENTITY_REFERENCE_NODE", rt.js_number(5.0))?;
    rt.define_constant(proto_node, "ENTITY_REFERENCE_NODE", rt.js_number(5.0))?;
    rt.define_constant(ctor_node, "NOTATION_NODE", rt.js_number(12.0))?;
    rt.define_constant(proto_node, "NOTATION_NODE", rt.js_number(12.0))?;
    rt.define_constant(ctor_node, "PROCESSING_INSTRUCTION_NODE", rt.js_number(7.0))?;
    rt.define_constant(
      proto_node,
      "PROCESSING_INSTRUCTION_NODE",
      rt.js_number(7.0),
    )?;
    rt.define_constant(ctor_node, "TEXT_NODE", rt.js_number(3.0))?;
    rt.define_constant(proto_node, "TEXT_NODE", rt.js_number(3.0))?;
    let func = rt.create_function("toJSON", 0, u_r_l_to_j_s_o_n::<Host, R>)?;
    rt.define_method(proto_u_r_l, "toJSON", func)?;
    let get = rt.create_function("get href", 0, u_r_l_get_attribute_href::<Host, R>)?;
    let set = rt.create_function("set href", 1, u_r_l_set_attribute_href::<Host, R>)?;
    rt.define_attribute_accessor(proto_u_r_l, "href", get, set)?;
    let get = rt.create_function("get origin", 0, u_r_l_get_attribute_origin::<Host, R>)?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(proto_u_r_l, "origin", get, set)?;
    let ctor_u_r_l = rt.create_constructor(
      "URL",
      1,
      illegal_constructor::<Host, R>,
      u_r_l_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "URL", ctor_u_r_l, proto_u_r_l)?;
    let func = rt.create_function("canParse", 1, u_r_l_can_parse::<Host, R>)?;
    rt.define_method(ctor_u_r_l, "canParse", func)?;
    let func = rt.create_function("parse", 1, u_r_l_parse::<Host, R>)?;
    rt.define_method(ctor_u_r_l, "parse", func)?;
    let func = rt.create_function("append", 2, u_r_l_search_params_append::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "append", func)?;
    let func = rt.create_function("delete", 1, u_r_l_search_params_delete::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "delete", func)?;
    let func = rt.create_function("entries", 0, u_r_l_search_params_entries::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "entries", func)?;
    let iterator_key = rt.symbol_iterator()?;
    rt.define_data_property(
      proto_u_r_l_search_params,
      iterator_key,
      func,
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.create_function("forEach", 1, u_r_l_search_params_for_each::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "forEach", func)?;
    let func = rt.create_function("get", 1, u_r_l_search_params_get::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "get", func)?;
    let func = rt.create_function("getAll", 1, u_r_l_search_params_get_all::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "getAll", func)?;
    let func = rt.create_function("has", 1, u_r_l_search_params_has::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "has", func)?;
    let func = rt.create_function("keys", 0, u_r_l_search_params_keys::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "keys", func)?;
    let func = rt.create_function("set", 2, u_r_l_search_params_set::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "set", func)?;
    let func = rt.create_function("values", 0, u_r_l_search_params_values::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "values", func)?;
    let get = rt.create_function(
      "get size",
      0,
      u_r_l_search_params_get_attribute_size::<Host, R>,
    )?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(proto_u_r_l_search_params, "size", get, set)?;
    let ctor_u_r_l_search_params = rt.create_constructor(
      "URLSearchParams",
      0,
      illegal_constructor::<Host, R>,
      u_r_l_search_params_constructor::<Host, R>,
    )?;
    rt.define_constructor(
      global,
      "URLSearchParams",
      ctor_u_r_l_search_params,
      proto_u_r_l_search_params,
    )?;
    let func = rt.create_function("alert", 0, window_alert::<Host, R>)?;
    rt.define_method(global, "alert", func)?;
    let func = rt.create_function("clearInterval", 0, window_clear_interval::<Host, R>)?;
    rt.define_method(global, "clearInterval", func)?;
    let func = rt.create_function("clearTimeout", 0, window_clear_timeout::<Host, R>)?;
    rt.define_method(global, "clearTimeout", func)?;
    let func = rt.create_function("alert", 0, window_alert::<Host, R>)?;
    rt.define_method(global, "alert", func)?;
    let func = rt.create_function("queueMicrotask", 1, window_queue_microtask::<Host, R>)?;
    rt.define_method(global, "queueMicrotask", func)?;
    let func = rt.create_function("setInterval", 1, window_set_interval::<Host, R>)?;
    rt.define_method(global, "setInterval", func)?;
    let func = rt.create_function("setTimeout", 1, window_set_timeout::<Host, R>)?;
    rt.define_method(global, "setTimeout", func)?;
    let _ = host;
    Ok(())
  }
}

pub mod worker {
  use std::collections::BTreeMap;

  use super::{BindingValue, WebHostBindings};
  use crate::js::webidl::DataPropertyAttributes;

  fn binding_value_to_js<Host, R>(
    rt: &mut R,
    value: BindingValue<R::JsValue>,
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    match value {
      BindingValue::Undefined => Ok(rt.js_undefined()),
      BindingValue::Null => Ok(rt.js_null()),
      BindingValue::Bool(b) => Ok(rt.js_bool(b)),
      BindingValue::Number(n) => Ok(rt.js_number(n)),
      BindingValue::String(s) => rt.js_string(&s),
      BindingValue::Object(v) => Ok(v),
      BindingValue::Callback(_) => {
        Err(rt.throw_type_error("cannot return callback handles to JavaScript"))
      }
      BindingValue::Sequence(values) | BindingValue::FrozenArray(values) => {
        let obj = rt.create_array(values.len())?;
        for (idx, item) in values.into_iter().enumerate() {
          let key = idx.to_string();
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(obj, &key, value, DataPropertyAttributes::new(true, true, true))?;
        }
        Ok(obj)
      }
      BindingValue::Dictionary(map) => {
        let obj = rt.create_object()?;
        for (key, item) in map {
          let value = binding_value_to_js::<Host, R>(rt, item)?;
          rt.define_data_property_str(obj, &key, value, DataPropertyAttributes::new(true, true, true))?;
        }
        Ok(obj)
      }
    }
  }

  #[allow(dead_code, unused_variables)]
  fn js_to_dict_add_event_listener_options<Host, R>(
    rt: &mut R,
    host: &mut Host,
    value: R::JsValue,
  ) -> Result<BindingValue<R::JsValue>, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    let is_missing = rt.is_undefined(value) || rt.is_null(value);
    if !is_missing && !rt.is_object(value) {
      return Err(rt.throw_type_error("expected object for dictionary AddEventListenerOptions"));
    }
    let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("capture")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("capture".to_string(), converted);
      } else {
        out_dict.insert("capture".to_string(), BindingValue::Bool(false));
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("once")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("once".to_string(), converted);
      } else {
        out_dict.insert("once".to_string(), BindingValue::Bool(false));
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("passive")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("passive".to_string(), converted);
      } else {
      }
    }
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("signal")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Object(js_member_value);
        out_dict.insert("signal".to_string(), converted);
      } else {
      }
    }
    Ok(BindingValue::Dictionary(out_dict))
  }

  #[allow(dead_code, unused_variables)]
  fn js_to_dict_event_listener_options<Host, R>(
    rt: &mut R,
    host: &mut Host,
    value: R::JsValue,
  ) -> Result<BindingValue<R::JsValue>, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    let is_missing = rt.is_undefined(value) || rt.is_null(value);
    if !is_missing && !rt.is_object(value) {
      return Err(rt.throw_type_error("expected object for dictionary EventListenerOptions"));
    }
    let mut out_dict: BTreeMap<String, BindingValue<R::JsValue>> = BTreeMap::new();
    {
      let js_member_value = if is_missing {
        rt.js_undefined()
      } else {
        let key = rt.property_key("capture")?;
        rt.get(value, key)?
      };
      if !rt.is_undefined(js_member_value) {
        let converted = BindingValue::Bool(rt.to_boolean(js_member_value)?);
        out_dict.insert("capture".to_string(), converted);
      } else {
        out_dict.insert("capture".to_string(), BindingValue::Bool(false));
      }
    }
    Ok(BindingValue::Dictionary(out_dict))
  }

  #[allow(dead_code)]
  fn event_target_add_event_listener<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_null(v1) || rt.is_undefined(v1) {
        BindingValue::Null
      } else {
        BindingValue::Callback(rt.root_callback_interface(v1)?)
      });
      let v2 = if args.len() > 2 {
        args[2]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v2) {
        js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
      } else {
        {
          if rt.is_null(v2) || rt.is_undefined(v2) {
            js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
          } else if rt.is_object(v2) {
            js_to_dict_add_event_listener_options::<Host, R>(rt, host, v2)?
          } else {
            BindingValue::Bool(rt.to_boolean(v2)?)
          }
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "addEventListener",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_dispatch_event<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "dispatchEvent",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_remove_event_listener<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_null(v1) || rt.is_undefined(v1) {
        BindingValue::Null
      } else {
        BindingValue::Callback(rt.root_callback_interface(v1)?)
      });
      let v2 = if args.len() > 2 {
        args[2]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v2) {
        js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
      } else {
        {
          if rt.is_null(v2) || rt.is_undefined(v2) {
            js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
          } else if rt.is_object(v2) {
            js_to_dict_event_listener_options::<Host, R>(rt, host, v2)?
          } else {
            BindingValue::Bool(rt.to_boolean(v2)?)
          }
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "EventTarget",
        "removeEventListener",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn event_target_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result =
        host.call_operation(rt, None, "EventTarget", "constructor", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_to_j_s_o_n<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(rt, Some(this), "URL", "toJSON", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_can_parse<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "canParse", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_parse<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "parse", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "href")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_origin<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "origin")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_set_attribute_href<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let v0 = if args.len() > 0 {
      args[0]
    } else {
      rt.js_undefined()
    };
    let converted = {
      let s = rt.to_string(v0)?;
      BindingValue::String(rt.js_string_to_rust_string(s)?)
    };
    host.set_attribute(rt, Some(this), "URL", "href", converted)?;
    Ok(rt.js_undefined())
  }

  #[allow(dead_code)]
  fn u_r_l_get_attribute_origin<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URL", "origin")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(rt, None, "URL", "constructor", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_append<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v1)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "append",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_delete<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "delete",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_entries<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "entries",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_for_each<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(BindingValue::Object(v0));
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        BindingValue::Object(v1)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "forEach",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "get", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get_all<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "getAll",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_has<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v1) {
        BindingValue::Undefined
      } else {
        {
          let s = rt.to_string(v1)?;
          BindingValue::String(rt.js_string_to_rust_string(s)?)
        }
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "has", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_keys<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "keys", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_set<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v0)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let v1 = if args.len() > 1 {
        args[1]
      } else {
        rt.js_undefined()
      };
      converted_args.push({
        let s = rt.to_string(v1)?;
        BindingValue::String(rt.js_string_to_rust_string(s)?)
      });
      let result =
        host.call_operation(rt, Some(this), "URLSearchParams", "set", 0, converted_args)?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_values<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let result = host.call_operation(
        rt,
        Some(this),
        "URLSearchParams",
        "values",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_get_attribute_size<Host, R>(
    rt: &mut R,
    host: &mut Host,
    this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    if !rt.is_object(this) {
      return Err(rt.throw_type_error("Illegal invocation"));
    }
    let result = host.get_attribute(rt, Some(this), "URLSearchParams", "size")?;
    binding_value_to_js::<Host, R>(rt, result)
  }

  #[allow(dead_code)]
  fn u_r_l_search_params_constructor<Host, R>(
    rt: &mut R,
    host: &mut Host,
    _this: R::JsValue,
    args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    {
      let mut converted_args: Vec<BindingValue<R::JsValue>> = Vec::new();
      let v0 = if args.len() > 0 {
        args[0]
      } else {
        rt.js_undefined()
      };
      converted_args.push(if rt.is_undefined(v0) {
        BindingValue::String("".to_string())
      } else {
        BindingValue::Object(v0)
      });
      let result = host.call_operation(
        rt,
        None,
        "URLSearchParams",
        "constructor",
        0,
        converted_args,
      )?;
      binding_value_to_js::<Host, R>(rt, result)
    }
  }

  #[allow(dead_code)]
  fn illegal_constructor<Host, R>(
    rt: &mut R,
    _host: &mut Host,
    _this: R::JsValue,
    _args: &[R::JsValue],
  ) -> Result<R::JsValue, R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
  {
    Err(rt.throw_type_error("Illegal constructor"))
  }

  pub fn install_worker_bindings<Host, R>(rt: &mut R, host: &mut Host) -> Result<(), R::Error>
  where
    R: crate::js::webidl::WebIdlBindingsRuntime<Host>,
    Host: WebHostBindings<R>,
  {
    let global = rt.global_object()?;
    let proto_event_target = rt.create_object()?;
    let proto_u_r_l = rt.create_object()?;
    let proto_u_r_l_search_params = rt.create_object()?;
    let func = rt.create_function(
      "addEventListener",
      2,
      event_target_add_event_listener::<Host, R>,
    )?;
    rt.define_method(proto_event_target, "addEventListener", func)?;
    let func = rt.create_function("dispatchEvent", 1, event_target_dispatch_event::<Host, R>)?;
    rt.define_method(proto_event_target, "dispatchEvent", func)?;
    let func = rt.create_function(
      "removeEventListener",
      2,
      event_target_remove_event_listener::<Host, R>,
    )?;
    rt.define_method(proto_event_target, "removeEventListener", func)?;
    let ctor_event_target = rt.create_constructor(
      "EventTarget",
      0,
      illegal_constructor::<Host, R>,
      event_target_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "EventTarget", ctor_event_target, proto_event_target)?;
    let func = rt.create_function("toJSON", 0, u_r_l_to_j_s_o_n::<Host, R>)?;
    rt.define_method(proto_u_r_l, "toJSON", func)?;
    let get = rt.create_function("get href", 0, u_r_l_get_attribute_href::<Host, R>)?;
    let set = rt.create_function("set href", 1, u_r_l_set_attribute_href::<Host, R>)?;
    rt.define_attribute_accessor(proto_u_r_l, "href", get, set)?;
    let get = rt.create_function("get origin", 0, u_r_l_get_attribute_origin::<Host, R>)?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(proto_u_r_l, "origin", get, set)?;
    let ctor_u_r_l = rt.create_constructor(
      "URL",
      1,
      illegal_constructor::<Host, R>,
      u_r_l_constructor::<Host, R>,
    )?;
    rt.define_constructor(global, "URL", ctor_u_r_l, proto_u_r_l)?;
    let func = rt.create_function("canParse", 1, u_r_l_can_parse::<Host, R>)?;
    rt.define_method(ctor_u_r_l, "canParse", func)?;
    let func = rt.create_function("parse", 1, u_r_l_parse::<Host, R>)?;
    rt.define_method(ctor_u_r_l, "parse", func)?;
    let func = rt.create_function("append", 2, u_r_l_search_params_append::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "append", func)?;
    let func = rt.create_function("delete", 1, u_r_l_search_params_delete::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "delete", func)?;
    let func = rt.create_function("entries", 0, u_r_l_search_params_entries::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "entries", func)?;
    let iterator_key = rt.symbol_iterator()?;
    rt.define_data_property(
      proto_u_r_l_search_params,
      iterator_key,
      func,
      DataPropertyAttributes::METHOD,
    )?;
    let func = rt.create_function("forEach", 1, u_r_l_search_params_for_each::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "forEach", func)?;
    let func = rt.create_function("get", 1, u_r_l_search_params_get::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "get", func)?;
    let func = rt.create_function("getAll", 1, u_r_l_search_params_get_all::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "getAll", func)?;
    let func = rt.create_function("has", 1, u_r_l_search_params_has::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "has", func)?;
    let func = rt.create_function("keys", 0, u_r_l_search_params_keys::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "keys", func)?;
    let func = rt.create_function("set", 2, u_r_l_search_params_set::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "set", func)?;
    let func = rt.create_function("values", 0, u_r_l_search_params_values::<Host, R>)?;
    rt.define_method(proto_u_r_l_search_params, "values", func)?;
    let get = rt.create_function(
      "get size",
      0,
      u_r_l_search_params_get_attribute_size::<Host, R>,
    )?;
    let set = rt.js_undefined();
    rt.define_attribute_accessor(proto_u_r_l_search_params, "size", get, set)?;
    let ctor_u_r_l_search_params = rt.create_constructor(
      "URLSearchParams",
      0,
      illegal_constructor::<Host, R>,
      u_r_l_search_params_constructor::<Host, R>,
    )?;
    rt.define_constructor(
      global,
      "URLSearchParams",
      ctor_u_r_l_search_params,
      proto_u_r_l_search_params,
    )?;
    let _ = host;
    Ok(())
  }
}

pub use window::install_window_bindings;
pub use worker::install_worker_bindings;
