use anyhow::{Context, Result};
use clap::Args;
use regex::Regex;
use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use walkdir::WalkDir;

const SCHEMA_VERSION: u32 = 2;
const TARGET_ITEM_COUNT: usize = 1000;

#[derive(Args, Debug, Clone)]
pub struct CapabilityMapArgs {
  /// Write a human-readable capability map (markdown).
  #[arg(long, default_value = "docs/capability_map.md")]
  pub out_md: PathBuf,

  /// Optionally write a machine-readable capability map (JSON).
  #[arg(long)]
  pub out_json: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
enum PriorityTier {
  P0,
  P1,
  P2,
  P3,
}

impl PriorityTier {
  fn label(self) -> &'static str {
    match self {
      Self::P0 => "P0",
      Self::P1 => "P1",
      Self::P2 => "P2",
      Self::P3 => "P3",
    }
  }
}

#[derive(Debug, Clone, Serialize)]
struct CapabilityItem {
  id: String,
  title: String,
  tier: PriorityTier,
  #[serde(skip_serializing_if = "Option::is_none")]
  why: Option<String>,
  #[serde(default, skip_serializing_if = "Vec::is_empty")]
  specs: Vec<String>,
  #[serde(default, skip_serializing_if = "Vec::is_empty")]
  evidence: Vec<String>,
  #[serde(default, skip_serializing_if = "Option::is_none")]
  group: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
struct CapabilityMap {
  schema_version: u32,
  generated_at_commit: Option<String>,
  target_items: usize,
  items: Vec<CapabilityItem>,
}

pub fn run_capability_map(args: CapabilityMapArgs) -> Result<()> {
  let repo_root = crate::repo_root();
  let out_md = resolve_repo_path(&repo_root, &args.out_md);
  let out_json = args
    .out_json
    .as_ref()
    .map(|p| resolve_repo_path(&repo_root, p));

  let items = build_items(&repo_root)?;
  let map = CapabilityMap {
    schema_version: SCHEMA_VERSION,
    generated_at_commit: current_git_sha(&repo_root),
    target_items: TARGET_ITEM_COUNT,
    items,
  };

  write_capability_map_markdown(&map, &out_md)?;
  if let Some(out_json) = out_json {
    write_json(&map, &out_json)?;
  }

  Ok(())
}

fn resolve_repo_path(repo_root: &Path, path: &Path) -> PathBuf {
  if path.is_absolute() {
    return path.to_path_buf();
  }
  repo_root.join(path)
}

fn ensure_parent_dir(path: &Path) -> Result<()> {
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent)
      .with_context(|| format!("create parent dir {}", parent.display()))?;
  }
  Ok(())
}

fn write_json<T: Serialize>(value: &T, path: &Path) -> Result<()> {
  ensure_parent_dir(path)?;
  let json = serde_json::to_string_pretty(value).context("serialize json")?;
  fs::write(path, json + "\n").with_context(|| format!("write {}", path.display()))?;
  Ok(())
}

fn write_capability_map_markdown(map: &CapabilityMap, path: &Path) -> Result<()> {
  ensure_parent_dir(path)?;

  let mut items = map.items.clone();
  items.sort_by_key(|item| (item.tier, item.why.is_none(), item.id.clone()));

  let mut p0 = 0usize;
  let mut p1 = 0usize;
  let mut p2 = 0usize;
  let mut p3 = 0usize;
  for item in &items {
    match item.tier {
      PriorityTier::P0 => p0 += 1,
      PriorityTier::P1 => p1 += 1,
      PriorityTier::P2 => p2 += 1,
      PriorityTier::P3 => p3 += 1,
    }
  }

  let mut out = String::new();
  out.push_str("# Capability map (prioritized backlog)\n\n");
  out.push_str("This file is generated by `bash scripts/cargo_agent.sh xtask capability-map`.\n\n");
  out.push_str("Principles:\n");
  out.push_str("- Breadth-first (BFS), not depth-first (DFS): keep a frontier across subsystems (HTML/CSS/style/layout/paint/text/resources) instead of going deep on niche features.\n");
  out.push_str("- This is not a global coordination mechanism: if many agents are working, diversify across subsystems and avoid everyone piling onto the same hotspot file.\n");
  out.push_str("- Prefer spec-aligned evidence: WPT reftests, small offline fixtures, and targeted unit/layout/paint tests.\n\n");

  if let Some(commit) = &map.generated_at_commit {
    out.push_str(&format!("- Generated at commit: `{}`\n", commit));
  }
  out.push_str(&format!("- Target items: {}\n", map.target_items));
  out.push_str(&format!(
    "- Counts: P0={} P1={} P2={} P3={}\n\n",
    p0, p1, p2, p3
  ));

  out.push_str("Offline references:\n");
  out.push_str("- WHATWG HTML: `specs/whatwg-html/`\n");
  out.push_str("- CSSWG drafts: `specs/csswg-drafts/`\n\n");

  out.push_str("## P0 (foundational blockers)\n\n");
  write_tier_list(&mut out, &items, PriorityTier::P0);
  out.push_str("\n## P1 (common compounding features)\n\n");
  write_tier_list(&mut out, &items, PriorityTier::P1);
  out.push_str("\n## P2 (important but secondary)\n\n");
  write_tier_list(&mut out, &items, PriorityTier::P2);
  out.push_str("\n## P3 (long tail / niche)\n\n");
  write_tier_list(&mut out, &items, PriorityTier::P3);

  fs::write(path, out).with_context(|| format!("write {}", path.display()))?;
  Ok(())
}

fn write_tier_list(out: &mut String, items: &[CapabilityItem], tier: PriorityTier) {
  for item in items.iter().filter(|item| item.tier == tier) {
    let compact = item.why.is_none() && item.evidence.is_empty() && item.specs.len() <= 1;
    if compact {
      if let Some(spec) = item.specs.first() {
        out.push_str(&format!("- `{}`: {} ({})\n", item.id, item.title, spec));
      } else {
        out.push_str(&format!("- `{}`: {}\n", item.id, item.title));
      }
      continue;
    }

    out.push_str(&format!("- `{}`: {}\n", item.id, item.title));
    if let Some(why) = &item.why {
      out.push_str(&format!("  - why: {}\n", why));
    }
    if !item.specs.is_empty() {
      out.push_str("  - specs:\n");
      for spec in &item.specs {
        out.push_str(&format!("    - {}\n", spec));
      }
    }
    if !item.evidence.is_empty() {
      out.push_str("  - evidence:\n");
      for ev in &item.evidence {
        out.push_str(&format!("    - {}\n", ev));
      }
    }
  }
}

fn current_git_sha(repo_root: &Path) -> Option<String> {
  Command::new("git")
    .args(["rev-parse", "HEAD"])
    .current_dir(repo_root)
    .output()
    .ok()
    .and_then(|out| out.status.success().then_some(out.stdout))
    .and_then(|bytes| String::from_utf8(bytes).ok())
    .map(|s| s.trim().to_string())
    .filter(|s| !s.is_empty())
}

fn build_items(repo_root: &Path) -> Result<Vec<CapabilityItem>> {
  let mut items = Vec::new();

  // Curated keystones (high-signal, with rationale).
  items.extend(curated_items());

  // Algorithm-level backlog slices (break down "implement inline" etc into real work items).
  items.extend(algorithm_items());
  items.extend(csswg_mined_algorithm_items(repo_root)?);
  items.extend(html_mined_algorithm_items(repo_root)?);

  // Broad HTML surface area.
  items.extend(html_items());

  // CSS surface area mined from CSSWG drafts (properties/at-rules/functions; values as filler).
  items.extend(csswg_items(repo_root));

  // Deduplicate by id, keeping the highest priority tier and most informative entry.
  let mut by_id: HashMap<String, CapabilityItem> = HashMap::new();
  for item in items {
    match by_id.get(&item.id) {
      None => {
        by_id.insert(item.id.clone(), item);
      }
      Some(existing) => {
        let should_replace = item.tier < existing.tier
          || (item.tier == existing.tier && existing.why.is_none() && item.why.is_some());
        if should_replace {
          by_id.insert(item.id.clone(), item);
        }
      }
    }
  }

  let mut items: Vec<CapabilityItem> = by_id.into_values().collect();
  items.sort_by_key(|item| (item.tier, item.why.is_none(), item.id.clone()));

  // Keep all curated items (those with a `why`), then fill to target size.
  let must_keep_ids: HashSet<String> = items
    .iter()
    .filter(|item| item.why.is_some() || item.id.starts_with("alg."))
    .map(|item| item.id.clone())
    .collect();

  if items.len() > TARGET_ITEM_COUNT {
    let mut trimmed = Vec::with_capacity(TARGET_ITEM_COUNT);
    for item in &items {
      if must_keep_ids.contains(&item.id) {
        trimmed.push(item.clone());
      }
    }
    trimmed.sort_by_key(|item| (item.tier, item.why.is_none(), item.id.clone()));
    trimmed.truncate(TARGET_ITEM_COUNT);
    for item in &items {
      if trimmed.len() >= TARGET_ITEM_COUNT {
        break;
      }
      if must_keep_ids.contains(&item.id) {
        continue;
      }
      trimmed.push(item.clone());
    }
    trimmed.sort_by_key(|item| (item.tier, item.why.is_none(), item.id.clone()));
    return Ok(trimmed);
  }

  // If the spec scan produced fewer than 1000, add additional CSS value definitions to reach 1000.
  if items.len() < TARGET_ITEM_COUNT {
    let mut fill = csswg_value_filler(repo_root, TARGET_ITEM_COUNT - items.len());
    for item in fill.drain(..) {
      if !items.iter().any(|existing| existing.id == item.id) {
        items.push(item);
      }
      if items.len() >= TARGET_ITEM_COUNT {
        break;
      }
    }
    items.sort_by_key(|item| (item.tier, item.why.is_none(), item.id.clone()));
  }

  Ok(items)
}

fn curated_items() -> Vec<CapabilityItem> {
  vec![
    CapabilityItem {
      id: "keystone.css.cascade".to_string(),
      title: "CSS cascade/inheritance/shorthands/custom properties (correct computed styles)".to_string(),
      tier: PriorityTier::P0,
      why: Some("If computed styles are wrong, every downstream stage is wrong; invest here first.".to_string()),
      specs: vec!["specs/csswg-drafts/css-cascade-5/".to_string(), "specs/csswg-drafts/css-values-4/".to_string()],
      evidence: vec!["WPT reftests".to_string(), "unit tests for computed values".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.layout.ifc-bfc-floats".to_string(),
      title: "CSS2.1 block + inline formatting contexts (including floats)".to_string(),
      tier: PriorityTier::P0,
      why: Some("Most pages are dominated by BFC/IFC; float/IFC bugs create the worst clipping/bleeding failures.".to_string()),
      specs: vec!["specs/csswg-drafts/css2/".to_string()],
      evidence: vec!["WPT CSS2.1 reftests".to_string(), "layout regression tests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.layout.positioning".to_string(),
      title: "Positioning invariants (containing blocks, shrink-to-fit, percent bases, abspos/fixed)".to_string(),
      tier: PriorityTier::P0,
      why: Some("Incorrect containing blocks and percent bases break headers/footers/sidebars across the web.".to_string()),
      specs: vec!["specs/csswg-drafts/css-position-3/".to_string(), "specs/csswg-drafts/css2/".to_string()],
      evidence: vec!["WPT positioning reftests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.layout.flexbox".to_string(),
      title: "Flexbox correctness (intrinsics, auto-min sizing, alignment, abspos interaction)".to_string(),
      tier: PriorityTier::P0,
      why: Some("Modern UIs rely on flex; small flex bugs explode into gross layout breakage.".to_string()),
      specs: vec!["specs/csswg-drafts/css-flexbox-1/".to_string()],
      evidence: vec!["WPT flexbox reftests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.layout.grid".to_string(),
      title: "Grid correctness (auto placement, intrinsic sizing, alignment)".to_string(),
      tier: PriorityTier::P1,
      why: Some("Grid is common for major page scaffolding; correctness depends on intrinsic sizing.".to_string()),
      specs: vec!["specs/csswg-drafts/css-grid-2/".to_string()],
      evidence: vec!["WPT grid reftests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.layout.tables".to_string(),
      title: "Tables (HTML model + CSS2.1 §17) including spans and border models".to_string(),
      tier: PriorityTier::P0,
      why: Some("Tables still appear widely and failures are extremely visible.".to_string()),
      specs: vec!["specs/csswg-drafts/css2/".to_string(), "specs/whatwg-html/source".to_string()],
      evidence: vec!["WPT table reftests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.paint.stacking-clipping".to_string(),
      title: "Stacking contexts, z-index, overflow clipping, and paint order".to_string(),
      tier: PriorityTier::P0,
      why: Some("Wrong stacking/clip makes pages look fundamentally broken even with correct layout.".to_string()),
      specs: vec!["specs/csswg-drafts/css2/".to_string(), "specs/csswg-drafts/css-backgrounds-3/".to_string()],
      evidence: vec!["paint regression tests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.replaced.images-srcset".to_string(),
      title: "Replaced elements: images/SVG/object-fit/srcset/picture selection".to_string(),
      tier: PriorityTier::P0,
      why: Some("Missing icons/logos dominates perceived brokenness; responsive images are common.".to_string()),
      specs: vec!["specs/whatwg-html/source".to_string(), "specs/csswg-drafts/css-images-4/".to_string()],
      evidence: vec!["WPT image selection tests".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.forms.controls".to_string(),
      title: "Forms + form controls (UA defaults, sizing, baselines, appearance)".to_string(),
      tier: PriorityTier::P0,
      why: Some("Search boxes/buttons are the first thing users notice.".to_string()),
      specs: vec!["specs/whatwg-html/source".to_string(), "specs/csswg-drafts/css-ui-4/".to_string()],
      evidence: vec!["forms regression fixtures".to_string()],
      group: Some("keystone".to_string()),
    },
    CapabilityItem {
      id: "keystone.text.metrics".to_string(),
      title: "Text: font selection, metrics, line-height, wrapping, bidi".to_string(),
      tier: PriorityTier::P1,
      why: Some("Text dominates pixels; metric differences cascade into layout differences.".to_string()),
      specs: vec!["specs/csswg-drafts/css-text-4/".to_string(), "specs/csswg-drafts/css-fonts-4/".to_string()],
      evidence: vec!["WPT text reftests where feasible".to_string()],
      group: Some("keystone".to_string()),
    },
  ]
}

fn algorithm_items() -> Vec<CapabilityItem> {
  let mut out = Vec::new();

  // Inline formatting context (IFC) is not one feature; it is dozens of interacting algorithms.
  out.extend(alg_group(
    "inline",
    PriorityTier::P0,
    &[
      "specs/csswg-drafts/css2/Overview.bs",
      "specs/csswg-drafts/css-text-4/",
      "specs/csswg-drafts/css-writing-modes-3/",
    ],
    &[
      ("whitespace-collapsing", "Whitespace collapsing + segment boundaries (white-space)"),
      ("line-break-opportunities", "Line breaking opportunities and rules (wrapping)"),
      ("line-box-construction", "Line box construction (inline formatting, line boxes)"),
      ("inline-fragmentation", "Inline fragmentation across lines/columns/pages"),
      ("bidi-ordering", "Bidi reordering integration with line layout (UAX#9 integration)"),
      ("baseline-alignment", "Baseline alignment and dominant baselines in lines"),
      ("vertical-align", "vertical-align used values and alignment in line boxes"),
      ("text-indent", "text-indent interaction with first line and inline content"),
      ("text-align", "text-align / text-align-last / justification hooks"),
      ("word-letter-spacing", "word-spacing / letter-spacing application in shaping + layout"),
      ("inline-replaced", "Inline replaced elements sizing + alignment inside lines"),
      ("first-letter-first-line", "::first-letter / ::first-line layout interactions"),
      ("ruby-inline", "Ruby layout interactions with inline formatting"),
      ("list-marker-inline", "List marker inline alignment/placement with IFC"),
      ("overflow-ellipsis", "text-overflow / ellipsis shaping/layout integration (when supported)"),
    ],
  ));

  // Floats + clearance.
  out.extend(alg_group(
    "floats",
    PriorityTier::P0,
    &["specs/csswg-drafts/css2/Overview.bs", "specs/csswg-drafts/css-shapes-1/"],
    &[
      ("float-placement", "Float placement algorithm (left/right floats)"),
      ("float-intrusion", "Float intrusion/avoidance into line boxes"),
      ("clearance", "clear property + clearance calculation"),
      ("float-containing-blocks", "Containing block interactions for floats (percent bases)"),
      ("float-fragmentation", "Float behavior across fragmentation (columns/pages)"),
      ("shape-outside", "shape-outside interaction with line wrapping (if/when supported)"),
    ],
  ));

  // Block formatting context (BFC) + sizing.
  out.extend(alg_group(
    "block",
    PriorityTier::P0,
    &[
      "specs/csswg-drafts/css2/Overview.bs",
      "specs/csswg-drafts/css-box-3/",
      "specs/csswg-drafts/css-sizing-3/",
    ],
    &[
      ("block-width", "Block width computation (auto margins, shrink-to-fit cases)"),
      ("min-max", "min/max width/height constraint application"),
      ("percentage-resolution", "Percentage resolution rules and percentage bases"),
      ("margin-collapsing", "Margin collapsing (block formatting model)"),
      ("bfc-establishment", "BFC establishment conditions (overflow, floats, etc.)"),
      ("clearance-bfc", "Clearance and BFC interactions"),
      ("overflow-clipping", "Overflow clipping vs layout size (scroll containers)"),
    ],
  ));

  // Positioning algorithms.
  out.extend(alg_group(
    "positioning",
    PriorityTier::P0,
    &["specs/csswg-drafts/css-position-3/", "specs/csswg-drafts/css2/Overview.bs"],
    &[
      ("containing-block", "Containing block determination rules (static/relative/abs/fixed)"),
      ("static-position", "Static position calculation (abspos static pos)"),
      ("abspos-sizing", "Absolute positioning sizing algorithm (used values)"),
      ("abspos-position", "Absolute positioning offset resolution (top/right/bottom/left)"),
      ("fixed-position", "Fixed positioning relative to viewport / pages"),
      ("z-index-stacking", "z-index + positioned stacking context creation"),
    ],
  ));

  // Flexbox algorithms (break down the spec's layout algorithm).
  out.extend(alg_group(
    "flexbox",
    PriorityTier::P0,
    &["specs/csswg-drafts/css-flexbox-1/Overview.bs"],
    &[
      ("available-space", "Determine available main/cross space and definite sizes"),
      ("flex-base-size", "Flex base size + hypothetical main size computation"),
      ("line-collection", "Collect items into flex lines"),
      ("resolve-flexible-lengths", "Resolve flexible lengths algorithm"),
      ("cross-size", "Determine cross sizes (hypothetical, stretched, final)"),
      ("alignment", "justify-content / align-items / align-content resolution"),
      ("min-size-auto", "auto min-size behavior and intrinsic constraints"),
      ("baseline-alignment", "Baseline alignment in flex containers"),
      ("abspos-in-flex", "Abspos items in flex containers (static position)"),
    ],
  ));

  // Grid algorithms.
  out.extend(alg_group(
    "grid",
    PriorityTier::P1,
    &["specs/csswg-drafts/css-grid-1/Overview.bs", "specs/csswg-drafts/css-grid-2/"],
    &[
      ("track-sizing", "Grid track sizing algorithm"),
      ("auto-placement", "Grid auto-placement algorithm"),
      ("intrinsic-contributions", "Intrinsic size contributions in grid"),
      ("alignment", "Grid alignment and gutters (gap)"),
      ("abspos-in-grid", "Abspos items in grid containers"),
      ("subgrid", "Subgrid behavior (when supported)"),
    ],
  ));

  // Tables algorithms.
  out.extend(alg_group(
    "tables",
    PriorityTier::P0,
    &["specs/csswg-drafts/css2/Overview.bs", "specs/csswg-drafts/css-tables-3/"],
    &[
      ("anonymous-table-objects", "Anonymous table object generation rules"),
      ("fixed-layout", "Fixed table layout algorithm"),
      ("auto-layout", "Auto table layout algorithm"),
      ("col-width-distribution", "Column width distribution (spans, percentages, min/max)"),
      ("row-height-distribution", "Row height distribution (rowspans, baselines)"),
      ("border-collapse", "Border-collapsing conflict resolution and geometry"),
      ("caption-placement", "Caption placement and sizing"),
    ],
  ));

  // Painting/compositing algorithms.
  out.extend(alg_group(
    "paint",
    PriorityTier::P0,
    &[
      "specs/csswg-drafts/css2/Overview.bs",
      "specs/csswg-drafts/css-backgrounds-3/Overview.bs",
      "specs/csswg-drafts/css-color-4/",
      "specs/csswg-drafts/css-transforms-1/",
    ],
    &[
      ("stacking-contexts", "Stacking context creation + painting order"),
      ("background-paint", "Background painting (color/images positioning/tiling)"),
      ("border-paint", "Border painting (styles, radius, border-image)"),
      ("outline-paint", "Outline painting (ordering vs borders)"),
      ("box-shadow", "Box-shadow painting order and blur/spread geometry"),
      ("overflow-clip", "Overflow clipping and border-radius clip interactions"),
      ("opacity-compositing", "Opacity compositing and stacking interactions"),
      ("transforms", "Transform application order and containing block effects"),
    ],
  ));

  // Replaced elements sizing algorithms.
  out.extend(alg_group(
    "replaced",
    PriorityTier::P0,
    &["specs/csswg-drafts/css2/Overview.bs", "specs/csswg-drafts/css-images-4/"],
    &[
      ("intrinsic-size", "Intrinsic size determination (images/SVG)"),
      ("replaced-min-max", "Replaced min/max constraints with intrinsic sizes"),
      ("object-fit", "object-fit sizing algorithm"),
      ("object-position", "object-position alignment inside replaced content box"),
      ("aspect-ratio", "Aspect-ratio interaction with auto sizes"),
    ],
  ));

  // Form controls (layout + UA defaults) as algorithms, not just “make it look right”.
  out.extend(alg_group(
    "forms",
    PriorityTier::P0,
    &["specs/whatwg-html/source", "specs/csswg-drafts/css-ui-4/"],
    &[
      ("ua-default-styles", "UA default style rules for controls (baseline web expectations)"),
      ("control-intrinsic-size", "Intrinsic sizes for controls and replaced-box mapping"),
      ("control-baselines", "Baselines for inline form controls"),
      ("appearance-none", "appearance:none and fallback rendering model"),
      ("select-option-rendering", "<select>/<option> rendering model subset (static)"),
    ],
  ));

  out
}

fn alg_group(
  group: &str,
  tier: PriorityTier,
  specs: &[&str],
  entries: &[(&str, &str)],
) -> Vec<CapabilityItem> {
  let specs: Vec<String> = specs.iter().map(|s| (*s).to_string()).collect();
  entries
    .iter()
    .map(|(id, title)| CapabilityItem {
      id: format!("alg.{}.{}", group, id),
      title: title.to_string(),
      tier,
      why: None,
      specs: specs.clone(),
      evidence: Vec::new(),
      group: Some(format!("alg.{}", group)),
    })
    .collect()
}

fn html_items() -> Vec<CapabilityItem> {
  // Intentionally coarse: the goal is breadth reminders. Algorithms live in `docs/conformance.md`.
  let p0 = [
    "html", "head", "body", "base", "meta", "link", "style", "title",
    "div", "span", "p", "a", "img", "picture", "source",
    "ul", "ol", "li", "dl", "dt", "dd",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "colgroup", "col",
    "form", "label", "input", "button", "select", "option", "optgroup", "textarea", "fieldset", "legend",
  ];
  let p1 = [
    "main", "header", "footer", "nav", "section", "article", "aside",
    "strong", "em", "small", "br", "hr", "pre", "code",
    "blockquote", "q", "cite", "abbr", "time",
    "svg", "math",
    "iframe", "object", "embed",
    "video", "audio", "track", "canvas",
    "details", "summary", "dialog",
    "template",
  ];

  let mut out = Vec::new();
  for tag in p0 {
    out.push(CapabilityItem {
      id: format!("html.element.{}", tag),
      title: format!("HTML element: <{}>", tag),
      tier: PriorityTier::P0,
      why: None,
      specs: vec!["specs/whatwg-html/source".to_string()],
      evidence: Vec::new(),
      group: Some("html.element".to_string()),
    });
  }
  for tag in p1 {
    out.push(CapabilityItem {
      id: format!("html.element.{}", tag),
      title: format!("HTML element: <{}>", tag),
      tier: PriorityTier::P1,
      why: None,
      specs: vec!["specs/whatwg-html/source".to_string()],
      evidence: Vec::new(),
      group: Some("html.element".to_string()),
    });
  }
  out
}

#[derive(Debug, Clone)]
struct Heading {
  level: u8,
  id: String,
  title: String,
}

fn csswg_mined_algorithm_items(repo_root: &Path) -> Result<Vec<CapabilityItem>> {
  let csswg_root = repo_root.join("specs/csswg-drafts");
  if !csswg_root.is_dir() {
    return Ok(Vec::new());
  }

  // Note: Rust's regex crate does not support backreferences, so we match any closing `</hN>`.
  // The capture is still useful for `level` and the match is non-greedy.
  let heading_re = Regex::new(
    r#"(?s)<h([1-6])[^>]*\bid=['"]([^'"]+)['"][^>]*>(.*?)</h[1-6]>"#,
  )
  .context("compile heading regex")?;
  let strip_tags_re = Regex::new(r#"(?s)<[^>]+>"#).context("compile strip-tags regex")?;

  let mut out = Vec::new();
  for entry in fs::read_dir(&csswg_root).with_context(|| format!("read {}", csswg_root.display()))? {
    let entry = match entry {
      Ok(e) => e,
      Err(_) => continue,
    };
    let path = entry.path();
    if !path.is_dir() {
      continue;
    }
    let module = path
      .file_name()
      .and_then(|s| s.to_str())
      .unwrap_or("unknown")
      .to_string();

    // Only mine algorithm structure from higher-priority specs.
    if tier_for_csswg_module(&module) > PriorityTier::P1 {
      continue;
    }

    let overview_bs = path.join("Overview.bs");
    let overview_html = path.join("Overview.html");
    let (spec_path, contents) = if overview_bs.is_file() {
      let contents = fs::read_to_string(&overview_bs)
        .with_context(|| format!("read {}", overview_bs.display()))?;
      (format!("specs/csswg-drafts/{}/Overview.bs", module), contents)
    } else if overview_html.is_file() {
      let contents = fs::read_to_string(&overview_html)
        .with_context(|| format!("read {}", overview_html.display()))?;
      (format!("specs/csswg-drafts/{}/Overview.html", module), contents)
    } else {
      continue;
    };

    let headings = extract_headings(&contents, &heading_re, &strip_tags_re);
    out.extend(mined_algorithm_items_for_headings(
      &module,
      &spec_path,
      &headings,
    ));
  }

  Ok(out)
}

fn html_mined_algorithm_items(repo_root: &Path) -> Result<Vec<CapabilityItem>> {
  let html_source = repo_root.join("specs/whatwg-html/source");
  if !html_source.is_file() {
    return Ok(Vec::new());
  }

  // WHATWG HTML `source` is large; keep mining cheap by only extracting headings and selecting
  // those that look algorithmic.
  let heading_re = Regex::new(
    r#"(?s)<h([1-6])[^>]*\bid=['"]([^'"]+)['"][^>]*>(.*?)</h[1-6]>"#,
  )
  .context("compile heading regex")?;
  let strip_tags_re = Regex::new(r#"(?s)<[^>]+>"#).context("compile strip-tags regex")?;
  let contents =
    fs::read_to_string(&html_source).with_context(|| format!("read {}", html_source.display()))?;

  let headings = extract_headings(&contents, &heading_re, &strip_tags_re);
  Ok(mined_algorithm_items_for_headings(
    "html",
    "specs/whatwg-html/source",
    &headings,
  ))
}

fn extract_headings(contents: &str, heading_re: &Regex, strip_tags_re: &Regex) -> Vec<Heading> {
  let mut out = Vec::new();
  for caps in heading_re.captures_iter(contents) {
    let level: u8 = match caps.get(1).and_then(|m| m.as_str().parse().ok()) {
      Some(v) => v,
      None => continue,
    };
    let id = caps.get(2).map(|m| m.as_str()).unwrap_or("").trim().to_string();
    if id.is_empty() {
      continue;
    }
    let raw = caps.get(3).map(|m| m.as_str()).unwrap_or("");
    let mut title = strip_tags_re.replace_all(raw, "").to_string();
    title = title.replace('\n', " ");
    title = title.split_whitespace().collect::<Vec<_>>().join(" ");
    if title.is_empty() {
      continue;
    }
    out.push(Heading { level, id, title });
  }
  out
}

fn mined_algorithm_items_for_headings(
  module: &str,
  spec_path: &str,
  headings: &[Heading],
) -> Vec<CapabilityItem> {
  let mut out = Vec::new();

  // Root heuristic: headings that explicitly call out algorithms, or CSS2-style "Calculating ..."
  // sections. Then pull in a shallow subtree under each root so "Flex Layout Algorithm" breaks
  // into multiple items.
  for (idx, heading) in headings.iter().enumerate() {
    if !is_algorithm_root_heading(module, heading) {
      continue;
    }

    let tier = promote_tier(tier_for_csswg_module(module), 1);
    out.push(mined_heading_item(module, spec_path, heading, tier));

    let max_level = heading.level.saturating_add(2).min(6);
    for sub in headings.iter().skip(idx + 1) {
      if sub.level <= heading.level {
        break;
      }
      if sub.level > max_level {
        continue;
      }
      if is_ignorable_heading(&sub.title) {
        continue;
      }
      out.push(mined_heading_item(module, spec_path, sub, tier));
    }
  }

  out
}

fn mined_heading_item(
  module: &str,
  spec_path: &str,
  heading: &Heading,
  tier: PriorityTier,
) -> CapabilityItem {
  let id = sanitize_id_component(&heading.id);
  CapabilityItem {
    id: format!("alg.spec.{}.{}", module, id),
    title: format!("{}: {}", module, heading.title),
    tier,
    why: None,
    specs: vec![format!("{}#{}", spec_path, heading.id)],
    evidence: Vec::new(),
    group: Some(format!("alg.spec.{}", module)),
  }
}

fn is_ignorable_heading(title: &str) -> bool {
  let t = title.trim().to_lowercase();
  matches!(
    t.as_str(),
    "abstract"
      | "introduction"
      | "conformance"
      | "conformance requirements"
      | "terminology"
      | "references"
      | "acknowledgments"
      | "privacy considerations"
      | "security considerations"
      | "index"
  )
}

fn is_algorithm_root_heading(module: &str, heading: &Heading) -> bool {
  if is_ignorable_heading(&heading.title) {
    return false;
  }

  let title = heading.title.to_lowercase();
  let id = heading.id.to_lowercase();

  // WHATWG HTML is algorithm-heavy but doesn't always label sections as "algorithm".
  // Use HTML-specific keywords and signature-like headings as roots.
  if module == "html" {
    if heading.level <= 4
      && (id.contains("parsing")
        || id.contains("token")
        || id.contains("tree")
        || id.contains("insertion")
        || id.contains("url")
        || id.contains("fetch")
        || id.contains("encoding")
        || id.contains("charset")
        || id.contains("base")
        || id.contains("viewport")
        || id.contains("srcset")
        || id.contains("picture")
        || id.contains("image")
        || id.contains("img")
        || id.contains("form")
        || id.contains("submission")
        || title.contains("parsing")
        || title.contains("tokenization")
        || title.contains("tree construction")
        || title.contains("insertion mode")
        || title.contains("url")
        || title.contains("fetch")
        || title.contains("encoding")
        || title.contains("base url")
        || title.contains("srcset")
        || title.contains("picture")
        || title.contains("image")
        || title.contains("form submission"))
    {
      return true;
    }

    // Avoid treating every internal method heading as a top-level priority for a no-JS renderer.
  }

  if id.contains("algorithm") || title.contains("algorithm") {
    return true;
  }

  // CSS2 and friends often describe algorithms as "Calculating ..." sections.
  if module == "css2" {
    if title.starts_with("calculating ")
      || title.starts_with("computing ")
      || title.starts_with("determining ")
      || title.contains("calculating the ")
      || title.contains("computed value")
      || title.contains("used value")
    {
      return true;
    }
  }

  // Broader heuristic for other core specs: "calculating/used value/sizing/layout/painting".
  if title.starts_with("calculating ")
    || title.starts_with("computing ")
    || title.starts_with("determining ")
    || title.contains("used value")
    || title.contains("computed value")
    || title.contains("layout")
    || title.contains("formatting")
    || title.contains("painting")
    || title.contains("sizing")
    || title.contains("fragmentation")
  {
    return true;
  }

  false
}

fn promote_tier(tier: PriorityTier, steps: u8) -> PriorityTier {
  let mut t = tier;
  for _ in 0..steps {
    t = match t {
      PriorityTier::P0 => PriorityTier::P0,
      PriorityTier::P1 => PriorityTier::P0,
      PriorityTier::P2 => PriorityTier::P1,
      PriorityTier::P3 => PriorityTier::P2,
    };
  }
  t
}

#[derive(Debug, Clone)]
struct BestDef {
  tier: PriorityTier,
  module: String,
}

fn csswg_items(repo_root: &Path) -> Vec<CapabilityItem> {
  let csswg_root = repo_root.join("specs/csswg-drafts");
  if !csswg_root.is_dir() {
    return Vec::new();
  }

  let mut defs = scan_csswg_link_defaults(&csswg_root);
  merge_defs(&mut defs, scan_csswg_propdefs(&csswg_root));

  let mut out = Vec::new();
  for ((kind, name), best) in defs {
    let (id, title, group) = csswg_item_identity(&kind, &name, &best.module);
    let tier = adjust_csswg_kind_tier(&kind, best.tier);
    let spec_path = csswg_spec_pointer(&best.module);
    out.push(CapabilityItem {
      id,
      title,
      tier,
      why: None,
      specs: vec![spec_path],
      evidence: Vec::new(),
      group: Some(group),
    });
  }

  out
}

fn csswg_value_filler(repo_root: &Path, limit: usize) -> Vec<CapabilityItem> {
  // Fallback only: mine extra keyword/value names from csswg drafts if the main scan is missing.
  let csswg_root = repo_root.join("specs/csswg-drafts");
  if !csswg_root.is_dir() || limit == 0 {
    return Vec::new();
  }

  let mut defs = scan_csswg_link_defaults(&csswg_root);
  defs.retain(|(kind, _), _| kind == "value");

  let mut out = Vec::new();
  for ((kind, name), best) in defs {
    if out.len() >= limit {
      break;
    }
    let (id, title, group) = csswg_item_identity(&kind, &name, &best.module);
    let tier = adjust_csswg_kind_tier(&kind, best.tier);
    out.push(CapabilityItem {
      id,
      title,
      tier,
      why: None,
      specs: vec![csswg_spec_pointer(&best.module)],
      evidence: Vec::new(),
      group: Some(group),
    });
  }
  out
}

fn merge_defs(
  into: &mut HashMap<(String, String), BestDef>,
  other: HashMap<(String, String), BestDef>,
) {
  for (key, def) in other {
    match into.get(&key) {
      None => {
        into.insert(key, def);
      }
      Some(existing) => {
        if def.tier < existing.tier {
          into.insert(key, def);
        }
      }
    }
  }
}

fn scan_csswg_link_defaults(csswg_root: &Path) -> HashMap<(String, String), BestDef> {
  let mut best: HashMap<(String, String), BestDef> = HashMap::new();

  for entry in WalkDir::new(csswg_root)
    .follow_links(false)
    .into_iter()
    .filter_map(|e| e.ok())
  {
    if !entry.file_type().is_file() {
      continue;
    }

    let path = entry.path();
    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    if ext != "bs" && ext != "html" {
      continue;
    }

    let contents = match fs::read_to_string(path) {
      Ok(s) => s,
      Err(_) => continue,
    };

    let file_module = csswg_module_name(csswg_root, path);

    let mut in_block = false;
    let mut current_spec: Option<String> = None;
    let mut current_type: Option<String> = None;

    for line in contents.lines() {
      let line = line.trim();

      if !in_block {
        if line.starts_with("<pre") && line.contains("link-defaults") {
          in_block = true;
          current_spec = None;
          current_type = None;
        }
        continue;
      }

      if line.starts_with("</pre") {
        in_block = false;
        continue;
      }

      let kvs = parse_semicolon_kvs(line);
      if kvs.is_empty() {
        continue;
      }

      for (key, value) in kvs {
        match key.as_str() {
          "spec" => current_spec = Some(normalize_csswg_spec(&value)),
          "type" => current_type = Some(value.trim().to_lowercase()),
          "text" => {
            let kind = match &current_type {
              Some(t) => t.clone(),
              None => continue,
            };
            let name = value.trim().to_string();
            if name.is_empty() {
              continue;
            }

            let module = current_spec.clone().unwrap_or_else(|| file_module.clone());
            let base_tier = tier_for_csswg_module(&module);

            best
              .entry((kind.clone(), name.clone()))
              .and_modify(|existing| {
                if base_tier < existing.tier {
                  existing.tier = base_tier;
                  existing.module = module.clone();
                }
              })
              .or_insert(BestDef {
                tier: base_tier,
                module,
              });
          }
          _ => {}
        }
      }
    }
  }

  best
}

fn scan_csswg_propdefs(csswg_root: &Path) -> HashMap<(String, String), BestDef> {
  let mut best: HashMap<(String, String), BestDef> = HashMap::new();

  for entry in WalkDir::new(csswg_root)
    .follow_links(false)
    .into_iter()
    .filter_map(|e| e.ok())
  {
    if !entry.file_type().is_file() {
      continue;
    }

    let path = entry.path();
    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    if ext != "bs" && ext != "html" {
      continue;
    }

    let contents = match fs::read_to_string(path) {
      Ok(s) => s,
      Err(_) => continue,
    };

    let module = csswg_module_name(csswg_root, path);
    let tier = tier_for_csswg_module(&module);

    let mut in_propdef = false;
    for line in contents.lines() {
      let line = line.trim();
      if !in_propdef {
        if line.starts_with("<pre") && line.contains("propdef") {
          in_propdef = true;
        }
        continue;
      }

      if line.starts_with("</pre") {
        in_propdef = false;
        continue;
      }

      if let Some(name) = line.strip_prefix("Name:") {
        let name = name.trim();
        if name.is_empty() {
          continue;
        }

        best
          .entry(("property".to_string(), name.to_string()))
          .and_modify(|existing| {
            if tier < existing.tier {
              existing.tier = tier;
              existing.module = module.clone();
            }
          })
          .or_insert(BestDef {
            tier,
            module: module.clone(),
          });
      }
    }
  }

  best
}

fn csswg_module_name(csswg_root: &Path, path: &Path) -> String {
  let rel = match path.strip_prefix(csswg_root) {
    Ok(p) => p,
    Err(_) => return "unknown".to_string(),
  };
  rel
    .components()
    .next()
    .and_then(|c| c.as_os_str().to_str())
    .unwrap_or("unknown")
    .to_string()
}

fn parse_semicolon_kvs(line: &str) -> Vec<(String, String)> {
  line
    .split(';')
    .map(|seg| seg.trim())
    .filter(|seg| !seg.is_empty())
    .filter_map(|seg| seg.split_once(':'))
    .map(|(k, v)| (k.trim().to_lowercase(), v.trim().to_string()))
    .collect()
}

fn normalize_csswg_spec(spec: &str) -> String {
  spec.trim().trim_end_matches(';').trim().to_string()
}

fn csswg_spec_pointer(module: &str) -> String {
  if module == "html" {
    return "specs/whatwg-html/source".to_string();
  }
  format!("specs/csswg-drafts/{}/", module)
}

fn csswg_item_identity(kind: &str, name: &str, module: &str) -> (String, String, String) {
  // Prefer stable ids, but keep titles human-friendly.
  let normalized_kind = kind.trim().to_lowercase();
  let name_for_id = sanitize_id_component(name);

  if normalized_kind == "element" && module == "html" {
    return (
      format!("html.element.{}", name_for_id),
      format!("HTML element: <{}>", name),
      "html.element".to_string(),
    );
  }

  match normalized_kind.as_str() {
    "property" => (
      format!("css.property.{}", name_for_id),
      format!("CSS property: {}", name),
      "css.property".to_string(),
    ),
    "value" => (
      format!("css.value.{}", name_for_id),
      format!("CSS value keyword: {}", name),
      "css.value".to_string(),
    ),
    "selector" => (
      format!("css.selector.{}", name_for_id),
      format!("CSS selector/pseudo: {}", name),
      "css.selector".to_string(),
    ),
    "type" => (
      format!("css.type.{}", name_for_id),
      format!("CSS value type: {}", name),
      "css.type".to_string(),
    ),
    "dfn" => (
      format!("css.concept.{}", name_for_id),
      format!("CSS concept: {}", name),
      "css.concept".to_string(),
    ),
    "function" => (
      format!("css.function.{}", name_for_id),
      format!("CSS function: {}()", name),
      "css.function".to_string(),
    ),
    "at-rule" | "at_rule" | "atrule" => (
      format!("css.at_rule.{}", name_for_id),
      format!("CSS at-rule: @{}", name.trim_start_matches('@')),
      "css.at_rule".to_string(),
    ),
    _ => (
      format!("css.{}.{}", normalized_kind, name_for_id),
      format!("CSS {}: {}", normalized_kind, name),
      format!("css.{}", normalized_kind),
    ),
  }
}

fn sanitize_id_component(value: &str) -> String {
  let mut out = String::with_capacity(value.len());
  for ch in value.chars() {
    if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
      out.push(ch);
    } else {
      out.push('_');
    }
  }
  out
}

fn adjust_csswg_kind_tier(kind: &str, base: PriorityTier) -> PriorityTier {
  // Values/selectors/types are more granular than properties; bias them slightly lower priority.
  match kind {
    "property" | "at-rule" | "at_rule" | "function" => base,
    "value" | "selector" => bump_tier(base, 1),
    "type" | "dfn" => bump_tier(base, 2),
    _ => bump_tier(base, 1),
  }
}

fn bump_tier(tier: PriorityTier, delta: u8) -> PriorityTier {
  let mut t = tier;
  for _ in 0..delta {
    t = match t {
      PriorityTier::P0 => PriorityTier::P1,
      PriorityTier::P1 => PriorityTier::P2,
      PriorityTier::P2 => PriorityTier::P3,
      PriorityTier::P3 => PriorityTier::P3,
    }
  }
  t
}

fn tier_for_csswg_module(module: &str) -> PriorityTier {
  // Rough mapping: prioritize the specs that dominate real pages first.
  let m = module;
  if m == "html" {
    return PriorityTier::P0;
  }
  // CSS2 is huge (and includes obsolete areas); treat it as important but not the top tier by itself.
  if m == "css2" {
    return PriorityTier::P1;
  }
  if m.starts_with("css-display") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-box") || m.starts_with("css-sizing") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-position") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-flexbox") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-grid") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-tables") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-backgrounds") {
    return PriorityTier::P0;
  }
  if m.starts_with("css-color") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-values") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-text") || m.starts_with("css-fonts") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-ui") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-transforms")
    || m.starts_with("css-masking")
    || m.starts_with("filter-effects")
  {
    return PriorityTier::P1;
  }
  if m.starts_with("css-multicol") || m.starts_with("css-break") {
    return PriorityTier::P1;
  }
  if m.starts_with("css-animations") || m.starts_with("css-transitions") {
    return PriorityTier::P2;
  }
  if m.starts_with("selectors") || m.starts_with("css-pseudo") {
    return PriorityTier::P1;
  }
  if m.starts_with("mediaqueries") {
    return PriorityTier::P1;
  }
  PriorityTier::P2
}
