use anyhow::{bail, Context, Result};
use clap::Args;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use xtask::webidl::resolve::ResolvedWebIdlWorld;

#[derive(Args, Debug)]
pub struct WebIdlCodegenArgs {
  /// Path to the WHATWG DOM Bikeshed source (`dom.bs`).
  #[arg(long, default_value = "specs/whatwg-dom/dom.bs", value_name = "FILE")]
  pub dom_source: PathBuf,

  /// Path to the WHATWG HTML spec source (`source`).
  #[arg(long, default_value = "specs/whatwg-html/source", value_name = "FILE")]
  pub html_source: PathBuf,

  /// Output Rust module path (relative to repo root unless absolute).
  #[arg(long, default_value = "src/webidl/generated/mod.rs", value_name = "FILE")]
  pub out: PathBuf,

  /// Do not write files; instead, fail if the generated output differs.
  #[arg(long)]
  pub check: bool,
}

pub fn run_webidl_codegen(args: WebIdlCodegenArgs) -> Result<()> {
  let repo_root = crate::repo_root();

  let dom_source = absolutize(repo_root.clone(), args.dom_source);
  let html_source = absolutize(repo_root.clone(), args.html_source);
  let out_path = absolutize(repo_root, args.out);

  let dom_text = fs::read_to_string(&dom_source)
    .with_context(|| format!("read DOM spec source {}", dom_source.display()))?;
  let html_text = fs::read_to_string(&html_source)
    .with_context(|| format!("read HTML spec source {}", html_source.display()))?;

  let mut idl = String::new();
  for block in xtask::webidl::extract_webidl_blocks(&dom_text) {
    idl.push_str(&block);
    idl.push_str("\n\n");
  }
  for block in xtask::webidl::extract_webidl_blocks(&html_text) {
    idl.push_str(&block);
    idl.push_str("\n\n");
  }

  let parsed = xtask::webidl::parse_webidl(&idl).context("parse extracted WebIDL")?;
  let resolved = xtask::webidl::resolve::resolve_webidl_world(&parsed);

  let generated = generate_rust_module(&resolved);

  if args.check {
    let existing = fs::read_to_string(&out_path)
      .with_context(|| format!("read generated file {}", out_path.display()))?;
    if existing != generated {
      bail!(
        "generated WebIDL bindings are out of date: run `cargo xtask webidl` (path={})",
        out_path.display()
      );
    }
    return Ok(());
  }

  if let Some(parent) = out_path.parent() {
    fs::create_dir_all(parent)
      .with_context(|| format!("create output directory {}", parent.display()))?;
  }
  fs::write(&out_path, generated)
    .with_context(|| format!("write generated output {}", out_path.display()))?;

  Ok(())
}

fn absolutize(repo_root: PathBuf, path: PathBuf) -> PathBuf {
  if path.is_absolute() {
    path
  } else {
    repo_root.join(path)
  }
}

fn generate_rust_module(world: &ResolvedWebIdlWorld) -> String {
  let mut out = String::new();

  writeln!(
    out,
    "// @generated by `cargo xtask webidl`. DO NOT EDIT.\n\
     //\n\
     // Source inputs:\n\
     // - specs/whatwg-dom/dom.bs\n\
     // - specs/whatwg-html/source\n\
     \n\
     use super::*;\n"
  )
  .expect("write to string must succeed");

  writeln!(out, "pub const WORLD: WebIdlWorld = WebIdlWorld {{").unwrap();
  writeln!(out, "  interfaces: &[").unwrap();
  for iface in world.interfaces.values() {
    write_interface(&mut out, iface, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "  interface_mixins: &[").unwrap();
  for mixin in world.interface_mixins.values() {
    write_interface_mixin(&mut out, mixin, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "  dictionaries: &[").unwrap();
  for dict in world.dictionaries.values() {
    write_dictionary(&mut out, dict, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "  enums: &[").unwrap();
  for en in world.enums.values() {
    write_enum(&mut out, en, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "  typedefs: &[").unwrap();
  for td in world.typedefs.values() {
    write_typedef(&mut out, td, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "  callbacks: &[").unwrap();
  for cb in world.callbacks.values() {
    write_callback(&mut out, cb, 2);
  }
  writeln!(out, "  ],").unwrap();

  writeln!(out, "}};\n").unwrap();

  out
}

fn write_interface(out: &mut String, iface: &xtask::webidl::resolve::ResolvedInterface, indent: usize) {
  indent_line(out, indent);
  writeln!(out, "WebIdlInterface {{").unwrap();

  indent_kv_str(out, indent + 2, "name", &iface.name);
  indent_kv_opt_str(out, indent + 2, "inherits", iface.inherits.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &iface.ext_attrs);

  indent_line(out, indent + 2);
  writeln!(out, "members: &[").unwrap();
  for member in &iface.members {
    write_interface_member(out, member, indent + 4);
  }
  indent_line(out, indent + 2);
  writeln!(out, "],").unwrap();

  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_interface_mixin(
  out: &mut String,
  mixin: &xtask::webidl::resolve::ResolvedInterfaceMixin,
  indent: usize,
) {
  indent_line(out, indent);
  writeln!(out, "WebIdlInterfaceMixin {{").unwrap();

  indent_kv_str(out, indent + 2, "name", &mixin.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &mixin.ext_attrs);

  indent_line(out, indent + 2);
  writeln!(out, "members: &[").unwrap();
  for member in &mixin.members {
    write_interface_member(out, member, indent + 4);
  }
  indent_line(out, indent + 2);
  writeln!(out, "],").unwrap();

  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_interface_member(
  out: &mut String,
  member: &xtask::webidl::resolve::ResolvedInterfaceMember,
  indent: usize,
) {
  indent_line(out, indent);
  writeln!(out, "WebIdlInterfaceMember {{").unwrap();
  indent_kv_opt_str(out, indent + 2, "name", member.name.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &member.ext_attrs);
  indent_kv_str(out, indent + 2, "raw", &member.raw);
  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_dictionary(
  out: &mut String,
  dict: &xtask::webidl::resolve::ResolvedDictionary,
  indent: usize,
) {
  indent_line(out, indent);
  writeln!(out, "WebIdlDictionary {{").unwrap();
  indent_kv_str(out, indent + 2, "name", &dict.name);
  indent_kv_opt_str(out, indent + 2, "inherits", dict.inherits.as_deref());
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &dict.ext_attrs);

  indent_line(out, indent + 2);
  writeln!(out, "members: &[").unwrap();
  for member in &dict.members {
    indent_line(out, indent + 4);
    writeln!(out, "WebIdlDictionaryMember {{").unwrap();
    indent_kv_opt_str(out, indent + 6, "name", member.name.as_deref());
    indent_kv_ext_attrs(out, indent + 6, "ext_attrs", &member.ext_attrs);
    indent_kv_str(out, indent + 6, "raw", &member.raw);
    indent_line(out, indent + 4);
    writeln!(out, "}},").unwrap();
  }
  indent_line(out, indent + 2);
  writeln!(out, "],").unwrap();

  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_enum(out: &mut String, en: &xtask::webidl::resolve::ResolvedEnum, indent: usize) {
  indent_line(out, indent);
  writeln!(out, "WebIdlEnum {{").unwrap();
  indent_kv_str(out, indent + 2, "name", &en.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &en.ext_attrs);

  indent_line(out, indent + 2);
  writeln!(out, "values: &[").unwrap();
  for value in &en.values {
    indent_line(out, indent + 4);
    writeln!(out, "{},", rust_string_literal(value)).unwrap();
  }
  indent_line(out, indent + 2);
  writeln!(out, "],").unwrap();

  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_typedef(out: &mut String, td: &xtask::webidl::resolve::ResolvedTypedef, indent: usize) {
  indent_line(out, indent);
  writeln!(out, "WebIdlTypedef {{").unwrap();
  indent_kv_str(out, indent + 2, "name", &td.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &td.ext_attrs);
  indent_kv_str(out, indent + 2, "type_", &td.type_);
  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn write_callback(out: &mut String, cb: &xtask::webidl::resolve::ResolvedCallback, indent: usize) {
  indent_line(out, indent);
  writeln!(out, "WebIdlCallback {{").unwrap();
  indent_kv_str(out, indent + 2, "name", &cb.name);
  indent_kv_ext_attrs(out, indent + 2, "ext_attrs", &cb.ext_attrs);
  indent_kv_str(out, indent + 2, "type_", &cb.type_);
  indent_line(out, indent);
  writeln!(out, "}},").unwrap();
}

fn indent_kv_str(out: &mut String, indent: usize, key: &str, value: &str) {
  indent_line(out, indent);
  writeln!(out, "{key}: {},", rust_string_literal(value)).unwrap();
}

fn indent_kv_opt_str(out: &mut String, indent: usize, key: &str, value: Option<&str>) {
  indent_line(out, indent);
  match value {
    Some(v) => writeln!(out, "{key}: Some({}),", rust_string_literal(v)).unwrap(),
    None => writeln!(out, "{key}: None,").unwrap(),
  }
}

fn indent_kv_ext_attrs(
  out: &mut String,
  indent: usize,
  key: &str,
  attrs: &[xtask::webidl::ExtendedAttribute],
) {
  indent_line(out, indent);
  writeln!(out, "{key}: &[").unwrap();
  for attr in attrs {
    indent_line(out, indent + 2);
    write!(
      out,
      "WebIdlExtendedAttribute {{ name: {}, value: ",
      rust_string_literal(&attr.name)
    )
    .unwrap();
    match &attr.value {
      Some(v) => write!(out, "Some({})", rust_string_literal(v)).unwrap(),
      None => out.push_str("None"),
    }
    out.push_str(" },\n");
  }
  indent_line(out, indent);
  writeln!(out, "],").unwrap();
}

fn indent_line(out: &mut String, indent: usize) {
  for _ in 0..indent {
    out.push(' ');
  }
}

fn rust_string_literal(value: &str) -> String {
  let mut out = String::with_capacity(value.len() + 2);
  out.push('"');
  for ch in value.chars() {
    out.extend(ch.escape_default());
  }
  out.push('"');
  out
}
